<table  width="100%" style="border:none !important;">
<tbody>
<?php
if(count($Results)>0){
	$i=1;
 foreach ($Results as $result) {
?>


<tr>
<td>
<a href="javascript:void(0);" id="countrysearch<?=$i;?>" onclick="putvalues('<?=$result->countryName?>','<?=$result->dialCode?>','<?=$result->countryCode?>','<?=$result->id?>');"><?= $result->countryName?></a>
</td>
</tr>
<?php
}
}
else echo "<p>No matched search</p>";
?>
</tbody>
</table>