<style>
    .modal-dialog {
        width: 67%;
    }

    .activestatus{
        color:green;
        background:green;
        border-radius:30px; width:15px; height:15px;
        cursor:pointer

    }

    .de-activestatus{
        color:green;
        background:red;
        border-radius:30px; width:15px; height:15px;
        cursor:pointer;


    }



</style>




<div class="row">
    <div class="col-xs-12"> 
        <!--<div class="row">
          <div class="space-6"></div>
          <div class="vspace-12-sm"></div>
        </div>-->


        <div class="row">
            <div class="col-xs-12">
                <h3  >Country Master</h3>
                <div class="filter">
                    <div class="panel-body" style="padding:0 !important">
                        <div class="col-lg-6">View Records>></div>
                    </div>
                </div>
                <div class="portlet-body">
                    <form id="bookingFilter" method="post" autocomplete="off" action="<?= $this->url
        ('admin/country', array('action' => 'performsearch'))
?>" onsubmit="return performsearch(this.id, '<?= $this->url('admin/country', array('action' => 'performsearch'))
?>', performsearchresults)">
                        <div id="myTabContent" class="tab-content">
                            <div class="tab-pane fade active in" id="home">
                                <div class="col-sm-col-sm-offset-1" style="margin: 10px auto 0px !important;padding: 0 10px;">
                                    <div class="row">
                                        <div class="form-group clearfix margintopbottom20">
                                            <label id="flight_nos" class="col-sm-2 control-label labelalign ">Country Name</label>
                                            <div class="col-sm-2 ">
                                                <input id="search_countryName" class=" form-control inputchange" placeholder="Country Name" type="text" 
                                                       onkeyup="countrysearchactions($(this).val(), '<?php echo $this->url('admin/country', array('action'=>'countrysearch'))?>', countrysearchresp, 'countryName')" name="country_name">
                                                <div class="col-sm-3" id="countrysearchresults" style="position: absolute;overflow-y:scroll;background:#FFF;width:93%;height:auto;z-index: 9999;display:none;">
                                                </div>                                    
                                            </div>

                                            <label id="point_airport" class="col-sm-2 control-label labelalign ">Country Code
                                            </label>
                                            <div class="col-sm-1">
                                                <input id="search_countryCode" class=" form-control inputchange" placeholder="Country Code" type="text"name="country_code">
                                            </div>

                                            <label id="flight_nos" class="col-sm-1 control-label labelalign ">Dial Code</label>
                                            <div class="col-sm-1 ">
                                                <input id="search_dialCode" class=" form-control inputchange" placeholder="Country Code" type="number"
                                                       name="dial_code">
                                            </div>  

                                            <div class="col-sm-1 ">
                                                <input class="btn btn-red defaultbtnsearch searchBooking"  type="submit" name="submit" value="Search">
                                            </div>
                                            <div class="col-sm-2 ">
                                               <a id="showaddform" class="btn btn-red defaultbtnsearch searchBooking" href="#"> Add</a>
                                            </div>


                                        </div>
                                    </div>
                                    <div class="row">
                                        <!--<div class="form-group clearfix margintopbottom20">
                   <label id="flight_nos" class="col-sm-2 control-label labelalign ">Dial Code</label>
                                          <div class="col-sm-3 ">
                                             <input id="search_dialCode" class=" form-control inputchange" placeholder="Country Code" type="number"
                                            name="dial_code">
                                             </div>  
                                              <label id="flight_nos" class="col-sm-2 control-label labelalign "></label>
                                          <div class="col-sm-1 ">
                                             <input class="btn btn-red defaultbtnsearch searchBooking"  type="submit" name="submit" value="Search">
                                             </div>
                                             <div class="col-sm-2 ">
                                             <input class="btn btn-red defaultbtnsearch" id="showaddform" style="background:#333 !important;"  type="submit" name="submit" value="Add Country">
                                             </div>
                                                                               
                                          </div>-->


                                        <div class="col-sm-3">

                                        </div>
                                    </div>
                                </div>



                            </div>
                        </div>
                    </form>
                </div>





                <div class="filter">
                    <div class="panel-body" style="padding:0 !important; cursor:pointer;">
                        <div class="col-lg-6" >Add Update Records>>
                        </div>
                        <!--<div class="col-lg-6" id="showaddform" align="right">+
                       </div>-->
                    </div>

                </div>
                <div id="addForm" class="tab-content dontshow">
                    <?php
                    $form = $this->form;
                    $form->prepare();


                    $form->setAttribute('action', $this->url('admin/country', array('action' => 'add')));
                    $form->setAttribute('method', 'post');
                    $form->setAttribute('autocomplete', 'off');
                    $form->setAttribute('id', 'CountryForm');
                    $action = $this->url('admin/country', array('action' => 'add'));
                    $form->setAttribute('onSubmit', "return SubmitFormAction($(this).attr('id'),'" . $action . "',addformResp)");

                    echo $this->form()->openTag($form);
// echo $this->formCollection($form);
                    ?>

                    <div class="tab-pane fade active in" id="driver_tab">
                        <div class="container col-sm-col-sm-offset-1" style="margin: 10px auto 0px !important;padding: 0 10px;">

                            <div class="row" style="position:relative;z-index:1;">
                                <div class="form-group clearfix margintopbottom20">

                                    <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                                        <?= $this->translate($form->get('country_name')->getLabel()) ?>
                                    </label>
                                    <div class="col-sm-2" id="addparent" >
                                        <?php
                                        echo $this->formHidden($form->get('id'));
                                        echo $this->formElement($form->get('country_name'));
                                        ?> 
                                        <span class="showerror"></span>   
                                        <div class="col-sm-3 searchboxresults" id="searchresults" style="position: absolute;
                                             overflow-y:scroll;
                                             background:#FFF;
                                             width:93%;
                                             height:auto;
                                             z-index: 9999;display:none;">
                                        </div>                                
                                    </div>


                                    <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                                        <?= $this->translate($form->get('country_code')->getLabel()) ?>
                                    </label>

                                    <div class="col-sm-1">
                                        <?php
                                        echo $this->formElement($form->get('country_code'));
                                        ?>  
                                        <span class="showerror"></span>                                   

                                    </div>


                                    <label id="flight_nos" class="col-sm-1 control-label labelalign ">
<?= $this->translate($form->get('dial_code')->getLabel()) ?>
                                    </label>

                                    <div class="col-sm-1" >
<?php
echo $this->formHidden($form->get('master_country_id'));
echo $this->formElement($form->get('dial_code'));
?>  
                                        <span class="showerror"></span>                                   

                                    </div>

                                    <div class="col-sm-1 pull-left">
<?php
echo $this->formRow($form->get('submit'));
?>                                    
                                    </div>
                                    <div class="col-sm-1 pull-left">
                                        <a class="btn btn-red defaultbtnsearch searchBooking" href="javascript:void(0);" onclick="location.reload();">Cancel</a>                              
                                    </div>

                                </div>
                            </div>
                            <!--<div class="row">
                               <div class="form-group clearfix margintopbottom20">
                                                        
                                
           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
<?= $this->translate($form->get('is_active')->getLabel()) ?>
          </label>
                                 <div class="col-sm-3">
<?php
echo $this->formElement($form->get('is_active'));
?> 
                                    <span class="showerror"></span>                                   
                                                                       
                                 </div>
                                </div>
                            </div>-->

                        </div>
                    </div>
<?php
echo $this->form()->closeTag();
?>
                </div>
                <div id="editForm" class="tab-content dontshow">
                </div>
                <div class="clearfix"></div>

                <div class="col-lg-12" style="background-color:#FFF;" id="radiosearch" fld="tbl_country">

                    <div class="col-lg-1"><div class="radio">
                            <label>
                                <input type="radio" value="1" id="optionsRadios1" name="optionsRadios" 
                                       onchange="RadioSearch($(this).val(), 'tbl_country', '<?php echo 
                                       $this->url('admin/country', array('action'=>'ajaxradiosearch'))?>',
                                                   radioSearchResult)" ><strong>Active</strong>
                            </label>
                            <br>

                        </div>




                    </div>


                    <div class="col-lg-1">
                        <div class="radio">
                            <label>
                                <input type="radio" value="0" id="optionsRadios1" name="optionsRadios" onchange=
                                    "RadioSearch($(this).val(), 'tbl_country', '<?php echo $this->url
                                            ('admin/country', array('action'=>'ajaxradiosearch'))?>', 
                                                        radioSearchResult)"><strong>In-Active</strong>
                            </label>


                        </div>
                    </div>




                    <div class="col-lg-2 pull-right">
                        <div class="delete">
                            <button class="btn btn-red defaultbtnsearch searchBooking" onclick=
                                "statuschangeall('<?php echo $this->url('admin/country', array('action'=>
                                    'changeStatusAll'))?>', statuschangeallresp, 0)">De-Activate Selected
                            </button>                                    
                        </div>
                    </div>

                    <div class="col-lg-2 pull-right">
                        <div class="delete">
                            <button class="btn btn-red defaultbtnsearch searchBooking" onclick=
                                "statuschangeall('<?php echo $this->url('admin/country', array
                                    ('action'=>'changeStatusAll'))?>', statuschangeallresp, 1)">
                                Activate Selected</button>                                    
                        </div>
                    </div>
                    <div class="col-lg-2 pull-right">
                        <div class="delete">
                            <button class="btn btn-red defaultbtnsearch searchBooking" onclick=
                                "delselected('<?php echo $this->url('admin/country', array('action'=>
                                    'delmultiple'))?>', delmultipleresp)">Delete Selected</button>                                              
                        </div>
                    </div>

                </div>

                <div class="col-sm-12">


                </div>


                <div class="col-md-12" id="country_data_list">

                    <?php echo $this->partial('admin/country/countryList.phtml'); ?>
                </div>
            </div>





            <div class="col-sm-12"> 

                <!-- /.widget-box -->
                <!--<div  style="margin-top:20px;"> <a href="#" class="btn btn-red defaultbtnsearch searchBooking"><i class="fa fa-search" id="search_me" style="color:#fff; margin:5px"></i>Refresh</a> </div>-->
            </div>
        </div>
        <!-- /.col --> 




        <a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse"> <i class="ace-icon fa fa-angle-double-up icon-only bigger-110"></i> </a> 

    </div></div>
<div id="viewCountryModel"></div>


<!-- /.main-container --> 

<!-- basic scripts --> 

<!--[if !IE]> -->



