
<div class="table-responsive">
                        <table id="dynamic-table" class="table table-striped table-bordered table-hover">
                            <thead>
                                <tr>

                                    <th><input type="checkbox" value="" id="checkAll" onclick="checkall(this.id)" ></th>
                                    <th>Sr. No. </th>
                                    <th>Country Name</th>
                                    <th>Dial Code</th>
                                    <th class="hidden-480">Country Code</th>                       
                                    <th class="hidden-480">Modified Date</th>
                                    <th class="hidden-480">Created Date</th>
                                    <th class="hidden-480">Status</th>
                                    <th class="hidden-480">Modified By</th>
                                    <th><b>Actions</b></th>
                                </tr>
                            </thead>
                            <tbody>
<?php
$i = 1;
if (count($results) > 0) {
foreach ($results as $country) {
    ?>

                                    <tr>
                                        <td><input type="checkbox" value="<?= $country->id ?>" class="checkme" name="checkme[]"></td> 
                                        <td><?= $i ?></td>
                                        <td ><?= $country->countryName ?></td>

                                        <td class="hidden-480"><?= $country->dialCode ?></td>
                                        <td><?= $country->countryCode ?></td>
                                        <td class="hidden-480"><?= $country->modifiedDate ?></td>
                                        <td class="hidden-480"><?= $country->createdDate ?></td>                                        
                                        <td class="hidden-480" align="center">

    <?php
    $status = ($country->isActive == 1) ? 'Active' : 'In-Active';
    $statuscolor = ($country->isActive == 1) ? 'activestatus' : 'de-activestatus';
    ?>
                                            <div name="ChangeStatus" id="changestatus<?= $i; ?>" onclick=
                                                "changestatusquick(<?= $country->id ?>,<?= ($country->
                                                        isActive == 0) ? 0 : 1; ?>, '<?php echo $this->
                                                                url('admin/country', array('action'=>
                                                                    'changestatus')); ?>', 
                                                                        changstatusresult);" class="<?= 
                                                        $statuscolor ?>">
                                            </div>

                                        </td>
                                        <td class="hidden-480"><?php echo ($country->modifiedBy == 1) ? 'Admin' : 'NotByAdmin'; ?></td>
                                        <td aria-expanded="false" class="accordion1"><div class="hidden-sm hidden-xs action-buttons"> 
                                                <a class="blue" style="cursor:pointer;" data-toggle="modal" data-target="#myModal"  
                                                   tar="indview<?= $i ?>"> <i onclick="findRowDataByCountryId('<?php echo $this->url
                                                           ('admin/country', array('action'=>'viewById','id'=>$country->id)); ?>', 
                                                                       viewRowDataById);" class="ace-icon fa fa-search-plus bigger-130">
                                                    </i> </a> <a class="green" href="javascript:void(0);" onclick="editbox(<?= 
                                                   $country->id ?>, '<?php echo $this->url('admin/country', array('action' => 
                                                       'edit', 'id' => $country->id));
                                        ?>', editformresp);" > <i class="ace-icon fa fa-pencil bigger-130"></i> </a> <a class="red" href="<?php echo $this->url('admin/country', array('action' => 'delete', 'id' => $country->id)); ?>" onclick="return confirm('are you sure you want to delete');"> <i class="ace-icon fa fa-trash-o bigger-130"></i> </a> </div>
                                        </td>
                                    </tr>

                                    <!-- <?php echo $this->url('admin', array('controller' => 'country', 'action' => 'edit', 'id' => $country->id)); ?> -->







    <?php
    $i++;
}
} else
        echo" <tr>
                         
                       <td colspan=9><center><h2>No data available</h2></center></td></tr>";
?>
                            </tbody>
                        </table>




                    </div>
