<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Modal Header</h4>
            </div>
            <div class="modal-body">


                <tr class="dontshow" id="indview" aria-expanded="true">

                    <td colspan="7">
                        <div aria-expanded="true" class="panel-body accordion-body packageDetails1 collapse in" id="accordion1">

                            <div class="tab-content" id="myTabContent">

                                <div class="col-sm-col-sm-offset-1" style="margin: 10px auto 0px !important;padding: 0 10px;">
                                    <div class="row">
                                        <div class="form-group clearfix margintopbottom20 col-sm-12">
                                            <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                                                <?= $this->translate('Country Name'); ?>
                                            </label>
                                            <div class="col-sm-3" id="country_name_modal">
                                                 <?php echo $info->country_name;?> 
                                            </div>
                                            <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                                                <?= $this->translate('Created Date'); ?>
                                            </label>
                                            <div class="col-sm-3">
                                                <?php
                                                echo date('l d-m-Y', strtotime($info->created_date));
                                                ?>                                    
                                            </div>

                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="form-group clearfix margintopbottom20 col-sm-12">
                                            <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                                                <?= $this->translate('Modified By'); ?>
                                            </label>
                                            <div class="col-sm-3">
                                                <?php
                                                echo ($info->modified_by == 1) ? 'Admin' : 'Not Available Now';
                                                ?>                                    
                                            </div>

                                            <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                                                <?= $this->translate('Status'); ?>
                                            </label>
                                            <div class="col-sm-3">
                                                <?php
                                                echo ($info->IsActive == 1) ? 'Active' : 'In-Active';
                                                ?>                                    
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="form-group clearfix margintopbottom20 col-sm-12">


                                            <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                                                <?= $this->translate('Modified Date'); ?>
                                            </label>
                                            <div class="col-sm-3">
                                                <?php
                                                echo date('l d-m-Y', strtotime($info->modified_date));
                                                ?>                                    
                                            </div>
                                        </div>
                                    </div>  

                                </div>

                            </div>
                        </div>


                    </td>
                </tr>   
            </div>
            <div class="modal-footer">
                <button type="button"data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>