<!-- onclick="showmodal('<?= $this->serverUrl().$this->url('admin',array('controller'=>'country','action'=>'view')) ?>','<?= $country->id ?>')" -->

<?php 

// echo"<pre>"; print_r($Info);die;
?>

 <div >
            <p>
              <a href="<?= $this->url('admin',array('controller'=>'country','action'=>'index'));?>"><button class="btn btn-warning btn-xlg">Go Back</button></a>
            </p>
          </div>
<div class="panel-body">
               
                <?php 
        // $form->setAttribute('action',$this->url('admin',array('controller'=>'Country','action'=>'add')));
                ?>
          <div id="myTabContent" class="tab-content">
            
            
            <div class="tab-pane fade active in" id="driver_tab">
              <div class="container col-sm-col-sm-offset-1" style="margin: 10px auto 0px !important;padding: 0 10px;">
                
                <div class="row">
                                                <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Country Name'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     
                                                     echo $Info->country_name;
                                                     ?>                                    
                                                  </div>
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Dial Code'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo $Info->dial_code;
                                                     ?>                                    
                                                  </div>
                                                 </div>
                                             </div>
                                             <div class="row">
                                                <div class="form-group clearfix margintopbottom20">
                          <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Country Code'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo $Info->country_code;
                                                     ?>                                    
                                                  </div>
                                                 
                            <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Status'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo ($Info->IsActive==1)? 'Active':'In-Active';
                                                     ?>                                    
                                                  </div>
                                                 </div>
                                             </div>

                                          <div class="row">
                                                <div class="form-group clearfix margintopbottom20">
                          <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Created Date'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo date('l d-m-Y',strtotime($Info->created_date));
                                                     ?>                                    
                                                  </div>
                                                 
                            <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Modified Date'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo date('l d-m-Y',strtotime($Info->modified_date));
                                                     ?>                                    
                                                  </div>
                                                 </div>
                                             </div>  
                                             <div class="row">
                                                <div class="form-group clearfix margintopbottom20">
                          <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Modified By'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo ($Info->modified_by==1)?'Admin':'Not Available Now';
                                                     ?>                                    
                                                  </div>
                                                 </div>
                                             </div>   




                                             
              </div>
            </div>
          </div>
      </div>