
<style>


.news
{
	height:;
}
</style>

<div class="col-sm-3 col-sm-3-new width20per">
<?php echo $this->partial('layout/sidebar-news') ?>
</div>

<div id="newsContainer"> 
<div class="col-sm-9 width80per">

<h2 class="heading">Latest News</h2>
<ul id="items">
<?php if(count($this->NewsData>0))
foreach ($NewsData as $Ndata){
?>
  <li>
<div class="col-md-6 news col-xs-12">
<div class="col-md-3 col-sm-2 col-xs-2 img">
  <?php if(!empty($Ndata->image_path)) $path=$Ndata->image_path;
  else $path="/images/new-big.jpg";
  ?>
  <a href="<?php echo $this->basePath()?>/news/view/<?=$Ndata->id?>">
<img src="<?php echo $this->basePath($path) ?>" class="img-responsive" /></a>
</div>
<div class="col-md-9 col-sm-10 col-xs-10 content">
<h4><a href="<?php echo $this->basePath()?>/news/view/<?=$Ndata->id?>"><?php echo $Ndata->title; ?></a></h4>
<p><?php echo $Ndata->description; ?></p>
<p><a href="<?php echo $this->basePath()?>/news/view/<?=$Ndata->id?>">Read Full Story >></a></p>
</div>
</div>
</li>
<?php 
}
else{

  ?>
<h2> No Data Available </h2>
  <?php 

}

?>

</ul>
<div class="clearfix"></div>

<!--<nav>
  <ul class="pagination">
  <li class="disabled"><a href="#">Pages:</a></li>
    <li><a href="#">1</a></li>
    <li><a href="#">2</a></li>
    <li><a href="#">3</a></li>
    <li><a href="#">4</a></li>
    <li><a href="#">5</a></li>
    <li><a href="#">6</a></li>
    <li><a href="#">7</a></li>
    <li class="disabled"><a href="#">.....</a></li>
  </ul>
</nav>-->
<div class="clearfix"></div>
</div>
</div>
