<div class="col-sm-9 width80per">

<h2 class="heading">Latest News</h2>
<ul id="items">
<?php if(count($this->NewsData)>0){
foreach ($NewsData as $Ndata){
?>
<li>
<div class="col-md-6 news col-xs-12">
<div class="col-md-3 col-sm-2 col-xs-2 img">
  <?php if(!empty($Ndata->image)) $path="images/new-big.jpg";
  else $path="images/news-thumb.jpg";
  ?>
<img src="<?php echo $this->basePath($path) ?>" class="img-responsive" />
</div>
<div class="col-md-9 col-sm-10 col-xs-10 content">
<h4><?php echo $Ndata->title; ?></h4>
<p><?php echo $Ndata->description; ?></p>
<p><a href="<?php echo $this->basePath()?>/news/view">Read Full Story >></a></p>
</div>
</div>
</li>
<?php 
}
}
else{ ?> 
				<span style="text-align:center;font-weight:bold;font-size:16px;color:cornflowerblue;">No Data available</span>
			<?php } ?>
 </ul>