                    <div class="table-responsive">
                      <table id="dynamic-table" class="table table-striped table-bordered table-hover">
                    <thead>
                      <tr>
                           <th><input type="checkbox" value="" id="checkAll" onclick="checkall(this.id)" > </th>
                        <th>S. No.</th>
                        <th>Starsign Name</th>
                        <th class="hidden-480">Modified Date</th>
                        <th class="hidden-480">Created Date</th>
                        <th class="hidden-480">Status</th>
                        <th class="hidden-480">Modified By</th>
                        <th><b>Actions</b></th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php 
					  $i=1;
                       if (count($results) > 0) {                   
                      foreach ($results as $starsign) {
                      
                      ?>
                      <tr>
                        <td><input type="checkbox" value="<?=$starsign->id?>" class="checkme" name="checkme[]"> </td> 
                       <td><?= $i ?></td>  
                        <td><?= $starsign->starSignName?></td>                       
                        <td class="hidden-480"><?=$starsign->modifiedDate?></td>
                        <td class="hidden-480"><?=$starsign->createdDate?></td>
                        
                        <td class="hidden-480">
						<!--<?php echo ($starsign->isActive==1)? 'Active': '<span class="label label-sm label-warning">In-Active</span>'; ?>-->
                        <?php $status = ($starsign->isActive==1)? 'Active': 'In-Active';
                        $statuscolor = ($starsign->isActive==1)? 'activestatus': 'de-activestatus';
                         ?>
                          <div name="ChangeStatus" id="changestatus<?=$i;?>" onclick="changestatusquick(<?=$starsign->id?>,<?= ($starsign->isActive==0)?0:1; ?>,'<?php echo $this->
                                                                url('admin/starsign', array('action'=>
                                                                    'changestatus')); ?>',changstatusresult);" class="<?=$statuscolor?>">
                        </div>
                        </td>
                        <td class="hidden-480"><?php echo ($starsign->modifiedBy==1)? 'Admin': 'NotByAdmin'; ?></td>
                        <td><div class="hidden-sm hidden-xs action-buttons"> 
                        <!--<a class="blue" href="<?php echo $this->url('admin',array('controller'=>'starsign','action'=>'view','id'=>$starsign->id)); ?>">
                         <i class="ace-icon fa fa-search-plus bigger-130"></i> </a> -->
                         <a class="blue" style="cursor:pointer;" data-toggle="modal" data-target="#myModal"  
                                                   tar="indview<?= $i ?>"> <i onclick="findRowDataByStarsignId('<?php echo $this->url
                                                           ('admin/starsign', array('action'=>'viewById','id'=>$starsign->id)); ?>', 
                                                                       viewRowDataById);" class="ace-icon fa fa-search-plus bigger-130">
                                                    </i> </a>
                         
                         <a class="green" href="javascript:void(0);" onclick="editbox(<?= 
                                                   $starsign->id ?>, '<?php echo $this->url('admin/starsign', array('action' => 
                                                       'edit', 'id' => $starsign->id));
                                        ?>', editformresp);" > <i class="ace-icon fa fa-pencil bigger-130"></i> </a> 
                          <a class="red" href="<?php echo $this->url('admin/starsign',array('action'=>'delete','id'=>
                              $starsign->id)); ?>" onclick="return confirm('are you sure you want to delete');"> <i class="ace-icon fa 
                                                                                             fa-trash-o bigger-130"></i> </a> </div>
                          </td>
                      </tr>
                      
                      
                      
                      
                      <?php 
                      $i++;
                    }
                  } else
                            echo" <tr>
                         
                       <td colspan=9><center><h2>No data available</h2></center></td></tr>";
                      ?>
                    </tbody>
                  </table>
                      
                      
                      
                      
                    </div>
                

            
             