<ul>
   <li class='has-sub'><a href='#'><span>Master 1</span></a>
   
   
   <ul>
         <li class='has-sub'><a href='#'><span>Static Pages</span></a>
            <ul>
               <li><a href='<?php echo $this->basePath()."/admin/pages";?>'><span>Manage Static Pages</span></a></li>
               <li class='last'><a href='<?php
               echo $this->url('admin', array('controller' => 'pages', 'action' => 'add'));
                ?>'><span>Add Static Pages</span></a></li>
            </ul>
         </li>
      </ul>
   </li>
   
   <li class='active has-sub'><a href='#'><span>Region</span></a>
      <ul>
         <li class='has-sub'><a href='<?php echo $this->url('admin/country'); ?>'><span>Country</span></a>
            <ul>
               <li><a href='<?php echo $this->url('admin/country'); ?>'><span>Manage Country</span></a></li>
               <li class='last'><a href='<?php
               echo $this->url('admin/country', array('action' => 'add'));
                ?>'><span>Add Country</span></a></li>
            </ul>
         </li>
         <li class='has-sub'><a href='<?php echo $this->url('admin/state'); ?>'><span>State</span></a>
            <ul>
               <li><a href='<?php echo $this->url('admin/state'); ?>'><span>Manage State</span></a></li>
               <li class='last'><a href='<?php
               echo $this->url('admin/state', array('action' => 'add'));
                ?>'><span>Add State</span></a></li>
            </ul>
         </li>
         
         <li class='has-sub'><a href='<?php echo $this->url('admin/city', array('controller' => 'city', 'action' => 'index'));?>'><span>City</span></a>
            <ul>
               <li><a href='<?php echo $this->url('admin/city', array('controller' => 'city', 'action' => 'index'));?>'><span>Manage City</span></a></li>
               <li class='last'><a href='<?php
               echo $this->url('admin/city', array('controller' => 'city', 'action' => 'add'));
                ?>'><span>Add City</span></a></li>
            </ul>
         </li>
         
         
         
          <li class='has-sub'><a href='#'><span>Native Place</span></a>
            <ul>
               <li><a href='#'><span>Manage Country</span></a></li>
               <li class='last'><a href='#'><span>Add Country</span></a></li>
            </ul>
         </li>
         
         
         <li class='has-sub'><a href='#'><span>Regional</span></a>
            <ul>
               <li><a href='#'><span>Manage Religional</span></a></li>
               <li class='last'><a href='#'><span>Add Religional</span></a></li>
            </ul>
         </li>
         
         
         
          <li class='has-sub'><a href='#'><span>Regional Branches</span></a>
            <ul>
               <li><a href='#'><span>Rohini</span></a></li>
               <li class='last'><a href='#'><span>Transhindon</span></a></li>
                <li class='last'><a href='#'><span>Palam</span></a></li>
            </ul>
         </li>
         
         
         
         
         
         
         
      </ul>
   </li>
   <li   class='has-sub'><a href='#'><span>Matrimonial Master Enteries</span></a>
   
   <ul>
         <li class='has-sub'><a href='<?php
               echo $this->url('admin/religion', array('controller' => 'religion', 'action' => 'index'));
                ?>'><span>Religion</span></a>
            <ul>
               <li><a href='<?php
               echo $this->url('admin/religion', array('controller' => 'religion', 'action' => 'index'));
                ?>'><span>Manage Religion</span></a></li>
               <li class='last'><a href='<?php
               echo $this->url('admin/religion', array('controller' => 'religion', 'action' => 'add'));
                ?>'><span>Add Religion</span></a></li>
            </ul>
         </li>
         <li class='has-sub'><a href='<?php
               echo $this->url('admin/gothra', array('controller' => 'gothra', 'action' => 'index'));
                ?>'><span>Gotra</span></a>
            <ul>
               <li><a href='<?php
               echo $this->url('admin/gothra', array('controller' => 'gothra', 'action' => 'index'));
                ?>'><span>Manage Gotra</span></a></li>
               <li class='last'><a href='<?php
               echo $this->url('admin/gothra', array('controller' => 'gothra', 'action' => 'add'));
                ?>'><span>Add Gotra</span></a></li>
            </ul>
         </li>
         
         <li class='has-sub'><a href='#'><span>Height</span></a>
            <ul>
               <li><a href='#'><span>Manage Height</span></a></li>
               <li class='last'><a href='#'><span>Add Height</span></a></li>
            </ul>
         </li>
         
         
         
          <li class='has-sub'><a href='#'><span>Weight</span></a>
            <ul>
               <li><a href='#'><span>Manage Weight</span></a></li>
               <li class='last'><a href='#'><span>Add Weight</span></a></li>
            </ul>
         </li>
         
         
         <li class='has-sub'><a href='<?php
               echo $this->url('admin/starsign', array('controller' => 'starsign', 'action' => 'index'));
                ?>'><span>Star Sign</span></a>
            <ul>
               <li><a href='<?php
               echo $this->url('admin/starsign', array('controller' => 'starsign', 'action' => 'index'));
                ?>'><span>Manage Star Sign</span></a></li>
               <li class='last'><a href='<?php
               echo $this->url('admin/starsign', array('controller' => 'starsign', 'action' => 'add'));
                ?>'><span>Add Star Sign</span></a></li>
            </ul>
         </li>
         
         
         
          <li class='has-sub'><a href='<?php
               echo $this->url('admin/zodiacsign', array('controller' => 'zodiacsign', 'action' => 'index'));
                ?>'><span>Zodiac Sign Rassi
</span></a>
            <ul>
               <li><a href='<?php
               echo $this->url('admin/zodiacsign', array('controller' => 'zodiacsign', 'action' => 'index'));
                ?>'><span>Manage Zodiac Sign Rassi</span></a></li>
               <!-- <li class='last'><a href='<?php
               echo $this->url('admin/zodiacsign', array('controller' => 'zodiacsign', 'action' => 'add'));
                ?>'><span>Add Zodiac Sign Rassi</span></a></li> -->
            </ul>
         </li>
         
         
         
         
         
         
         
      </ul>
   
   
   
   </li>

   
   <li  class='has-sub'><a href='#'><span>Education Filed</span></a>
   
   
   
   <ul>
         <li class='has-sub'><a href='<?php echo $this->url('admin/education', array('action' => 'index'));?>'><span>Education</span></a>
            <ul>
               <li><a href='<?php echo $this->url('admin/education', array('action' => 'index'));?>'><span>Manage Education</span></a></li>
               <li class='last'><a href='<?php echo $this->url('admin/education', array('action' => 'add')); ?>'><span>Add Education</span></a></li>
               <li class='last'><a href='<?php echo $this->url('admin/education', array('action' => 'manageEducationLevel'));?>'><span> Manage Education Level</span></a></li>
               <li class='last'><a href='<?php echo $this->url('admin/education', array('action' => 'addEducationLevel'));?>'><span>Add Education Level</span></a></li>
            </ul>
         </li>
         <li class='has-sub'><a href='<?php echo $this->url('admin/profession', array('controller' => 'profession', 'action' => 'index'));?>'><span>Profession</span></a>
            <ul>
               <li><a href='<?php
               echo $this->url('admin/profession', array('controller' => 'profession', 'action' => 'index'));
                ?>'><span>Manage Professions </span></a></li>
               <li class='last'><a href='<?php
               echo $this->url('admin/profession', array('action' => 'addProfession'));
                ?>'><span>Add Profession</span></a></li>
            </ul>
         </li>
         
         <li class='has-sub'><a href='<?php
               echo $this->url('admin/designation', array('controller' => 'designation', 'action' => 'index'));
                ?>'><span>Designiation</span></a>
            <ul>
               <li><a href='<?php
               echo $this->url('admin/designation', array('controller' => 'designation', 'action' => 'index'));
                ?>'><span>Manage Designiation</span></a></li>
               <li class='last'><a href='<?php
               echo $this->url('admin/designation', array('action' => 'addDesignation'));
                ?>'><span>Add Designiation</span></a></li>
            </ul>
         </li>
         
         
         
      </ul>
   
   
   
   
   </li>
      <li class='last has-sub'><a href='#'><span>General Member</span></a>
      
      
      <ul>
         <li class='has-sub'><a href='#'><span>Child</span></a>
            <ul>
               <li><a href='#'><span>Manage Child</span></a></li>
               <li class='last'><a href='#'><span>Add Child</span></a></li>
              
            </ul>
         </li>
         <li class='has-sub'><a href='#'><span>Adult</span></a>
            <ul>
               <li><a href='#'><span>Manage Adult</span></a></li>
               <li class='last'><a href='#'><span>Add Adult</span></a></li>
            </ul>
         </li>
         
         <li class='has-sub'><a href='#'><span>Senior Citizen</span></a>
            <ul>
               <li><a href='#'><span>Manage Senior Citizen<</span></a></li>
               <li class='last'><a href='#'><span>Add Senior Citizen<</span></a></li>
            </ul>
         </li>
         
         
         <li class='has-sub'><a href='#'><span>Committee Member</span></a>
            <ul>
               <li><a href='#'><span>Manage Committee Member</span></a></li>
               <li class='last'><a href='<?php
               echo $this->url('admin/master', array('controller' => 'master', 'action' => 'addcomm', 'id' => 0));
                ?>'><span>Add Committee Member</span></a></li>
            </ul>
         </li>
         
         
         <li class='has-sub'><a href='#'><span>Vice President</span></a>
            <ul>
               <li><a href='#'><span>Manage Vice President</span></a></li>
               <li class='last'><a href='#'><span>Add Vice President</span></a></li>
            </ul>
         </li>
         
         
         
      </ul>
      
      
      
      
      
      
      
      
      
      
      
      </li>
      
      
      <li class='last has-sub'><a href='#'><span>Matrimoni Member</span></a>
      
      
      
      <ul>
         <li class='has-sub'><a href='#'><span>Married</span></a>
            <ul>
               <li><a href='#'><span>Manage Married</span></a></li>
               <li class='last'><a href='#'><span>Add Married</span></a></li>
              
            </ul>
         </li>
         <li class='has-sub'><a href='#'><span>Unmarried</span></a>
            <ul>
               <li><a href='#'><span>Manage Unmarried</span></a></li>
               <li class='last'><a href='#'><span>Add Unmarried</span></a></li>
            </ul>
         </li>
         
         <li class='has-sub'><a href='#'><span>Widow</span></a>
            <ul>
               <li><a href='#'><span>Manage Widow</span></a></li>
               <li class='last'><a href='#'><span>Add Widow</span></a></li>
            </ul>
         </li>
         
         
         <li class='has-sub'><a href='#'><span>Divorci</span></a>
            <ul>
               <li><a href='#'><span>Manage Divorci</span></a></li>
               <li class='last'><a href='#'><span>Add Divorci</span></a></li>
            </ul>
         </li>
         
         
         
      </ul>
      
      
      
      
      
      
      </li>
   
   
</ul>