<div class="col-sm-3 col-sm-3-new width20per">
<?php echo $this->partial('layout/sidebar-membership') ?>
</div>

<div class="col-sm-9 width80per">

<div class="col-sm-3 profile-img col-xs-4">
<img src="<?php echo $this->basePath('images/community1.png') ?>" width="78" class="img-responsive"  />
<p>Membership ID 17860</p>

</div>
<div class="col-sm-6 col-xs-8">
<div class="row">
<div class="col-xs-5">Name</div>
<div class="col-xs-7">धर्मपाल रुस्तगी</div>

<div class="col-xs-5">Father’s. Name</div>
<div class="col-xs-7">धर्मपाल रुस्तगी</div>

<div class="col-xs-5">Address</div>
<div class="col-xs-7">54-D, Bandra Mumbai 102453</div>

<div class="col-xs-5">Contact Number</div>
<div class="col-xs-7">000000000</div>

<div class="col-xs-5">Profession</div>
<div class="col-xs-7">Profession</div>

<div class="col-xs-5">Post</div>
<div class="col-xs-7">Chief Patron</div>

<div class="col-xs-5">Email ID</div>
<div class="col-xs-7">parveenrustagi.pr@gmail.com</div>
</div>
</div>
<div class="col-sm-12">
<p>Connected  9 Months ago</p>
</div>

<div class="clearfix"></div>
<ul class="nav nav-pills">
    <li class="active"><a data-toggle="pill" href="#about">About</a></li>
    	<li><a data-toggle="pill" href="#personal-info">Personal Info</a></li>
    <li><a data-toggle="pill" href="#education">Education</a></li>
    <li><a data-toggle="pill" href="#profession">Profession</a></li>
    <li><a data-toggle="pill" href="#family-details">Family Details</a></li>
      <li><a data-toggle="pill" href="#marital-detail">Marital Detail</a></li> 
    <li><a data-toggle="pill" href="#photo-gallery">Gallery</a></li> 
  </ul>
  
  
  <div class="tab-content">
    <div id="about" class="tab-pane fade in active">
      <p>Lorem ipsum dolor sit amet, integre diceret facilis ea nec, pri postea commodo ceteros et. Moderatius reprehendunt nam cu, vel dicant viderer an. Vidit solet definitionem no pro, te pro salutandi philosophia complectitur, pri suavitate constituto adversarium eu. Est etiam fuisset et, at qui suscipit facilisi.</p> 
      
      <p>Lorem ipsum dolor sit amet, integre diceret facilis ea nec, pri postea commodo ceteros et. Moderatius reprehendunt nam cu, vel dicant viderer an. Vidit solet definitionem no pro, te pro salutandi philosophia complectitur, pri suavitate constituto adversarium eu. Est etiam fuisset et, at qui suscipit facilisi.</p> 
      
      <p>Lorem ipsum dolor sit amet, integre diceret facilis ea nec, pri postea commodo ceteros et. Moderatius reprehendunt nam cu, vel dicant viderer an. Vidit solet definitionem no pro, te pro salutandi philosophia complectitur, pri suavitate constituto adversarium eu. Est etiam fuisset et, at qui suscipit facilisi.</p> 
      
      <p>Lorem ipsum dolor sit amet, integre diceret facilis ea nec, pri postea commodo ceteros et. Moderatius reprehendunt nam cu, vel dicant viderer an. Vidit solet definitionem no pro, te pro salutandi philosophia complectitur, pri suavitate constituto adversarium eu. Est etiam fuisset et, at qui suscipit facilisi.</p>     
      
    </div>
    
    <div id="personal-info" class="tab-pane fade">
			<div class="row divrow">
             <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Full Name');?></span>
				<div class="col-sm-3 nwclas">धर्मपाल रुस्तगी</div>
                </div>
                 <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Gender') ?></span>
				<div class="col-sm-3 nwclas">Male</div>
                </div>
			</div>
			<div class="row divrow">
             <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Date of Birth');?></span>
				<div class="col-sm-3 nwclas">01-05-1950</div>
                </div>
                 <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Age') ?></span>
				<div class="col-sm-3 nwclas">90 Year</div>
                </div>
			</div>
            
            <div class="row divrow">
             <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Height.');?></span>
				<div class="col-sm-3 nwclas">5ft 6in </div>
                </div>
                 <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Body Type') ?></span>
				<div class="col-sm-3 nwclas">Average</div>
                </div>
			</div>
            
             <div class="row divrow">
             <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Skin Tone.');?></span>
				<div class="col-sm-3 nwclas">Fair</div>
                </div>
                 <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Any Disability?') ?></span>
				<div class="col-sm-3 nwclas">No</div>
                </div>
			</div>
            
			<div class="row divrow">
             <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Phone No.');?></span>
				<div class="col-sm-3 nwclas">0000000000</div>
                </div>
                 <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Alt. Mob. No.') ?></span>
				<div class="col-sm-3 nwclas">0000000000</div>
                </div>
			</div>
			<div class="row divrow">
             <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Address Line 1');?></span>
				<div class="col-sm-3 nwclas">1029, karolbag Delhi</div>
                </div>
                 <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Address Line 2') ?></span>
				<div class="col-sm-3 nwclas">New Delhi></div>
                </div>
			</div>
			<div class="row divrow">
             <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Country');?></span>
				<div class="col-sm-3 nwclas">India</div>
                </div>
                 <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('State') ?></span>
				<div class="col-sm-3 nwclas">Delhi</div>
                </div>
			</div>
			<div class="row divrow">
             <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('City');?></span>
				<div class="col-sm-3 nwclas">New Delhi</div>
                </div>
                 <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Zip/Pin Code') ?></span>
				<div class="col-sm-3 nwclas">110005</div>
                </div>
			</div>
			<div class="row divrow">
             <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Native Palace');?></span>
				<div class="col-sm-3 nwclas">Delhi</div>
                </div>				
			</div>
		</div>
    
    <div id="education" class="tab-pane fade">
		   <div class="row divrow">
           <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Education Level');?></span>
				<div class="col-sm-3 nwclas">M A</div>
                </div>
                <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Education Field') ?></span>
				<div class="col-sm-3 nwclas">Arts</div>
                </div>
			</div>
			<div class="row">
            <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Specialization');?></span>
				<div class="col-sm-3 nwclas">Arts</div>
                </div>
                <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Employment Status');?></span>
				<div class="col-sm-3 nwclas">Bussiness </div>
                </div>
			</div>	
            
            <div class="row">
              <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Profession');?></span>
				<div class="col-sm-3 nwclas">Business</div>
                </div>
			</div>
            	
		</div>
    <div id="profession" class="tab-pane fade">
		    <div class="row">
             <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Working Info');?></span>
				<div class="col-sm-3 nwclas">Regency</div>
                </div>
                 <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Office Name') ?></span>
				<div class="col-sm-3 nwclas">Hello42</div>
                </div>
			</div>
            
            <div class="row">
             <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Designation');?></span>
				<div class="col-sm-3 nwclas"> HR Management</div>
                </div>
                 <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Working With') ?></span>
				<div class="col-sm-3 nwclas">Regency</div>
                </div>
			</div>
			<div class="row">
              <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Specialization') ?></span>
				<div class="col-sm-3 nwclas">HR </div>
                </div>
             
             
                 <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Office Address') ?></span>
				<div class="col-sm-3 nwclas">Delhi Karolbag</div>
                </div>
                
                
			</div>
			<div class="row">
            <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Office Country');?></span>
				<div class="col-sm-3 nwclas">India</div>
                </div>
             
                 <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Office State') ?></span>
				<div class="col-sm-3 nwclas">Delhi</div>
                </div>
                
                
                
			</div>
			<div class="row">
            
            <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Office City');?></span>
				<div class="col-sm-3 nwclas">New Delhi</div>
                </div>
             
                 <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Office Zip/Pin') ?></span>
				<div class="col-sm-3 nwclas">110005</div>
                </div>
                
                
			</div>
			<div class="row">
            
            <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Office Phone');?></span>
				<div class="col-sm-3 nwclas">0000000000</div>
                </div>
             <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Office Email');?></span>
				<div class="col-sm-3 nwclas">parveenrustagi.pr@gmail.com</div>
                </div>
                 
			</div>
			
			<div class="row">
            <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Office Website') ?></span>
				<div class="col-sm-3 nwclas">www.</div>
                </div>
            
             <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Annual Income');?></span>
				<div class="col-sm-3 nwclas">20000000</div>	
                </div>			
			</div>
		</div>
        
    <div id="family-details" class="tab-pane fade">
        
        <div class="row">
             <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Name of Spouse');?></span>
				<div class="col-sm-3 nwclas"> </div>
                </div>
                 <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Spouse Status');?></span>
				<div class="col-sm-3 nwclas"> </div>
                </div>
			</div>
            
            <div class="row">
             <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Spouse DOB');?></span>
				<div class="col-sm-3 nwclas"> </div>
                </div>
                 <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Spouse Photo');?></span>
				<div class="col-sm-3 nwclas"> </div>
                </div>
			</div>
            
            
            <div class="row">
             <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Name of Kid');?></span>
				<div class="col-sm-3 nwclas"> </div>
                </div>
                 <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Kid Status');?></span>
				<div class="col-sm-3 nwclas"> </div>
                </div>
			</div>
            
            
             <div class="row">
             <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Kid DOB');?></span>
				<div class="col-sm-3 nwclas"> </div>
                </div>
                 <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Kid Photo');?></span>
				<div class="col-sm-3 nwclas"> </div>
                </div>
			</div>
                
		   <div class="row">
            <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Father Name');?></span>
				<div class="col-sm-3 nwclas"> </div>
                </div>
                 <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Father Status') ?></span>
				<div class="col-sm-3 nwclas"> </div>
                </div>
			</div>
            
            
			<div class="row">
             <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Father DOB');?></span>
				<div class="col-sm-3 nwclas"> </div>
                </div>
                 <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Father Photo') ?></span>
				<div class="col-sm-3 nwclas"> </div>
                </div>
			</div>
			<div class="row">
             <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Mother Name');?></span>
				<div class="col-sm-3 nwclas"> </div>
                </div>
                 <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Mother Status') ?></span>
				<div class="col-sm-3 nwclas"> </div>
                </div>
			</div>
			<div class="row">
             <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Mother DOB');?></span>
				<div class="col-sm-3 nwclas"> </div>
                </div>
                 <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Mother Photo') ?></span>
				<div class="col-sm-3 nwclas"> </div>
                </div>
			</div>
            
             <div class="row">
             <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Name of Brother');?></span>
				<div class="col-sm-3 nwclas"> </div>
                </div>
                 <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Brother Status');?></span>
				<div class="col-sm-3 nwclas"> </div>
                </div>
			</div>
                        
             <div class="row">
             <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Brother DOB');?></span>
				<div class="col-sm-3 nwclas"> </div>
                </div>
                 <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Brother Photo');?></span>
				<div class="col-sm-3 nwclas"> </div>
                </div>
			</div>
            
             
             <div class="row">
             <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Name of Sister');?></span>
				<div class="col-sm-3 nwclas"></div>
                </div>
                 <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Sister Status');?></span>
				<div class="col-sm-3 nwclas"></div>
                </div>
			</div>
                        
             <div class="row">
             <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Sister DOB');?></span>
				<div class="col-sm-3 nwclas"></div>
                </div>
                 <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Sister Photo');?></span>
				<div class="col-sm-3 nwclas"></div>
                </div>
			</div>
            
            
			<div class="row">
             <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Grand Father Name');?></span>
				<div class="col-sm-3 nwclas"></div>
                </div>
                 <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Grand Father Status') ?></span>
				<div class="col-sm-3 nwclas"></div>
                </div>
			</div>
			<div class="row">
             <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Grand Mother Name');?></span>
				<div class="col-sm-3 nwclas"></div>
                </div>
                 <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Grand Mother Status') ?></span>
				<div class="col-sm-3 nwclas"></div>
                </div>
			</div>
			
		</div>
        
    <div id="marital-detail" class="tab-pane fade">
		    <div class="row">
             <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Marital Status');?></span>
				<div class="col-sm-3 nwclas"> </div>
                </div>
                
                <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Caste') ?></span>
				<div class="col-sm-3 nwclas"> </div>
                </div>
                 
			</div>
			<div class="row">
             
                 <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Religion');?></span>
				<div class="col-sm-3 nwclas"> </div>
                </div>
                
                <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Other Caste') ?></span>
				<div class="col-sm-3 nwclas"> </div>
                </div>
                				
			</div>
            
             <div class="row">
            
            <div class="divmatrimon">
				<span class="col-sm-2n"><?= $this->translate('Blood Group') ?></span>
				<div class="col-sm-3 nwclas"> </div>
                </div>
            
            	</div>		
		</div>
        
        <div id="photo-gallery" class="tab-pane fade">
		   <div class="gallery">
  <div class="col-xs-4">
  <div class="col-xs-12"><a href="<?php echo $this->basePath('gallery/large/gallery.jpg') ?>" title="" data-gallery=""><img src="<?php echo $this->basePath('gallery/thumb/gallery.jpg') ?>" class="img-responsive" />
  <div class="img-title"><span style="float:left;">Image Name</span><span style="float:right;">Delhi</span></div>
   
  </a>
    </div>
   <div class="img-title"><span style="float:left;">01-01-2016</span><span style="float:right;">05:20 pm</span></div>
  </div>
  
  <div class="col-xs-4">
  <div class="col-xs-12"><a href="<?php echo $this->basePath('gallery/large/gallery.jpg') ?>" title="" data-gallery=""><img src="<?php echo $this->basePath('gallery/thumb/gallery.jpg') ?>" class="img-responsive" />
  <div class="img-title"><span style="float:left;">Image Name</span><span style="float:right;">Delhi</span></div>
   
  </a>
    </div>
   <div class="img-title"><span style="float:left;">01-01-2016</span><span style="float:right;">05:20 pm</span></div>
  </div>
  
  <div class="col-xs-4">
  <div class="col-xs-12"><a href="<?php echo $this->basePath('gallery/large/gallery.jpg') ?>" title="" data-gallery=""><img src="<?php echo $this->basePath('gallery/thumb/gallery.jpg') ?>" class="img-responsive" />
  <div class="img-title"><span style="float:left;">Image Name</span><span style="float:right;">Delhi</span></div>
   
  </a>
    </div>
   <div class="img-title"><span style="float:left;">01-01-2016</span><span style="float:right;">05:20 pm</span></div>
  </div>
  
  <div class="col-xs-4">
  <div class="col-xs-12"><a href="<?php echo $this->basePath('gallery/large/gallery.jpg') ?>" title="" data-gallery=""><img src="<?php echo $this->basePath('gallery/thumb/gallery.jpg') ?>" class="img-responsive" />
  <div class="img-title"><span style="float:left;">Image Name</span><span style="float:right;">Delhi</span></div>
   
  </a>
    </div>
   <div class="img-title"><span style="float:left;">01-01-2016</span><span style="float:right;">05:20 pm</span></div>
  </div>
  
  <div class="col-xs-4">
  <div class="col-xs-12"><a href="<?php echo $this->basePath('gallery/large/gallery.jpg') ?>" title="" data-gallery=""><img src="<?php echo $this->basePath('gallery/thumb/gallery.jpg') ?>" class="img-responsive" />
  <div class="img-title"><span style="float:left;">Image Name</span><span style="float:right;">Delhi</span></div>
   
  </a>
    </div>
   <div class="img-title"><span style="float:left;">01-01-2016</span><span style="float:right;">05:20 pm</span></div>
  </div>
  
  <div class="col-xs-4">
  <div class="col-xs-12"><a href="<?php echo $this->basePath('gallery/large/gallery.jpg') ?>" title="" data-gallery=""><img src="<?php echo $this->basePath('gallery/thumb/gallery.jpg') ?>" class="img-responsive" />
  <div class="img-title"><span style="float:left;">Image Name</span><span style="float:right;">Delhi</span></div>
   
  </a>
    </div>
   <div class="img-title"><span style="float:left;">01-01-2016</span><span style="float:right;">05:20 pm</span></div>
  </div>
  
   
  <div class="clearfix"></div>
  </div>			
		</div>
  </div>
</div>