<div class="commen-list grid-view">
    <ul id="items">
        <?php if (count($this->GroomData) > 0) {
            foreach ($GroomData as $GrData) {
                ?>
                <li class="li_listmember">
                    <div class="col-xs-2">
                        <div class="profile-pic"><img src="<?php
                            if ($GrData->profile_photo != '') {
                                echo $this->basePath() . $GrData->profile_photo;
                            } else {
                                echo $this->basePath() . '/img/default_user.png';
                            }
                            ?>"/></div>
                        <h3 style="height:30px;"><?php echo $GrData->name_title_user . " " . $GrData->full_name; ?></h3>
                        <h4><?= $GrData->profession ?></h4>
                        <a href="<?php echo $this->basePath() ?>/membership/profile-view?groom_id=<?php echo $GrData->uid ?>" class="btn btn-default">more info</a>
                    </div>
                    <div class="col-xs-10">
                        <div class="col-xs-8">
                            <div class="col-xs-2 col-xs-2-member">Name</div>

                            <div class="col-xs-3 col-xs-3-member"><?= $GrData->name_title_user . "  " . $GrData->full_name ?></div>
                            <div class="col-xs-2 col-xs-2-member">F. Name</div>

                            <div class="col-xs-3 col-xs-3-member"><?= $GrData->name_title_father . " " . $GrData->father_name ?> </div>
                            <div class="col-xs-2 col-xs-2-member">Occupation</div>

                            <div class="col-xs-3 col-xs-3-member"><?= $GrData->profession ?></div>
                            <div class="col-xs-2 col-xs-2-member">Address</div>
                            <div class="col-xs-3 col-xs-3-member"><?= $GrData->address . " " . $GrData->city_name ?></div>

                            <div class="col-xs-2 col-xs-2-member">Branch</div>
                            <div class="col-xs-3 col-xs-3-member"><?= $GrData->branch_name ?></div> 
                        </div>

                        <div class="clearfix"></div>
                        <div class="col-xs-8" style="padding:0 0;">Short Description : President ( 2012 - Till )</div>
                        <div class="col-xs-4" style="padding:0 0;">
                            <div>
                                <span>Follow : -</span>
                                <ul class="follow">
                                    <li style="width:32%; min-height:auto !important;"><a href="#" class="facebook"></a></li>
                                    <li style="width:32%; min-height:auto !important;"><a href="#" class="twitter"></a></li>
                                    <li style="width:32%; min-height:auto !important;"><a href="#" class="gplus"></a></li>
                                    <li style="width:32%; min-height:auto !important;"><a href="#" class="linkedin"></a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                        <div class="col-xs-12" style="display:none;">
                            <p><?= $GrData->about_yourself_partner_family ?></p>
                        </div>
                    </div>
                </li>
            <?php }
        } else {
            ?> 
            <span style="text-align:center;font-weight:bold;font-size:12px; color:cornflowerblue;">No Data available</span>
<?php } ?>
    </ul>
</div>

