<style>
    .li_listmember_wid{
        width:100% !important;
    }

</style>


<div class="col-sm-3 col-sm-3-new width20per">
    <?php echo $this->partial('layout/sidebar-membership') ?>
    <?php //print_r($filters_data);
// echo MembershipController::membercount(); 
    ?>
</div>
<div class="showerrorbox">

</div>
<div class="col-sm-9 width80per">
    <div class="row">
        <div class="col-xs-9">
            <ul class="view-menu">
                <li>Sort By :</li>
                <li><a href="javascript:void(0);" onclick="sortmembers(this, 'Latest', '<?php echo $this->url('membership', array('action'=>'sortmembers')); ?>', sortmembersresults)" >New Joining</a></li>
                <li><a href="javascript:void(0);" onclick="sortmembers(this, 'IsExecutive', '<?php echo $this->url('membership', array('action'=>'sortmembers')); ?>', sortmembersresults)">Executive Communinty</a></li>
                <li><a href="javascript:void(0);" onclick="sortmembers(this, 'age', '<?php echo $this->url('membership', array('action'=>'sortmembers')); ?>', sortmembersresults)">Senior Citizen</a></li>             
            </ul>
        </div>
        <div class="col-xs-3">
            <ul class="prof-view pull-right">
                <li><a href="#" id="list"><span class="glyphicon glyphicon-th-list"></span><span class="sr-only">List View</span></a></li>
                <li><a href="#" id="grid"><span class="glyphicon glyphicon-th"></span><span class="sr-only">Grid View</span></a></li>
            </ul>
        </div>
    </div>
    <div class="clearfix"></div>
    <!-- <div class="filters_loader_box">
            <div id="filters_data_loader"><h1>Loading...</h1></div>
    </div> -->
    <div id="profile">

        <div class="commen-list grid-view">
            <ul  id="items">
                <li>
                    <div class="col-xs-2"></div>
                    <div class="col-xs-10">
                        <div class="col-xs-2">Name</div>
                        <div class="col-xs-3">F. Name</div>
                        <div class="col-xs-3">Occupation</div>
                        <div class="col-xs-2">Area</div>
                        <div class="col-xs-2">Branch</div>
                    </div>
                </li>
                <?php if (count($this->GroomData) > 0) {
                    foreach ($GroomData as $GrData) {
                        ?>
                        <li class="li_listmember">
                            <div class="col-xs-2">
                                <div class="profile-pic"><img src="<?php
                                    if ($GrData->profile_photo != '') {
                                        echo $this->basePath() . $GrData->profile_photo;
                                    } else {
                                        echo $this->basePath() . '/img/default_user.png';
                                    }
                                    ?>" /></div>
                                <h3 style="height:30px;"><?php echo $GrData->name_title_user . " " . $GrData->full_name; ?></h3>
                                <h4><?= $GrData->profession ?></h4>
                                <a href="<?php echo $this->basePath() ?>/membership/profile-view?groom_id=<?php echo $GrData->uid ?>" class="btn btn-default">more info</a>
                            </div>
                            <div class="col-xs-10">
                                <div class="col-xs-8">
                                    <div class="col-xs-2 col-xs-2-member">Name</div>

                                    <div class="col-xs-3 col-xs-3-member"><?= $GrData->name_title_user . " " . $GrData->full_name ?></div>
                                    <div class="col-xs-2 col-xs-2-member">F. Name</div>

                                    <div class="col-xs-3 col-xs-3-member"><?= $GrData->name_title_father . " " . $GrData->father_name ?> </div>
                                    <div class="col-xs-2 col-xs-2-member">Occupation</div>

                                    <div class="col-xs-3 col-xs-3-member"><?= $GrData->profession ?></div>
                                    <div class="col-xs-2 col-xs-2-member">Address</div>
                                    <div class="col-xs-3 col-xs-3-member"><?= $GrData->address . " " . $GrData->city_name ?></div>

                                    <div class="col-xs-2 col-xs-2-member">Branch</div>
                                    <div class="col-xs-3 col-xs-3-member"><?= $GrData->branch_name ?></div> 
                                </div>
                                <div class="clearfix"></div>
                                <div class="col-xs-8" style="padding:0 0;">Short Description : President ( 2012 - Till )</div>
                                <div class="col-xs-4" style="padding:0 0;">
                                    <div style="">
                                        <span>Follow : -</span>
                                        <ul class="follow">
                                            <li style="width:32%; min-height:auto !important;"><a href="#" class="facebook"></a></li>
                                            <li style="width:32%; min-height:auto !important;"><a href="#" class="twitter"></a></li>
                                            <li style="width:32%; min-height:auto !important;"><a href="#" class="gplus"></a></li>
                                            <li style="width:32%; min-height:auto !important;"><a href="#" class="linkedin"></a></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="clearfix"></div>
                                <div class="col-xs-12" style="display:none;">
                                    <p><?= $GrData->about_yourself_partner_family ?></p>
                                </div>
                            </div>
                        </li>


                    <?php }
                } else {
                    ?> 
                    <span style="text-align:center;font-weight:bold;font-size:12px;color:cornflowerblue;">No Data available</span>
<?php } ?>


                <!--/* <li>
                <div class="col-xs-2">
                <div class="profile-pic"><img src="<?php echo $this->basePath('images/profile-pic.png') ?>" /></div>
                <h3>Sunny Deo</h3>
                <h4>Actor</h4>
                <a href="<?php echo $this->basePath() ?>/membership/profile-view" class="btn btn-default">more info</a>
                </div>
                <div class="col-xs-10">
                <div class="col-xs-2">S. Deo</div>
                <div class="col-xs-3">Rajkumar </div>
                <div class="col-xs-3">Business Man</div>
                <div class="col-xs-2">Gk</div>
                <div class="col-xs-2">Rohini</div>
                <div class="clearfix"></div>
                <div class="col-xs-8">Short Description : President ( 2012 - Till )</div>
                <div class="col-xs-4">
                <div>
                <span>Follow : -</span>
                <ul class="follow">
                <li><a href="#" class="facebook"></a></li>
                <li><a href="#" class="twitter"></a></li>
                <li><a href="#" class="gplus"></a></li>
                <li><a href="#" class="linkedin"></a></li>
                </ul>
                </div>
                </div>
                <div class="clearfix"></div>
                <div class="col-xs-12">
                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the 
                </p>
                </div>
                </div>
                </li> */-->

            </ul>
        </div>
    </div>


    <div class="clearfix"></div>

    <div class="featured-list">
        <ul id="flexiselDemo2">
            <li style="width:100%;">
                <a href="<?php echo $this->basePath() ?>/pages/gallery" style="float:left; padding:0;" class="col-sm-4">
                    <div class="col-xs-5"><img src="<?php echo $this->basePath('images/gallery-thumb.jpg') ?>" class="img-responsive" /></div>
                    <div class="col-xs-7"><span class="bar">&nbsp;</span><h2><?php echo $this->translate('PHOTO GALLERY') ?></h2></div>
                </a>

                <a href="<?php echo $this->basePath() ?>/pages/about" style="float:left; padding:0;" class="col-sm-4">
                    <div class="col-xs-5"><img src="<?php echo $this->basePath('images/about-us-thumb.jpg') ?>" class="img-responsive" /></div>
                    <div class="col-xs-7"><span class="bar">&nbsp;</span><h2><?php echo $this->translate('ABOUT RUSTAGI SAMAJ') ?></h2></div>
                </a>

                <a href="<?php echo $this->basePath() ?>/matrimonial" style="float:left; padding:0;" class="col-sm-4">
                    <div class="col-xs-5"><img src="<?php echo $this->basePath('images/matrimonial.jpg') ?>" class="img-responsive" /></div>
                    <div class="col-xs-7"><span class="bar">&nbsp;</span><h2><?php echo $this->translate('MATRIMONIAL') ?></h2></div>
                </a>
            </li>

            <li>
                <a href="<?php echo $this->basePath() ?>/pages/gallery" class="col-sm-12" style="width:100%; padding:0;">
                    <img src="<?php echo $this->basePath('images/rustagi_ad.jpg') ?>" class="img-responsive" style="width:100%;" />
                </a>
            </li>
        </ul>
    </div>

    <!--<nav id="chk" >
      <ul class="pagination">
      <li class="disabled"><a href="#">Pages:</a></li>
        <li><a href="#">1</a></li>
        <li><a href="#">2</a></li>
        <li><a href="#">3</a></li>
        <li><a href="#">4</a></li>
        <li><a href="#">5</a></li>
        <li><a href="#">6</a></li>
        <li><a href="#">7</a></li>
        <li class="disabled"><a href="#">.....</a></li>
        
      </ul>
    </nav>-->
</div>

<script>
    $("#list").on('click', function () {

        $(".li_listmember").addClass('li_listmember_wid');
    });
    $("#grid").on('click', function () {
        $(".li_listmember").removeClass('li_listmember_wid');
    });
</script>
<?php echo $this->inlineScript()->prependFile($this->basePath('/js/member_filters.js')); ?>