<ul class="nav nav-pills">
        <li><a href="<?php echo $this->basePath() ?>/account/about"><?php echo $this->translate('About') ?></a></li> 
        <li class="active"><a href="<?php echo $this->basePath() ?>/account/personal-detail"><?php echo $this->translate('Personal Details') ?></a></li>
        <li><a href="<?php echo $this->basePath() ?>/account/education-and-career"><?php echo $this->translate('Education & Career') ?></a></li>  
        <!--<li><a href="<?php echo $this->basePath() ?>/account/profession"><?php echo $this->translate('Profession') ?></a></li>-->
        <li><a href="<?php echo $this->basePath() ?>/account/family-detail"><?php echo $this->translate('Family Details') ?></a></li>
        <!--/* <li><a href="<?php //echo $this->basePath() ?>/account/editmatrimoni"><?php echo $this->translate('Marital Details') ?></a></li> */-->

        <li><a href="<?php echo $this->basePath() ?>/account/post"><?php echo $this->translate('Post') ?></a></li>
        <li><a href="<?php echo $this->basePath() ?>/account/mygallery"><?php echo $this->translate('Gallery') ?></a></li>
    </ul>