<table id="" class="table table-striped table-bordered table-hover">  <!--id="bootstrap-table"-->
                      <thead>
                        <tr>
                        <th class="center"> <label class="pos-rel">
                            <input type="checkbox" class="ace" />
                            <span class="lbl"></span> </label>
                        </th>
                          <th>User ID</th>
                          <th>Personal Details</th>
                          <th>Physical Details</th>
                          <th>Religional Details</th>
                          <th valign="top" >Educations</th>
                          <th valign="top" >Location</th>
                          <th valign="top" >Family Details</th>
                          <th>Office Details</th>
                          
                          <!-- <th valign="top" >Type of User</th> -->
                          <th valign="top" >Financial Year</th>
                          <th valign="top" >Membership Paid</th>
                          <th valign="top" >Community Member Status</th>
                          <th valign="top" >Status</th>
                        </tr>
                      </thead>
                        <tbody>
                      <?php 
                      $i =1;
                      if(count($userinfos)>0){
                        foreach ($userinfos as $userinfo) {
                          
                        

                      ?>
                      <tr>
                      <td class="center"><label class="pos-rel">
                            <input type="checkbox" class="ace" />
                            <span class="lbl"></span> </label></td>
                        <td  tar="UserIdTab<?php echo $i;?>" class="itarget" ><?php echo (empty($userinfo->uid))?'See More':$userinfo->uid; ?></td>                        
                        <td  tar="PersonalDetailTab<?php echo $i;?>" class="itarget" ><?php echo (empty($userinfo->full_name))?'See More':$userinfo->full_name; ?></td>                        
                        <td  tar="PhysicalDetailTab<?php echo $i;?>" class="itarget" ><?php echo (empty($userinfo->height))?'See More':$userinfo->height; ?></td>                        
                        <td  tar="ReligionalDetailTab<?php echo $i;?>" class="itarget" ><?php echo (empty($userinfo->marital_status))?'See More':$userinfo->marital_status; ?></td>                        
                        <td  tar="EducationsTab<?php echo $i;?>" class="itarget" ><?php echo (empty($userinfo->education_field))?'See More':$userinfo->education_field; ?></td>                        
                        <td  tar="LocationTab<?php echo $i;?>" class="itarget" ><?php echo (empty($userinfo->country_name))?'See More':$userinfo->country_name; ?></td>                        
                        <td  tar="FamilyDetailTab<?php echo $i;?>" class="itarget" ><?php echo (empty($userinfo->father_name))?'See More':$userinfo->father_name; ?></td>                        
                        <td  tar="OfficeDetailTab<?php echo $i;?>" class="itarget" >Office details</td> 
                        <?php /*?>
                        <td  tar="<!--LocationTab<?php echo $i;?>-->" class="itarget" >
                        <select style="width:80px;" name="usertypes" onchange="changesuserType($(this).val(),'<?=$userinfo->uid?>','<?= $this->serverUrl().$this->url().'/Matrimonyuser/updateusertype';?>',changstatusresult)">
                          <option value="0">Select</option>
                          <?php 
                            foreach ($usertypes as $key => $value) {
                            
                            $select = ($key == $userinfo->user_type_id)? 'selected ="selected"':"";
                            echo "<option value='".$key."' ".$select.">".$value."</option>";
                             
                          }
                            ?>
    
                        </select></td> 
                        <?php */?>                       
                        <td  tar="FinancialYearTab<?php echo $i;?>" class="itarget"><?php echo (empty($userinfo->financial_year))?'See More':$userinfo->financial_year; ?></td>                        
                        <td  tar="membershipPaidTab<?php echo $i;?>" class="itarget"><?php echo (empty($userinfo->membership_paid))?'See More':$userinfo->membership_paid; ?></td> 

                        <td class="itarget">
                          <?php 
                          if($userinfo->parent_id<=1){
                          // else{
                          ?>
                          <select style="width:80px;" name="usertypes" onchange="changeCommType($(this).val(),'<?=$userinfo->uid?>','<?= $this->serverUrl().$this->url().'/Matrimonyuser/updatecommtype';?>',changCommTyperesults)">
                            <?php $chk = ( $userinfo->comm_mem_id == 0)? 'selected ="selected"':""; ?>
                          <option value="0" <?=$chk?> >Not Assigned</option>
                          <?php 
                            foreach ($commtypes as $key => $value) {
                            
                            $select = ($value['id'] == $userinfo->comm_mem_id)? 'selected ="selected"':"";
                            echo "<option value='".$value['id']."' ".$select.">".$value['category_name']."</option>";
                             
                          }
                            ?>
    
                        </select>
                        <?php 
                      }
                      else if($userinfo->Head==2){
                        ?>
                        <input type='button' style='background:lightyellow;' value='view' onclick='viewAssigned("<?=$userinfo->uid?>","<?=$userinfo->full_name?>","<?= $this->serverUrl().$this->url()."/matrimonyuser/viewloneassigned"?>",viewassignedresults)'>
                        <?php
                      }
                      else {
                        ?>
                        <input type='button' style='background:lightgreen;' value='view' onclick='viewAssigned("<?=$userinfo->uid?>","<?=$userinfo->full_name?>","<?= $this->serverUrl().$this->url()."/matrimonyuser/viewassigned"?>",viewassignedresults)'>
                        <?php 
                      }
                        ?>
                        </td>


                        <td class="hidden-480"><?php $status = ($userinfo->userstatus==1)? 'Active': 'In-Active';
                        $statuscolor = ($userinfo->userstatus==1)? 'activestatus': 'de-activestatus';
                         ?>
                          <div name="ChangeStatus" id="changestatus<?=$i;?>" onclick="changestatusquick(<?=$userinfo->uid?>,<?= ($userinfo->userstatus==0)?0:1; ?>,'<?= $this->serverUrl().$this->url().'/Matrimonyuser/changestatus';?>',changstatusresult);" class="<?=$statuscolor?>">
                        </div></td>                       
                         
                      </tr>

                  <tr class="dontshow" id="UserIdTab<?php echo $i;?>">
                        <td colspan="13" align="left">
                      <div class="tabbable">
                      <ul class="nav nav-tabs padding-12 tab-color-blue background-blue" id="myTab4">
                        <li class="active">
                          <a href="javascript:void(0);" >User ID</a>
                        </li>
                      </ul>
                      <div class="tab-content">
                        <div class="row">
                   <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Profile ID'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                      <?php echo $userinfo->uid; ?>
                                                                                         
                                                  </div>
                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('E-Mail'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      <?php echo $userinfo->email; ?>
                                                                                         
                                                  </div>
                           
                                                 </div>
                                             </div>
                                             <div class="row">
                   <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Mobile No'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                      <?php echo $userinfo->mobile_no; ?>
                                                                                         
                                                  </div>
                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Created Date'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      <?php echo $userinfo->created_date; ?>
                                                                                         
                                                  </div>
                           
                                                 </div>
                                             </div>
                                             <div class="row">
                   <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('User Type'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                      <?php echo $userinfo->user_type; ?>
                                                                                         
                                                  </div>
                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Reference No'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                      <?php echo $userinfo->ref_no; ?>
                                                                                         
                                                  </div>
                                                 </div>
                                             </div>
                                              <div class="row">
                   <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('User Name'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                      <?php echo $userinfo->username; ?>
                                                                                         
                                                  </div>
                                                   
                                                 </div>
                                             </div>
                      </div>
                      </div>
                      </td>
                  </tr>

                  <tr class="dontshow" id="PersonalDetailTab<?php echo $i;?>">
                        <td colspan="13" align="left">
                      <div class="tabbable">
                      <ul class="nav nav-tabs padding-12 tab-color-blue background-blue" id="myTab4">
                        <li class="active">
                          <a href="javascript:void(0);" >Personal Details</a>
                        </li>
                      </ul>
                      <div class="tab-content">
                        <div class="row">
                   <div class="form-group clearfix margintopbottom20">
                           
                                                  <div class="col-sm-2">
                                                      
                                                     
                                                     <?php $imagePath = (empty($userinfo->profile_photo))?'/img/default_user.png' : $userinfo->profile_photo;
                                                     // echo $this->basepath().$imagePath."sasasasas";
                                                     ?><img src="<?= $this->basepath().$imagePath;?>" alt="">
                                                                                         
                                                  </div>
                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('About User'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <textarea class="addressstyle" col="100"> <?= (empty($userinfo->about_yourself_partner_family))? 'Not Available':$userinfo->about_yourself_partner_family; ?></textarea>
                                                                                         
                                                  </div>
                                                   
                           
                                                 </div>
                                             </div>
                                             <div class="row">
                   <div class="form-group clearfix margintopbottom20">
                           
                                                  
                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Phone No'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <p> <?= (empty($userinfo->phone_no))? 'Not Available':$userinfo->phone_no; ?></p>
                                                                                         
                                                  </div>
                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Address'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <p> <?= (empty($userinfo->address))? 'Not Available':$userinfo->address; ?></p>
                                                                                         
                                                  </div>
                                                   
                           
                                                 </div>
                                             </div>
                                             <div class="row">
                   <div class="form-group clearfix margintopbottom20">
                           
                                                  
                                                   
                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Full Name'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <p> <?= (empty($userinfo->full_name))? 'Not Available':$userinfo->full_name; ?></p>
                                                                                         
                                                  </div>
                                                   <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Date of Birth'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <p> <?= (empty($userinfo->dob))? 'Not Available':$userinfo->dob; ?></p>
                                                                                         
                                                  </div>
                           
                                                 </div>
                                             </div>
                                             <div class="row">
                   <div class="form-group clearfix margintopbottom20">
                           
                                                  
                                                   
                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Age'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <p> <?= (empty($userinfo->age))? 'Not Available':$userinfo->age; ?></p>
                                                                                         
                                                  </div>
                                                  
                           
                                                 </div>
                                             </div>
                      </div>
                      </div>
                      </td>
                  </tr>
                  <tr class="dontshow" id="PhysicalDetailTab<?php echo $i;?>">
                        <td colspan="13" align="left">
                      <div class="tabbable">
                      <ul class="nav nav-tabs padding-12 tab-color-blue background-blue" id="myTab4">
                        <li class="active">
                          <a href="javascript:void(0);" >Physical Details</a>
                        </li>
                      </ul>
                      <div class="tab-content">
                        <div class="row">
                   <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Height'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                      <?= (empty($userinfo->height))? 'Not Available':$userinfo->height; ?>
                                                                                         
                                                  </div>
                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Blood Group '); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?= (empty($userinfo->blood_group))? 'Not Available':$userinfo->blood_group; ?>
                                                                                         
                                                  </div>
                           
                                                 </div>
                                             </div>
                                             <div class="row">
                   <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Color Complexion'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                      <?= (empty($userinfo->color_complexion))? 'Not Available':$userinfo->color_complexion; ?>
                                                                                         
                                                  </div>
                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Any Disability '); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?= (empty($userinfo->any_disability))? 'Not Available':$userinfo->any_disability; ?>
                                                                                         
                                                  </div>
                           
                                                 </div>
                                             </div>
                                             <div class="row">
                   <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Body Type'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                      <?= (empty($userinfo->body_type))? 'Not Available':$userinfo->body_type; ?>
                                                                                         
                                                  </div>
                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Gender'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                      <?= (empty($userinfo->gender))? 'Not Available':$userinfo->gender; ?>
                                                                                         
                                                  </div>
                                                   
                           
                                                 </div>
                                             </div>
                      </div>
                      </div>
                      </td>
                  </tr>
                  <tr class="dontshow" id="ReligionalDetailTab<?php echo $i;?>">
                        <td colspan="13" align="left">
                      <div class="tabbable">
                      <ul class="nav nav-tabs padding-12 tab-color-blue background-blue" id="myTab4">
                        <li class="active">
                          <a href="javascript:void(0);" >Religional Details</a>
                        </li>
                      </ul>
                      <div class="tab-content">
                        <div class="row">
                   <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Caste'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                      <?= (empty($userinfo->caste_name))? 'Not Available':$userinfo->caste; ?>
                                                                                         
                                                  </div>
                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Religion '); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?= (empty($userinfo->religion_name))? 'Not Available':$userinfo->religion_name; ?>
                                                                                         
                                                  </div>
                           
                                                 </div>
                                             </div>
                                             <div class="row">
                   <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Mangalik Dosh'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                      <?= (empty($userinfo->manglik_dossam))? 'Not Available':$userinfo->manglik_dossam; ?>
                                                                                         
                                                  </div>
                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Sevvai Dossam'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?= (empty($userinfo->sevvai_dosham))? 'Not Available':$userinfo->sevvai_dosham; ?>
                                                                                         
                                                  </div>
                           
                                                 </div>
                                             </div>
                                             <div class="row">
                   <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Gothra'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                      <?= (empty($userinfo->gothra_name))? 'Not Available':$userinfo->gothra_name; ?>
                                                                                         
                                                  </div>
                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Star Sign'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?= (empty($userinfo->star_sign_name))? 'Not Available':$userinfo->star_sign; ?>
                                                                                         
                                                  </div>
                           
                                                 </div>
                                             </div>
                                             <div class="row">
                   <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Zodia Sign'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                      <?= (empty($userinfo->zodiac_sign_name))? 'Not Available':$userinfo->zodiac_sign; ?>
                                                                                         
                                                  </div>
                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Marital Status'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                      <?= (empty($userinfo->marital_status))? 'Not Available':$userinfo->marital_status; ?>
                                                                                         
                                                  </div>
                                                  
                           
                                                 </div>
                                             </div>
                      </div>
                      </div>
                      </td>
                  </tr>
                  <tr class="dontshow" id="EducationsTab<?php echo $i;?>">
                        <td colspan="13" align="left">
                      <div class="tabbable">
                      <ul class="nav nav-tabs padding-12 tab-color-blue background-blue" id="myTab4">
                        <li class="active">
                          <a href="javascript:void(0);" >Educations</a>
                        </li>
                      </ul>
                      <div class="tab-content">
                        <div class="row">
                   <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Education Field'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                      <?= (empty($userinfo->education_field))? 'Not Available':$userinfo->education_field; ?>
                                                                                         
                                                  </div>
                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Education Level'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                      <?= (empty($userinfo->education_level))? 'Not Available':$userinfo->education_level; ?>
                                                                                         
                                                  </div>
                                                  
                           
                                                 </div>
                                             </div>
                                             <div class="row">
                   <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Annual Income'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                      <?= (empty($userinfo->annual_income))? 'Not Available':$userinfo->annual_income; ?>
                                                                                         
                                                  </div>
                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Specialisation'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                      <?= (empty($userinfo->specialization_major))? 'Not Available':$userinfo->specialization_major; ?>
                                                                                         
                                                  </div>
                                                  
                           
                                                 </div>
                                             </div>
                                             <div class="row">
                   <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Employment Status'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                      <?= (empty($userinfo->employment_status))? 'Not Available':$userinfo->employment_status; ?>
                                                                                         
                                                  </div>
                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Specialisation'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                      <?= (empty($userinfo->specialization_major))? 'Not Available':$userinfo->specialization_major; ?>
                                                                                         
                                                  </div>

                           
                                                 </div>
                                             </div>
                                             <div class="row">
                   <div class="form-group clearfix margintopbottom20">
                           

                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Profession'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                      <?= (empty($userinfo->profession))? 'Not Available':$userinfo->profession; ?>
                                                                                         
                                                  </div>
                                                  
                           
                                                 </div>
                                             </div>
                      </div>
                      </div>
                      </td>
                  </tr>
                   
                  <tr class="dontshow" id="LocationTab<?php echo $i;?>">
                        <td colspan="13" align="left">
                      <div class="tabbable">
                      <ul class="nav nav-tabs padding-12 tab-color-blue background-blue" id="myTab4">
                        <li class="active">
                          <a href="javascript:void(0);" >Location</a>
                        </li>
                      </ul>
                      <div class="tab-content">
                        <div class="row">
                   <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Country'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                      <?= (empty($userinfo->country_name))? 'Not Available':$userinfo->country_name; ?>
                                                                                         
                                                  </div>
                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('State'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                      <?= (empty($userinfo->state_name))? 'Not Available':$userinfo->state_name; ?>
                                                                                         
                                                  </div>

                           
                                                 </div>
                                             </div>
                                             <div class="row">
                   <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('City'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                      <?= (empty($userinfo->city_name))? 'Not Available':$userinfo->city_name; ?>
                                                                                         
                                                  </div>
                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Native Place'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                      <?= (empty($userinfo->native_place))? 'Not Available':$userinfo->native_place; ?>
                                                                                         
                                                  </div>

                           
                                                 </div>
                                             </div>
                                             <div class="row">
                   <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Pin Code'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                      <?= (empty($userinfo->zip_pin_code))? 'Not Available':$userinfo->zip_pin_code; ?>
                                                                                         
                                                  </div>
                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Address'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                    <TEXTAREA cols="20" rows="1"><?= (empty($userinfo->address))? 'Not Available':$userinfo->address; ?></TEXTAREA>  
                                                                                         
                                                  </div>

                           
                                                 </div>
                                             </div>
                      </div>
                      </div>
                      </td>
                  </tr>
                  <tr class="dontshow" id="FamilyDetailTab<?php echo $i;?>">
                        <td colspan="13" align="left">
                      <div class="tabbable">
                      <ul class="nav nav-tabs padding-12 tab-color-blue background-blue" id="myTab4">
                        <li class="active">
                          <a href="javascript:void(0);" >Family Details</a>
                        </li>
                      </ul>
                      <div class="tab-content">
                        <div class="row">
                   <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Father Name'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                      <?= (empty($userinfo->father_name))? 'Not Available':$userinfo->father_name; ?>
                                                                                         
                                                  </div>
                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Father Date of Birth'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                    <?= (empty($userinfo->father_dob))? 'Not Available':$userinfo->father_dob; ?>  
                                                                                         
                                                  </div>

                           
                                                 </div>
                                             </div>
                          <div class="row">
                   <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Father Status'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                      <?= (empty($userinfo->father_status))? 'Not Available':$userinfo->father_status; ?>
                                                                                         
                                                  </div>
                                                  <?php if($userinfo->father_status=="Passed Away"){?>
                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Date of Death'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                    <?= (empty($userinfo->father_dod))? 'Not Available':$userinfo->father_dod; ?>  
                                                                                         
                                                  </div>
                                                  <?php }?>
                           
                                                 </div>
                                             </div>
                         <div class="row">
                   <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Father House Address'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                      <TEXTAREA  cols="20" rows="1"><?= (empty($userinfo->father_house_address))? 'Not Available':$userinfo->father_house_address; ?>
                                                          </TEXTAREA>                               
                                                  </div>
                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Father Office Address'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                    <TEXTAREA cols="20" rows="1"><?= (empty($userinfo->father_office_address))? 'Not Available':$userinfo->father_office_address; ?></TEXTAREA>  
                                                                                         
                                                  </div>

                           
                                                 </div>
                                             </div>
                          <div class="row">
                   <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Father Email'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                      <?= (empty($userinfo->father_email))? 'Not Available':$userinfo->father_email; ?>
                                                                                         
                                                  </div>
                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Father Mobile'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                     
                                                     
                                                    <?= (empty($userinfo->father_mobile))? 'Not Available':$userinfo->father_mobile; ?> 
                                                                                         
                                                  </div>

                           
                                                 </div>
                                             </div>
                          <div class="row">
                   <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Father Photo'); ?>
                            
                           </label>
                           
                           
                           
                           
                           
                                                  <div class="col-sm-3">
                                                  
                                                
                                                  
                                                
                                                
                                                
                                                
                                                  <div class="col-sm-3 col-xs-3">
                                                  
												  
                                                 <a href="#" class="thumbnail" data-toggle="modal" data-target="#lightbox"> 
            <img src="/rustagi-new/img/600x350.png" alt="..."  class="imgnew">
            
             <button aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button>
            
        </a>
        </div>
        
       
      
												  
												 <!--<a href="#"  data-toggle="modal" data-target="#lightbox"> <img class="thumbnail img-responsive"  src="/rustagi-new/img/600x350.png" width="60px" height="50px"  ></a>-->
												   <!--<a href="#" class="thumbnail" data-toggle="modal" data-target="#lightbox"> 
												   <?php $imagePath = (empty($userinfo->father_photo))? '/images/new-big.jpg' : $userinfo->father_photo;?>
												    <img src="<?= $this->basepath().$imagePath;?>" width="43" height="37" alt="">
												   </a>-->
												   
                                                     <div id="lightbox" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <!--  <button type="button" class="close hidden" data-dismiss="modal" aria-hidden="true">×</button>-->
        <div class="modal-content">
            <div class="modal-body">
                <img src="" alt="" />
            </div>
        </div>
    </div>
</div>
                      
                                             </div>
                                             <div class="row">
                   <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Mother Name'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                      <?= (empty($userinfo->mother_name))? 'Not Available':$userinfo->mother_name; ?>
                                                                                         
                                                  </div>
                                                 
                                                 
                           
                                                 </div>
                                             </div>
                          <div class="row">
                   <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Mother Status'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                      <?= (empty($userinfo->mother_status))? 'Not Available':$userinfo->mother_status; ?>
                                                      
                                                      
                                                      
                                                      
                                                      
                                                                                         
                                                  </div>
                                                  
                                                  <label class="col-sm-2 control-label labelalign " id="flight_nos">
                            Mother Date of Birth                           </label>
                            
                            
                            
                             <div class="col-sm-3">
                                                      
                                                     
                                                      <?= (empty($userinfo->grand_mother_name))? 'Not Available':$userinfo->grand_mother_name; ?>
                                                                                         
                                                  </div>  
                            
                                                  
                                                  
                                                  
                                                  <?php if($userinfo->mother_status=="Passed Away"){?>
                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Mother Date of Death'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                    <?= (empty($userinfo->mother_dod))? 'Not Available':$userinfo->mother_dod; ?>  
                                                                                         
                                                  </div>
                                                  <?php }?>
                           
                                                 </div>
                                             </div>
                         <div class="row">
                   <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Mother House Address'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                      <TEXTAREA cols="20" rows="1"><?= (empty($userinfo->mother_house_address))? 'Not Available':$userinfo->mother_house_address; ?>
                                                          </TEXTAREA>                               
                                                  </div>
                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Father Office Address'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                    <TEXTAREA cols="20" rows="1"><?= (empty($userinfo->father_office_address))? 'Not Available':$userinfo->father_office_address; ?></TEXTAREA>  
                                                                                         
                                                  </div>

                           
                                                 </div>
                                             </div>
                          <div class="row">
                   <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Mother Email'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                      <?= (empty($userinfo->mother_email))? 'Not Available':$userinfo->mother_email; ?>
                                                                                         
                                                  </div>
                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Mother Mobile'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                    <?= (empty($userinfo->mother_mobile))? 'Not Available':$userinfo->mother_mobile; ?> 
                                                                                         
                                                  </div>

                           
                                                 </div>
                                             </div>
                          <div class="row">
                   <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Mother Photo'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      <?php $imagePath = (empty($userinfo->mother_photo))? '/images/new-big.jpg' : $userinfo->mother_photo;?>
                        <img src="<?= $this->basepath().$imagePath;?>" width="43" height="37" alt="">
                                                     

                                                                                         
                                                  </div>
                                                   

                           
                                                 </div>
                                             </div>
                                             <div class="row">
                   <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Spouse Name'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                      <?= (empty($userinfo->spouse_name))? 'Not Available':$userinfo->spouse_name; ?>
                                                                                         
                                                  </div>
                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Spouse Date of Birth'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                    <?= (empty($userinfo->spouse_dob))? 'Not Available':$userinfo->spouse_dob; ?>  
                                                                                         
                                                  </div>

                           
                                                 </div>
                                             </div>
                          <div class="row">
                   <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Spouse Status'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                      <?= (empty($userinfo->spouse_status))? 'Not Available':$userinfo->spouse_status; ?>
                                                                                         
                                                  </div>
                                                  <?php if($userinfo->spouse_status=="Passed Away"){?>
                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('spouse Date of Death'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                    <?= (empty($userinfo->spouse_died_on))? 'Not Available':$userinfo->spouse_died_on; ?>  
                                                                                         
                                                  </div>
                                                  <?php }?>
                           
                                                 </div>
                                             </div>
                         <div class="row">
                   <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Spouse House Address'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                      <TEXTAREA cols="20" rows="1"><?= (empty($userinfo->spouse_house_address))? 'Not Available':$userinfo->spouse_house_address; ?>
                                                          </TEXTAREA>                               
                                                  </div>
                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Father Office Address'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                    <TEXTAREA cols="20" rows="1"><?= (empty($userinfo->spouse_office_address))? 'Not Available':$userinfo->spouse_office_address; ?></TEXTAREA>  
                                                                                         
                                                  </div>

                           
                                                 </div>
                                             </div>
                          <div class="row">
                   <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Spouse Email'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                      <?= (empty($userinfo->spouse_email))? 'Not Available':$userinfo->spouse_email; ?>
                                                                                         
                                                  </div>
                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Spouse Mobile'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                    <?= (empty($userinfo->spouse_mobile))? 'Not Available':$userinfo->spouse_mobile; ?> 
                                                                                         
                                                  </div>

                           
                                                 </div>
                                             </div>
                          <div class="row">
                   <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Spouse Photo'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      <?php $imagePath = (empty($userinfo->spouse_photo))? '/images/new-big.jpg' : $userinfo->spouse_photo;?>
                        <img src="<?= $this->basepath().$imagePath;?>" width="43" height="37" alt="">
                                                     

                                                                                         
                                                  </div>
                                                   

                           
                                                 </div>
                                             </div>

                                             <div class="row">
                   <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Grand Father Name'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                      <?= (empty($userinfo->grand_father_name))? 'Not Available':$userinfo->grand_father_name; ?>
                                                                                         
                                                  </div>
                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Grand Father Date of Birth'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                    <?= (empty($userinfo->grand_father_dob))? 'Not Available':$userinfo->grand_father_dob; ?>  
                                                                                         
                                                  </div>

                           
                                                 </div>
                                             </div>
                          <div class="row">
                   <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Grand Father Status'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                      <?= (empty($userinfo->grand_father_status))? 'Not Available':$userinfo->grand_father_status; ?>
                                                                                         
                                                  </div>
                                                  <?php if($userinfo->grand_father_status=="Passed Away"){?>
                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Grand Father Date of Death'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                    <?= (empty($userinfo->grand_father_dod))? 'Not Available':$userinfo->grand_father_dod; ?>  
                                                                                         
                                                  </div>
                                                  <?php }?>
                           
                                                 </div>
                                             </div>
                          
                          
                          <div class="row">
                   <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Grand Father Photo'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      <?php $imagePath = (empty($userinfo->grand_father_photo))? '/images/new-big.jpg' : $userinfo->grand_father_photo;?>
                        <img src="<?= $this->basepath().$imagePath;?>" width="43" height="37" alt="">
                                                     

                                                                                         
                                                  </div>
                                                   

                           
                                                 </div>
                                             </div>
                                             <div class="row">
                   <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Grand Mother Name'); ?>
                           </label>
                                                 
                                                  
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                    <?= (empty($userinfo->grand_mother_dob))? 'Not Available':$userinfo->grand_mother_dob; ?>  
                                                                                         
                                                  </div>

                           
                                                 </div>
                                             </div>
                          <div class="row">
                   <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Grand Mother Status'); ?>
                            
                           
                           </label>
                           
                           
                           
                           
                           
                           
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                      <?= (empty($userinfo->grand_mother_status))? 'Not Available':$userinfo->grand_mother_status; ?>
                                                                                         
                                                  </div>
                                                  
                                                  
                                                    <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Grand Mother Date of Birth'); ?>
                           </label>    
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  <?php if($userinfo->grand_mother_status=="Passed Away"){?>
                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Grand Mother Date of Death'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                    <?= (empty($userinfo->grand_mother_dod))? 'Not Available':$userinfo->grand_mother_dod; ?>  
                                                                                         
                                                  </div>
                                                  <?php }?>
                           
                                                 </div>
                                             </div>
                          
                          
                          <div class="row">
                   <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Grand Mother Photo'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      <?php $imagePath = (empty($userinfo->grand_mother_photo))? '/images/new-big.jpg' : $userinfo->grand_mother_photo;?>
                        <img src="<?= $this->basepath().$imagePath;?>" width="43" height="37" alt="">
                                                     

                                                                                         
                                                  </div>
                                                   

                           
                                                 </div>
                                             </div>
                                                                                                                                                              
                      </div>
                      </div>
                      
                      </div>
                      </div>
                      </td>
                  </tr>
                  <tr class="dontshow" id="OfficeDetailTab<?php echo $i;?>">
                        <td colspan="13" align="left">
                      <div class="tabbable">
                      <ul class="nav nav-tabs padding-12 tab-color-blue background-blue" id="myTab4">
                        <li class="active">
                          <a href="javascript:void(0);" >Office Details</a>
                        </li>
                      </ul>
                      <div class="tab-content">
                        <div class="row">
                   <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Office Name'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                      <?= (empty($userinfo->office_name))? 'Not Available':$userinfo->office_name; ?>
                                                                                         
                                                  </div>
                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Office Address'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                    <TEXTAREA cols="20" rows="1"><?= (empty($userinfo->office_address))? 'Not Available':$userinfo->office_address; ?></TEXTAREA>  
                                                                                         
                                                  </div>

                           
                                                 </div>
                                             </div>
                                             <div class="row">
                   <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Office Email'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                      <?= (empty($userinfo->office_email))? 'Not Available':$userinfo->office_email; ?>
                                                                                         
                                                  </div>
                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Office Country'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                   <?= (empty($userinfo->office_country))? 'Not Available':$userinfo->office_country; ?>  
                                                                                         
                                                  </div>

                           
                                                 </div>
                                             </div>
                                           
                                             <div class="row">
                   <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Office State'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                      <?= (empty($userinfo->office_state))? 'Not Available':$userinfo->office_state; ?>
                                                                                         
                                                  </div>
                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Office City'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                   <?= (empty($userinfo->office_city))? 'Not Available':$userinfo->office_city; ?> 
                                                                                         
                                                  </div>

                           
                                                 </div>
                                             </div>
                                               <div class="row">
                   <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Office Pincode'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                      <?= (empty($userinfo->office_pincode))? 'Not Available':$userinfo->office_pincode; ?>
                                                                                         
                                                  </div>
                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Office Phone'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                    <?= (empty($userinfo->office_phone))? 'Not Available':$userinfo->office_phone; ?> 
                                                                                         
                                                  </div>

                           
                                                 </div>
                                             </div>
                                               <div class="row">
                   <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Office Website'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                      <?= (empty($userinfo->office_website))? 'Not Available':$userinfo->office_website; ?>
                                                                                         
                                                  </div>
                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Designation'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                    <?= (empty($userinfo->designation))? 'Not Available':$userinfo->designation; ?> 
                                                                                         
                                                  </div>

                           
                                                 </div>
                                             </div>
                                              <div class="row">
                   <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Profession'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                      <?= (empty($userinfo->profession))? 'Not Available':$userinfo->profession; ?>
                                                                                         
                                                  </div>
                                                  

                           
                                                 </div>
                                             </div>
                      </div>
                      </div>
                      </td>
                  </tr>
                  <tr class="dontshow" id="membershipPaidTab<?php echo $i;?>">
                        <td colspan="13" align="left">
                      <div class="tabbable">
                      <ul class="nav nav-tabs padding-12 tab-color-blue background-blue" id="myTab4">
                        <li class="active">
                          <a href="javascript:void(0);" >Membership Details</a>
                        </li>
                      </ul>
                      <div class="tab-content">
                        <div class="row">
                   <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Height'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                      <h2> No Data Available</h2>
                                                      
                                                                                         
                                                  </div>
                                                   
                           
                                                 </div>
                                             </div>
                                              
                      </div>
                      </div>
                      </td>
                  </tr>
                    <tr class="dontshow" id="FinancialYearTab<?php echo $i;?>">
                        <td colspan="13" align="left">
                      <div class="tabbable">
                      <ul class="nav nav-tabs padding-12 tab-color-blue background-blue" id="myTab4">
                        <li class="active">
                          <a href="javascript:void(0);" >Financial Year Details</a>
                        </li>
                      </ul>
                      <div class="tab-content">
                        <div class="row">
                   <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                             
                           </label>
                                                  <div class="col-sm-3">
                                                      
                                                     
                                                      <h2> No Data Available</h2>
                                                                                         
                                                  </div>
                                                   
                           
                                                 </div>
                                             </div>
                                              
                      </div>
                      </div>
                      </td>
                  </tr>
                  
                      
                      
                      
                      <?php 
                    $i++;
                    }
                  }
                  else {
                    echo "<tr><td colspan='9'> No data Available </td></tr>";
                  }
                      ?>
                      </tbody>
                      </table>