<div class="col-sm-3 col-sm-3-new width20per">
    <?php echo $this->partial('layout/sidebar-user') ?>
</div>

<div class="col-sm-9 width80per">
    <?php include('main_info.phtml'); ?>
    <div class="col-sm-6" style="margin-top:22px; float:right; text-align:right;">
        <p style="text-align:right;">Connected  9 Months ago</p>
    </div>

    <div class="clearfix"></div>
    <?php include('menu.phtml'); ?>
    <div class="tab-content">
        <div id="personal_info" class="tab-pane fade in active">
            <table width="100%">
                <tr>
                    <td>
                        <?php
                        $form = $this->form;
                        $form->prepare();
                        echo $this->form()->openTag($form);
                        echo $this->formHidden($form->get('id'));
                        ?>
                        <div class="col-sm-4" style="width:100%;">

                            <h3><?php echo $this->translate('Update Education Info') ?></h3>

                            <div class="form-group row">
                                <label for="Education Level" class="col-sm-2 form-control-label edupading"><?php echo $this->translate('Education Level') ?></label>
                                <div class="col-sm-3">
                                    <?php
                                    echo $this->formRow($form->get('education_level'));
                                    ?>               
                                </div>
                                <div id="edu_level_Others_row" style="display:none;">
                                    <label for="Education Level" class="col-sm-2 form-control-label edupading"><?php echo $this->translate('Education Level Other') ?></label>
                                    <div class="col-sm-3"><?php echo $this->formRow($form->get('education_level_other')); ?> </div>
                                </div> 
                            </div>

                            <div class="form-group row">        
                                <label for="Education Field" class="col-sm-2 form-control-label edupading"><?php echo $this->translate('Education Field') ?></label>
                                <div class="col-sm-3"><?php echo $this->formRow($form->get('education_field')); ?></div>
                                <div id="edu_field_Others_row" style="display:none;">
                                    <label for="Education Field" class="col-sm-2 form-control-label edupading"><?php echo $this->translate('Education Field Other') ?></label>
                                    <div class="col-sm-3"><?php echo $this->formRow($form->get('education_field_other')); ?></div>
                                </div>
                            </div>
                            <h3><?php echo $this->translate('Update Your Career Info') ?></h3> 

                            <div class="form-group row">
                                <label for="Working With" class="col-sm-2 form-control-label edupading"><?php echo $this->translate('Working With') ?></label>
                                <div class="col-sm-3"><?php echo $this->formRow($form->get('working_with')); ?></div>

                                <div id="Working_Others_row" style="display:none;">
                                    <label for="Education Field" class="col-sm-2 form-control-label edupading"><?php echo $this->translate('Working Other') ?></label>
                                    <div class="col-sm-3"><?php echo $this->formRow($form->get('working_with_other')); ?></div>
                                </div>

                            </div>


                            <div class="form-group row">
                                <label for="Designation" class="col-sm-2 form-control-label edupading"><?php echo $this->translate('Designation'); ?></label>
                                <div class="col-sm-3"><?php echo $this->formRow($form->get('designation')); ?></div>
                                <div id="Designation_Others_row" style="display:none;">
                                    <label for="Education Level" class="col-sm-2 form-control-label edupading"><?php echo $this->translate('Designation Other') ?></label>
                                    <div class="col-sm-3"><?php echo $this->formRow($form->get('designation_other')); ?></div>
                                </div> 


                            </div>


                            <div class="form-group row">
                                <label for="Specialization" class="col-sm-2 form-control-label edupading"><?php echo $this->translate('Specialization'); ?></label>
                                <div class="col-sm-3">
                                        <!-- <input type="text" class="form-control" /> -->
                                    <?= $this->formRow($form->get('specialize_profession')); ?>

                                </div>
                            </div>


                            <div class="form-group row">
                                <label for="Annual Income" class="col-sm-2 form-control-label edupading"><?php echo $this->translate('Annual Income') ?></label>
                                <div class="col-sm-3"><?php echo $this->formRow($form->get('annual_income')); ?></div>
                            </div>


                            <div class="form-group row">

                                <label for="Office Name" class="col-sm-2 form-control-label edupading"><?php echo $this->translate('Office Name') ?></label>
                                <div class="col-sm-3"><?php echo $this->formRow($form->get('office_name')); ?></div>
                            </div>

                            <div class="form-group row">
                                <label for="Office Email" class="col-sm-2 form-control-label edupading"><?php echo $this->translate('Office Email'); ?></label>
                                <div class="col-sm-3"><?php echo $this->formRow($form->get('office_email')); ?></div>

                            </div>


                            <div class="form-group row">
                                <label for="Office Country" class="col-sm-2 form-control-label edupading"><?php echo $this->translate('Office Country'); ?></label>
                                <div class="col-sm-3"><?php echo $this->formRow($form->get('office_country')); ?></div>
                                <label for="Office Phone" class="col-sm-2 form-control-label edupading"><?php echo $this->translate('Office Phone'); ?></label>
                                <div class="col-sm-3"><?php echo $this->formRow($form->get('office_phone')); ?></div>
                            </div>

                            <div class="form-group row">
                                <label for="Office State" class="col-sm-2 form-control-label edupading"><?php echo $this->translate('Office State') ?></label>
                                <div class="col-sm-3"><?php echo $this->formRow($form->get('office_state')); ?></div>
                                <label for="Office Zip/Pin" class="col-sm-2 form-control-label edupading"><?php echo $this->translate('Office Zip/Pin') ?></label>
                                <div class="col-sm-3"><?php echo $this->formRow($form->get('office_pincode')); ?></div>
                            </div>

                            <img src="<?php echo $this->basePath() ?>/img/loadingmap.gif" id="Loading_Request" style="position:absolute;display:none;z-index: 9;margin-left: 45%;margin-top: -8%;width: 80px;"/>
                            <div class="form-group row">
                                <label for="Office City" class="col-sm-2 form-control-label edupading"><?php echo $this->translate('Office City'); ?></label>
                                <div class="col-sm-3"><?php echo $this->formRow($form->get('office_city')); ?></div>

                                <label for="Office Website" class="col-sm-2 form-control-label edupading"><?php echo $this->translate('Office Website') ?></label>
                                <div class="col-sm-3"><?php echo $this->formRow($form->get('office_website')); ?></div>


                            </div>

                            <DIV class="form-group row">
                                <label for="Office Address" class="col-sm-2 form-control-label edupading"><?php echo $this->translate('Office Address') ?></label>
                                <div class="col-sm-3"><?php echo $this->formRow($form->get('office_address')); ?></div>

                                <div class="col-sm-1 incomecbx"><?php echo $this->formRow($form->get('annual_income_status')); ?></div>
                                <label for="Office Website" class="col-sm-3 form-control-label lblline1" style="padding-left:15px !important;"><?php echo $this->translate('Hide Annual Income for Public'); ?></label>

                            </DIV>


                            <div class="form-group row" style="margin-top: 10px">
                                <label class="col-sm-3 "></label>
                                <div class="col-sm-3"><?php echo $this->formRow($form->get('submit')); ?>
                                    <input name="submit" id="submitnext" class="btn btn-default" value="Save & Next" type="submit">
                                </div>
                            </div>

                        </div>
                        <?php echo $this->form()->closeTag(); ?>
                    </td>
                </tr>
            </table>
        </div>
    </div>


</div>
<script>
    $(document).ready(function () {
        /* $("#CareerForm").validate({
         rules: {                            
         workplace_info:
         {
         required: true                                   
         },					
         office_address:
         {
         required: true
         },
         office_country:
         {
         required: true
         },
         office_state:
         {
         required: true                                
         },	
         office_city: 
         {
         required: true
         },
         designation:
         {
         required: true                                
         },
         working_with:
         {
         required: true                                
         },
         annual_income:
         {
         required: true,
         number:true,
         minlength:4,
         maxlength:12
         }
         },
         messages: {                              
         
         }
         }); */

        if ($("#working_with").val() == "Others") {
            $("#Working_Others_row").css('display', 'block');
        } else {
            $("#Working_Others_row").css('display', 'none');
        }
        if ($("#designation").val() == 7) {
            $("#Designation_Others_row").css('display', 'block');
        } else {
            $("#Designation_Others_row").css('display', 'none');
        }
    });
</script>


<script>
    /**************Get State on select Country***************/
    $("#office_country").on('change', function () {
        var countryId = this.value;
        $.ajax({
            url: '<?php echo $this->basePath() ?>' + '/account/getStateName',
            type: "POST",
            dataType: "json",
            data: {Country_ID: countryId},
            beforeSend: function () {
                $('#Loading_Request').show();
            },
            complete: function () {
                $('#Loading_Request').hide();
            },
            success: function (resp) {
                if (resp.Status == 'Success') {
                    $("#office_state").empty();
                    $("#office_city").empty();
                    $("#office_state").append("<option value=''>Select State</option>");
                    $.each(resp.statelist, function (idx, obj) {
                        $("#office_state").append("<option value='" + obj["id"] + "'>" + obj["state_name"] + "</option>");
                    });
                } else {
                    $("#office_state").empty();
                    $("#office_city").empty();
                    alert("No States are available");
                }
            },
            error: function (error) {
                console.log(error);
                alert(error);
            }
        });
    });
    /*******************End******************/
    /*************Get City on Select State*************************************************/
    $("#office_state").on('change', function () {
        var stateId = this.value;
        $.ajax({
            url: '<?php echo $this->basePath() ?>' + '/account/getCityName',
            type: "POST",
            dataType: "json",
            data: {State_ID: stateId},
            beforeSend: function () {
                $('#Loading_Request').show();
            },
            complete: function () {
                $('#Loading_Request').hide();
            },
            success: function (resp) {
                if (resp.Status == 'Success') {
                    $("#office_city").empty();
                    $("#office_city").append("<option value=''>Select City</option>");
                    $.each(resp.statelist, function (idx, obj) {
                        $("#office_city").append("<option value='" + obj["id"] + "'>" + obj["city_name"] + "</option>");
                    });
                } else {
                    $("#office_city").empty();
                    alert("No Cities are Available");
                }
            },
            error: function (error) {
                console.log(error);
                alert(error);
            }
        });
    });
    /*******************End******************/
</script>

<script>
//*****************************Others info hide show********************/
//*********apend working_with others info
    $("#working_with").on('change', function () {
        if ($("#working_with").val() == "Others") {
            $("#Working_Others_row").css('display', 'block');
        } else {
            $("#Working_Others_row").css('display', 'none');
        }
    });
//*********apend designation others info
    $("#designation").on('change', function () {
        if ($("#designation").val() == 7) {
            $("#Designation_Others_row").css('display', 'block');
        } else {
            $("#Designation_Others_row").css('display', 'none');
        }
    });
</script>
<script>
    $(document).ready(function () {
        /* $("#EducationForm").validate({
         rules: {                            
         education_level:
         {
         required: true                                   
         },					
         education_field:
         {
         required: true
         },
         specialization_major:
         {
         required: true
         },
         employment_status:
         {
         required: true                                
         },	
         profession: 
         {
         required: true
         }
         },
         messages: {                              
         
         }
         }); */

        //*****************
        if ($("#education_level").val() == 11) {
            $("#edu_level_Others_row").css('display', 'block');
        } else {
            $("#edu_level_Others_row").css('display', 'none');
        }
        if ($("#education_field").val() == 21) {
            $("#edu_field_Others_row").css('display', 'block');
        } else {
            $("#edu_field_Others_row").css('display', 'none');
        }
        if ($("#employment_status").val() == "Others") {
            $("#employement_Others_row").css('display', 'block');
        } else {
            $("#employement_Others_row").css('display', 'none');
        }
        if ($("#profession").val() == 12) {
            $("#profession_Others_row").css('display', 'block');
        } else {
            $("#profession_Others_row").css('display', 'none');
        }
    });
</script>


<script>
//*****************************Others info hide show********************/
//*********apend education_level others info
    $("#education_level").on('change', function () {
        if ($("#education_level").val() == 11) {
            $("#edu_level_Others_row").css('display', 'block');
        } else {
            $("#edu_level_Others_row").css('display', 'none');
        }
    });
//*********apend education_field others info
    $("#education_field").on('change', function () {
        if ($("#education_field").val() == 21) {
            $("#edu_field_Others_row").css('display', 'block');
        } else {
            $("#edu_field_Others_row").css('display', 'none');
        }
    });
//*********apend employment_status  others info
    $("#employment_status").on('change', function () {
        if ($("#employment_status").val() == "Others") {
            $("#employement_Others_row").css('display', 'block');
        } else {
            $("#employement_Others_row").css('display', 'none');
        }
    });
//*********apend profession  others info
    $("#profession").on('change', function () {
        if ($("#profession").val() == 12) {
            $("#profession_Others_row").css('display', 'block');
        } else {
            $("#profession_Others_row").css('display', 'none');
        }
    });
</script>













