

<style>

.preview_img{width:150px; margin:auto 10px 10px 0px !important; float:left;}
.avatar-view img{height:110px!important;}
.table {float:left !important;}
.show_allocation_detail{margin-bottom:0px; cursor:pointer;color:#428bca;width:100%;}

</style>
  

<div id="crop-vehicle" style="width:140px; margin:auto;"> 
                  
                  <!-- Current avatar -->
                  
                  <div data-original-title="Vehicle Picture" class="avatar-view userimg_byratio" title=""> <img src="<?php echo $this->basePath()?>/images/holi.png" id="vehicle_pic_update" alt="Avatar" style="height:140px"> </div>
                  
                  <!-- Cropping modal -->
                 <!--  <div class="modal fade" id="avatar-modal" tabindex="-1" role="dialog" aria-labelledby="avatar-modal-label" aria-hidden="true">
                    <div class="modal-dialog modal-lg">
                      <div class="modal-content">
                        
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">×</button>
                            <h4 class="modal-title" id="avatar-modal-label">Vehicle Picture</h4>
                          </div>
                         <div class="modal-body">
                         	<div id="showloader" style="position:absolute;top:30%;left:0;width:100%;min-height:300px;display:none;z-index:1000;">
                         		<center><img src="<?=$this->basepath()?>/img/loadingmap2.gif"></center>
                         	</div>
                             <form class="avatar-form" id="cropform" method="post" action="#" enctype="multipart/form-data" onsubmit="return cropimage('<?=$this->serverurl().$this->url()."account/cropimage"?>',cropimageresults);">
 
<h4>Image:</h4>
<input type="file" name="file" id="file"> 
<div class="banner"><img class="cropper" id="showimage" src="<?=$this->basepath()?>/img/default_user.png"></div>
 
 
 <input name="field_name" id="field_name" type="hidden">
 
 <input name="table_name" id="table_name" type="hidden">

<input type="hidden" class="form-control" id="dataX1" placeholder="x1" name="x1">
 
<input type="hidden" class="form-control" id="dataY1" placeholder="y1" name="y1">
 
<input type="hidden" class="form-control" id="dataX2" placeholder="x2" name="x2">
 
<input type="hidden" class="form-control" id="dataY2" placeholder="y2" name="y2">
 
<input type="hidden" class="form-control" id="dataWidth" placeholder="width" name="width">
 
<input type="hidden" class="form-control" id="dataHeight" placeholder="height" name="height">

<input type="hidden" class="form-control" id="cropenabled" name="cropenabled" value="Enable">


<input type="hidden"     id="actualimage" name="actualimage">
 <button id="cropper-enable" type="button" class="btn btn-success croptrigger">Enable</button>
<button id="cropper-disable" type="button" class="btn btn-danger croptrigger">Disable</button>
 </div>
<div class="modal-footer">
                            <button class="btn btn-default" type="button" data-dismiss="modal">Close</button>
                            <input class="btn btn-primary avatar-save" type="submit" value="Save">
                          </div>
                    </form>
                      </div>
                    </div>
                  </div>
                  
                   -->
                </div>

<div class="col-sm-3 col-sm-3-new width20per">
<?php echo $this->partial('layout/sidebar-user') ?>
</div>


<div class="col-sm-9 width80per">
<?php include('main_info.phtml'); ?>
<div class="col-sm-6" style="margin-top:22px; float:right; text-align:right;">
<p style="text-align:right;">Connected  9 Months ago</p>
</div>

<div class="clearfix"></div>
<?php include('menu.phtml'); ?>  
  <div class="tab-content">
      <div><button>Add Family Member</button></div>
     
  </div>
</div>
 
