<ul class="nav nav-pills">
        <li><a href="<?php echo $this->url('profile', array('action'=>'about'))?>"><?php echo $this->translate('About') ?></a></li> 
        <li class="active"><a href="<?php echo $this->url('profile', array('action'=>'personal-profile')) ?>"><?php echo $this->translate('Personal Profile') ?></a></li>
        <li><a href="<?php echo $this->url('profile', array('action'=>'education-and-career')) ?>"><?php echo $this->translate('Education & Career') ?></a></li>  
        <li><a href="<?php echo $this->url('profile', array('action'=>'family-detail')) ?>"><?php echo $this->translate('Family Details') ?></a></li>
        <li><a href="<?php echo $this->url('profile', array('action'=>'post')) ?>"><?php echo $this->translate('Post') ?></a></li>
        <li><a href="<?php echo $this->url('profile', array('action'=>'mygallery')) ?>"><?php echo $this->translate('Gallery') ?></a></li>
    </ul>