<style>
.loader2 {
	position: fixed;
	top: 250;
	background: none;
	z-index: 1000000;
	margin: auto;
	margin-left: 40%;
}
.loder {
    background: #378d18 none repeat scroll 0 0;
    border-radius: 10px;
    height: 10px;
    margin-top: 5px;
    width: 10px;
}

.preview_img{width:150px; margin:auto 10px 10px 0px !important; float:left;}
.avatar-view img{height:110px !important;}
.table {float:left!important}
.show_allocation_detail{margin-bottom:0px; cursor:pointer;color:#428bca;width:100%;}

</style>

<div class="col-sm-3 col-sm-3-new width20per">
<?php echo $this->partial('layout/sidebar-user') ?>
</div>


<div class="col-sm-9 width80per">
<?php include('main_info.phtml'); ?>
<div class="col-sm-6" style="margin-top:22px; float:right; text-align:right;">
<p style="text-align:right;">Connected  9 Months ago</p>
</div>

<div class="clearfix"></div>
<ul class="nav nav-pills">
<li><a href="<?php echo $this->basePath()?>/account/editabout"><?php echo $this->translate('About') ?></a></li> 
<li><a href="<?php echo $this->basePath()?>/account/memberbasic"><?php echo $this->translate('Personal Details') ?></a></li>
<li><a href="<?php echo $this->basePath()?>/account/editeducation"><?php echo $this->translate('Education') ?></a></li>  
<li><a href="<?php echo $this->basePath()?>/account/editcareer"><?php echo $this->translate('Profession') ?></a></li>
<li><a href="<?php echo $this->basePath()?>/account/editfamily"><?php echo $this->translate('Family Details') ?></a></li>
<!--<li><a href="<?php echo $this->basePath()?>/account/editmatrimoni"><?php echo $this->translate('Marital Details') ?></a></li>-->

<li><a href="<?php echo $this->basePath()?>/account/post"><?php echo $this->translate('Post') ?></a></li>
<li class="active"><a href="#"><?php echo $this->translate('Gallery') ?></a></li>
  </ul>
 
  
  
  
  <div class="tab-content" id="links"> 
    

    <div id="crop-vehicle" style="width:140px; margin:auto;"> 
                  
                  <!-- Current avatar -->
                  
                  <div data-original-title="Vehicle Picture" class="avatar-view userimg_byratio" title=""> <img src="<?php echo $this->basePath()?>/images/holi.png" id="vehicle_pic_update" alt="Avatar" style="height:140px"> </div>
                  
                  <!-- Cropping modal -->
                  <div class="modal fade" id="avatar-modal" tabindex="-1" role="dialog" aria-labelledby="avatar-modal-label" aria-hidden="true">
                    <div class="modal-dialog modal-lg">
                      <div class="modal-content">
                        
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">×</button>
                            <h4 class="modal-title" id="avatar-modal-label">Vehicle Picture</h4>
                          </div>
                         <div class="modal-body">
                          <div id="showloader" style="position:absolute;top:30%;left:0;width:100%;min-height:300px;display:none;z-index:1000;">
                            <center><img src="<?=$this->basepath()?>/img/loadingmap2.gif"></center>
                          </div>
                              <form class="avatar-form" id="uploadImgForm" method="post" action="#" enctype="multipart/form-data" >
 
<h4>Image:</h4>
<input type="file" name="file_upload" id="file"> 
<div class="banner"><img class="cropper" id="showimage" src="<?=$this->basepath()?>/img/default_user.png"></div>
 
 
 <input name="field_name" id="field_name" type="hidden">
 
 <input name="table_name" id="table_name" type="hidden">

<input type="hidden" class="form-control" id="dataX1" placeholder="x1" name="x1">
 
<input type="hidden" class="form-control" id="dataY1" placeholder="y1" name="y1">
 
<input type="hidden" class="form-control" id="dataX2" placeholder="x2" name="x2">
 
<input type="hidden" class="form-control" id="dataY2" placeholder="y2" name="y2">
 
<input type="hidden" class="form-control" id="dataWidth" placeholder="width" name="width">
 
<input type="hidden" class="form-control" id="dataHeight" placeholder="height" name="height">

<input type="hidden" class="form-control" id="cropenabled" name="cropenabled" value="Enable">


<input type="hidden"     id="actualimage" name="actualimage">
 <button id="cropper-enable" type="button" class="btn btn-success croptrigger">Enable</button>
<button id="cropper-disable" type="button" class="btn btn-danger croptrigger">Disable</button>
 
<div class="modal-footer">
                            <button class="btn btn-default" type="button" data-dismiss="modal">Close</button>
                            <input class="btn btn-primary avatar-save" type="submit" value="Save">
                          </div>
                    </form>
                    </div>
                      </div>
                    </div>
                  </div>
                  <!-- /.modal --> 
                  
                  <!-- Loading state --> 
                  
                </div>

                <a href="#" data-toggle="modal" data-target="#avatar-modal" onclick="showcropbox('image_path','tbl_user_gallery')" style="font-weight:bold;padding-left:33.5%;font-size:18px;color:cornflowerblue;">Upload More Photos to Gallery</a> 

        
	    
    
    <div class="gallery" id="gallery_images"> 
     
      <!--<div class="col-xs-4">
      <div class="col-xs-12"><a href="<?php //echo $this->basePath('gallery/large/gallery.jpg') ?>" title="" data-gallery=""><img src="<?php //echo $this->basePath('gallery/thumb/gallery.jpg') ?>" class="img-responsive" /><div class="img-title">Category 1</div></a></div>
      </div>--> 
      
       <div class="col-sm-6">
       	<div class="col-sm-12" style="padding:0 !important;">  <h3>Personal Photos</h3></div>
  		<div class="col-sm-8" style="padding:0 !important;"><a href="#" title="" ><img src="<?=$this->basePath().$Pphotos[0]?>" style="width:100%;height:140px;display:block;" class="moreimgthamb" /></a></div>
        <div class="col-sm-4" style="padding:0 !important;"><a href="#" title="" ><img src="<?=$this->basePath().$Pphotos[1]?>" class="moreimgthamb" style="width:100%;height:140px;display:block;" /></a></div>
        <div class="col-sm-3"><a href="#" title="" ><img src="<?=$this->basePath().$Pphotos[2]?>" class="moreimgthamb" style="width:100%;height:80px;display:block;" /></a></div>
        <div class="col-sm-3"><a href="#" title="" ><img src="<?=$this->basePath().$Pphotos[3]?>" class="moreimgthamb" style="width:100%;height:80px;display:block;" /></a></div>
        <div class="col-sm-3"><a href="#" title="" ><img src="<?=$this->basePath().$Pphotos[4]?>" class="moreimgthamb" style="width:100%;height:80px;display:block;" /></a></div>
        <div class="col-sm-3" id="more" onclick="showallimages('Personal','<?=$this->serverUrl().$this->url()."account/showallimages"?>',showallimagesresults)"><a href="#" title=""><img src="<?=$this->basePath().$Pphotos[5]?>" class="moreimgthamb" style="width:100%;height:80px;display:block;" /></a>
        <div class="moreimage" style="cursor:pointer;"> + </div>
        </div>
  </div>
  
  
  <div class="col-sm-6">
  <div class="col-sm-12" style="padding:0 !important;">  <h3>Family Photos</h3></div>
  		<div class="col-sm-8" style="padding:0 !important;"><a href="#" title="" data-gallery=""><img src="<?=$this->basePath().$F_photos[0]?>" class="moreimgthamb" style="width:100%;height:140px;display:block;" /></a></div>
        <div class="col-sm-4" style="padding:0 !important;"><a href="#" title="" data-gallery=""><img src="<?=$this->basePath().$F_photos[1]?>" class="moreimgthamb" style="width:100%;height:140px;display:block;" /></a></div>
        <div class="col-sm-3"><a href="#" title="" data-gallery=""><img src="<?=$this->basePath().$F_photos[2]?>" class="moreimgthamb" style="width:100%;height:80px;display:block;" /></a></div>
        <div class="col-sm-3"><a href="#" title="" data-gallery=""><img src="<?=$this->basePath().$F_photos[3]?>" class="moreimgthamb" style="width:100%;height:80px;display:block;" /></a></div>
        <div class="col-sm-3"><a href="#" title="" data-gallery=""><img src="<?=$this->basePath().$F_photos[4]?>" class="moreimgthamb" style="width:100%;height:80px;display:block;" /></a></div>
        <div class="col-sm-3 " id="fmore" onclick="showallimages('Family','<?=$this->serverUrl().$this->url()."account/showallimages"?>',showallimagesresults)"><a href="#" title="" data-gallery=""><img src="<?=$this->basePath().$F_photos[5]?>" class="moreimgthamb" style="width:100%;height:80px;display:block;" /></a>
        <div class="moreimage" style="cursor:pointer;"> + </div>
        </div>
  		
  </div>
          
        <div class="col-sm-12 userimg" id="showallimages" style="border:1px solid #ccc; margin-top:20px; padding:5px !important; display:none;">
  	<!-- <div class="col-sm-3"><img src="<?=$this->basePath()?>/gallery/thumb/img4.jpg" class="moreimgthambdeleat imghover"/>
    <div class="deleteimg"> 
    	<input type="checkbox" />
    </div>
    </div>
    
    <div class="col-sm-3"><img src="<?=$this->basePath()?>/gallery/thumb/img5.jpg" class="moreimgthambdeleat"/></div>
    
    <div class="col-sm-3"><img src="<?=$this->basePath()?>/gallery/thumb/slide1.jpg" class="moreimgthambdeleat"/></div>
    
    <div class="col-sm-3"><img src="<?=$this->basePath()?>/gallery/thumb/matrimonial-deepika.jpg" class="moreimgthambdeleat"/></div> -->
  
        </div>  
          
       <!--  <div class="col-sm-12 familyimg" style="border:1px solid #ccc; margin-top:20px; padding:5px !important; display:none;">
  	<div class="col-sm-3"><img src="<?=$this->basePath()?>/gallery/thumb/img4.jpg" class="moreimgthambdeleat"/></div>
    
    <div class="col-sm-3"><img src="<?=$this->basePath()?>/gallery/thumb/img5.jpg" class="moreimgthambdeleat"/></div>
    
    <div class="col-sm-3"><img src="<?=$this->basePath()?>/gallery/thumb/slide1.jpg" class="moreimgthambdeleat"/></div>
    
    <div class="col-sm-3"><img src="<?=$this->basePath()?>/gallery/thumb/matrimonial-deepika.jpg" class="moreimgthambdeleat"/></div>
  
  </div> -->
          
          
    </div> 
  
 
  
 </div>
</div>
<!-- ************************The Bootstrap modal starts************** -->
			<div class="modal fade" id="myGalleryModal">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <form id="uploadImgForm" enctype="multipart/form-data" role="form" action="" method="POST">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                                <h4 class="modal-title">Gallery Photo</h4>
                            </div>
                            <div class="modal-body">
									<div id="targetLayer" style="font-weight:bold;width:100%;height:auto;text-align:center;"></div>
									<label>Select Image For<span style="color:red;">*</span></label>
									<select name="img_relation" id="img_relation" class="form-control" required>
										<option value="">Select Relation</option>
										<option value="user">Myself</option>
										<option value="father">Father</option>
										<option value="mother">Mother</option>
									</select>
									<br/>
									<label>Browse Image<span style="color:red;">*</span></label>
									<input type="file" name="file_upload" id="file_upload" required />
									<br/>
                            </div>
                            <div class="modal-footer">
                                <!--<button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>-->
                                <button  name="upload_IMG"  id="upload_IMG" type="submit" class="btn" style="width:80px;">Upload</button>
                            </div>
                        </form>
                    </div>
                    
                    </div>
                
                
            </div>
            
          
            
            
            
            
<!-- The Bootstrap modal ends -->

<!-- The Bootstrap Image Gallery lightbox, should be a child element of the document body -->
<div id="blueimp-gallery" class="blueimp-gallery">
    <!-- The container for the modal slides -->
    <div class="slides"></div>
    <!-- Controls for the borderless lightbox -->
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
    <!-- The modal dialog, which will be used to wrap the lightbox content -->
    <div class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" aria-hidden="true">&times;</button>
                    <h4 class="modal-title"></h4>
                </div>
                <div class="modal-body next"></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left prev">
                        <i class="glyphicon glyphicon-chevron-left"></i>
                        Previous
                    </button>
                    <button type="button" class="btn btn-primary next">
                        Next
                        <i class="glyphicon glyphicon-chevron-right"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
            $(function() {
                var $cropper = $(".cropper"),
                    $dataX1 = $("#dataX1"),
                    $dataY1 = $("#dataY1"),
                    $dataX2 = $("#dataX2"),
                    $dataY2 = $("#dataY2"),
                    $dataHeight = $("#dataHeight"),
                    $dataWidth = $("#dataWidth"),
                    cropper;

                $cropper.cropper({
                    aspectRatio: 16 / 9,
                    preview: ".extra-preview",
                    done: function(data) {
                        $dataX1.val(data.x1);
                        $dataY1.val(data.y1);
                        $dataX2.val(data.x2);
                        $dataY2.val(data.y2);
                        $dataHeight.val(data.height);
                        $dataWidth.val(data.width);
                    }
                });

                cropper = $cropper.data("cropper");

                $("#cropper-enable").click(function() {
                    $cropper.cropper("enable");
                });


                $("#cropper-disable").click(function() {
                    cropper.disable();
                });

                 $(".croptrigger").click(function(){
                  var x = $(this).text();
                  $("#cropenabled").val(x);
                 });

                $('input[type=file]').change(function (event) {
                    var tmppath = URL.createObjectURL(event.target.files[0]);
                    $("#showimage").attr("src",tmppath);
                    $("#actualimage").val(tmppath);

                // console.log(tmppath);
                });

            })
        </script>
<script type="text/javascript">
	$(document).ready(function (e){
		$("#uploadImgForm").on('submit',(function(e){
			e.preventDefault();
			$.ajax({
			url: '<?php echo $this->basePath().'/account/AjaxImgUploadGallery'?>',
			type: "POST",
			data:  new FormData(this),
			contentType: false,
			cache: false,
			processData:false,
			success: function(response){
				   //        if(response.Status != "false") {
							// $('#targetLayer').removeClass('alert alert-danger');
       //                      $('#targetLayer').addClass('alert alert-success').text(response.message);
							// setTimeout(function(){
							//  window.location.href = "<?php echo $this->basePath().'/account/mygallery'?>";
							// }, 1000);
							//  $('#gallery_images').empty();
							// jQuery.each(response.gallery_data , function(index, value){
							// 		  $('#gallery_images').append("<div class='col-xs-4'><div class='col-xs-12'><a href='<?php echo ROOT_PATH ?>'+value['image_path']+ title='' data-gallery=''><img src='<?php echo ROOT_PATH ?>'+value['image_path']+ class='img-responsive' /><div class='img-title'>Category 1</div></a></div></div>"); 
							// 	}); 
							// } else {
							// 	$('#targetLayer').addClass('alert alert-danger').text(response.message);
							// }
              if(response.Status == 0){
                alert(response.message);
              }
              setTimeout(function(){
                              $('#myModal').modal('hide');
                        $('#avatar-modal1').modal('hide');
                        $('#avatar-modal').modal('hide');
                              $('#chooseGallery').modal('hide');
                            }, 2000);
              // alert(response);
			},
			error: function(error){
				alert(error);
			} 	        
			});
		}));
		
	});
</script>

<script>
$(document).ready(function(){
   //  $("#more").click(function(){
   //      $(".userimg").show();
		 // $(".familyimg").hide();
   //  });
   //  $("#fmore").click(function(){
   //       $(".userimg").hide();
		 // $(".familyimg").show();
   //  });
	
	// $("#showallimages :img").mouseover(function(){
 //    $(this).next().show();
 //         // $(".deleteimg").show();
	// 	// $(".familyimg").show();
 //    });
	
	$(".imghover").mouseout(function(){
         $(".deleteimg").hide();
		// $(".familyimg").show();
    });
	
	$(".deleteimg").mouseover(function(){
         $(".deleteimg").show();
		// $(".familyimg").show();
    });
});
</script>
 <!--<div class="col-xs-4">
		  <div class="col-xs-12"><a href="<?php //echo $this->basePath('gallery/large/gallery.jpg') ?>" title="" data-gallery=""><img src="<?php //echo $this->basePath('gallery/thumb/gallery.jpg') ?>" class="img-responsive" /><div class="img-title">Category 1</div></a></div>
		  </div>-->	






