  <?php foreach($this->receivedMember as $receivedMember){
     foreach ($this->memInfo as $memInfos){
         if($memInfos['received']==$receivedMember->user_id){
             $meid=$memInfos['id'];
         }
     }
                    ?>
                <div id="pin_interest" style="display: block;margin-top: 20px;">    
                    <div class="pinned_wrap">
                        <div class="pinned_shadow">

                            <div class="pinned_profile_green">
                               

                                <div id="pin_interest_profile" class="pos_rel">

                                    <div class="pinned_profile_wrap" rel="vSH87477335">
                                        <?php if(!empty($receivedMember['image_path'])){ ?>
                                        <div class="pinned_pic">
                                            <span class="thumb60">
                                                <a href="#" target=""><img src="<?php echo $this->basePath('/uploads/').$receivedMember['image_path']?>" border="0" height="60" width="60"></a>

                                            </span>
                                        </div>
                                        <?php } ?>
                                        <div class="pinned_info">
                                            <a href="#" class="pinned_pro_name" target="_blank"><?php echo $receivedMember['full_name']?></a>
                                            
                                        </div>
                                        <div class="clearfix"></div>
                                        <div class="personal_msg" style="border-top: none">
                                            <button style="margin-right: 20px;" onclick="acceptInterest(<?php echo $meid;?>, <?php echo $receivedMember->user_id; ?>, 'accept')">Accept</button>&nbsp;<button>Decline</button>
                                        </div>

                                    </div>                   
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <?php } ?>

<script>
    function acceptInterest(id, uid, type) {
        $.ajax({
            url: '<?php echo $this->url('profile', array('action'=>'interestaccepted'))?>',
            data: {
                id:id, uid: uid, type: type
            },
            error: function (request, status, error) {
                console.log(status);
            },
            success: function (data) {
                console.log(data);
            },
            type: 'POST'
        });
    }
</script>