<div class="row">
          <div class="col-xs-12"> 
            <!-- PAGE CONTENT BEGINS -->
          
            <div class="row">
              <div class="col-xs-12">
                <h3>User Type Master</h3>
                <div class="filter">
                <div class="panel-body" style="padding:0 !important;">
                  <div class="col-lg-6">View Records>></div>
                  </div>
                </div>
                <div class="portlet-body">
                  <form id="bookingFilter">
                    <div id="myTabContent" class="tab-content">
                      <div class="tab-pane fade active in" id="home">
                        <div class="col-sm-col-sm-offset-1" style="margin: 10px auto 0px !important;padding: 0 10px;">
                          <div class="row">
                                                <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">User Type Name</label>
                                                  <div class="col-sm-2 ">
                                                     <input id="Classic Dance" class=" form-control inputchange" placeholder="" type="text">                                    
                                                  </div>
                                                 
                              <div class="col-sm-1 ">
                                                     <input class="btn btn-red defaultbtnsearch searchBooking"  type="submit" name="submit" value="Search">
                                                     </div>
                                                     <div class="col-sm-1 ">
                                                     <!--<input class="btn btn-red defaultbtnsearch"  type="submit" name="submit" value="Add">-->
                                                     <a href="#" id="showaddform" class="btn btn-red defaultbtnsearch searchBooking">
                         							 Add</a> </div>
                                                   
                                                 </div>
                                             </div>
                          

                          
                          
                        </div>
                      </div>

                    </div>
                  </form>
   
                </div>
                
                 
                  <div class="filter">
                  <div class="panel-body" style="padding:0 !important; cursor:pointer;">
                  <div class="col-lg-6">Add Update Records>>
                  </div>
  
                  </div>
   
                </div>
                
                <div id="addForm" class="tab-content dontshow">
                     
          <div id="myTabContent" class="">
            
            
            <div class="tab-pane fade active in" id="driver_tab">
              <div class="container col-sm-col-sm-offset-1" style="margin: 10px auto 0px !important;padding: 0 10px;">
                
                <div class="row">
                                                <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            User Type Name
                           </label>
                                                  <div class="col-sm-2">
                                                     <input type="text" class="form-control" />                                    
                                                  </div>
                                                 
                            <label id="flight_nos" class="col-sm-1 control-label labelalign ">
                            Status
                           </label>
                                                  <div class="col-sm-2">
                                                     <input type="text" class="form-control" />                                      
                                                  </div>
                                                   <div class="col-sm-3">
                                                    <input type="submit" class="btn btn-red " value="Add" />                                 
                                                  </div>
                                                  
                                                 </div>
                                             </div>
                                            
                                             
              </div>
            </div>
          </div>
       
                                                  </div>
                
                    <div class="clearfix"></div>
                  
                <div class="col-lg-6" style="background-color:#FFF;">
                  
                  <div class="col-lg-4"><div class="radio">
                                                <label>
                                                    <input type="radio" checked="" value="option1" id="optionsRadios1" name="optionsRadios"><strong>Active</strong>
                                                </label>
                                                <br>
 
                                            </div>
                  
                  
                  
                  
                  </div>
                  
                  
                   <div class="col-lg-4"><div class="radio">
                                                <label>
                                                    <input type="radio" checked="" value="option1" id="optionsRadios1" name="optionsRadios"><strong>In-Active</strong>
                                                </label>
                                                
                                              
                                            </div>
                  
                  
                  
                  
                  </div>
                  </div>
                <div class="col-md-12">
                    <div class="table-responsive">
                      <table id="dynamic-table" class="table table-striped table-bordered table-hover">
                    <thead>
                      <tr>
                          <th><input type="checkbox" value="" id="checkAll" onclick="checkall(this.id)" > </th>
                        <th>SR.No.</th>
                        <th>User Type Name</th>
                        <th class="hidden-480">Modified Date</th>
                        <th class="hidden-480">Created Date</th>
                        <th class="hidden-480">Status</th>
                        <th class="hidden-480">Modified By</th>
                        <th><b>Actions</b></th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php 
                      $i =1;
                      foreach ($usertypes as $usertype) {
                      
                      ?>
                      <tr>
                         
                        <td><input type="checkbox" value="<?=$usertype->id?>" class="checkme" name="checkme[]"> </td>
                        <td><?= $i?></td>                       
                        <td><?= $usertype->user_type?></td>                       
                        <td class="hidden-480"><?= date('l d-m-y',strtotime($usertype->created_date))?></td>
                        <td class="hidden-480"><?= date('l d-m-y',strtotime($usertype->modified_date))?></td>
                        <td class="hidden-480">
						<!--<?php echo ($usertype->IsActive==1)? 'Active': '<span class="label label-sm label-warning">In-Active</span>'; ?>-->
                        
                        <?php $status = ($usertype->IsActive==1)? 'Active': 'In-Active';
                        $statuscolor = ($usertype->IsActive==1)? 'activestatus': 'de-activestatus';
                         ?>
                          <div name="ChangeStatus" id="changestatus<?=$i;?>" onclick="changestatusquick(<?=$usertype->id?>,<?= ($usertype->IsActive==0)?0:1; ?>,'<?= $this->serverUrl().$this->url().'/usertype/changestatus';?>',changstatusresult);" class="<?=$statuscolor?>">
                        </div>
                        </td>
                        <td class="hidden-480"><?php echo ($usertype->modified_by==1)? 'Admin': 'NotByAdmin'; ?></td>
                        <td><div class="hidden-sm hidden-xs action-buttons"> <a class="blue" href="<?php echo $this->url('admin',array('controller'=>'master','action'=>'viewusertype','id'=>$usertype->id)); ?>"> <i class="ace-icon fa fa-search-plus bigger-130"></i> </a> <a class="green" href="<?php echo $this->url('admin',array('controller'=>'master','action'=>'editusertype','id'=>$usertype->id)); ?>" > <i class="ace-icon fa fa-pencil bigger-130"></i> </a> <a class="red" href="<?php echo $this->url('admin',array('controller'=>'master','action'=>'deleteusertype','id'=>$usertype->id)); ?>" onclick="return confirm('are you sure you want to delete');"> <i class="ace-icon fa fa-trash-o bigger-130"></i> </a> </div>
                          </td>
                      </tr>
                      <?php 
                      $i++;
                    }
                      ?>
                    </tbody>
                  </table>
                      
                      
                      
                      
                    </div>
                 </div>
              </div>
              
              
              
              
              
              <div class="col-sm-12"> 
                
                <!-- /.widget-box -->
                <!--<div  style="margin-top:20px;"> <a href="#" class="btn btn-red defaultbtnsearch searchBooking"><i class="fa fa-search" id="search_me" style="color:#fff; margin:5px"></i>Refresh</a> </div>-->
              </div>
            </div>
            <!-- /.col --> 
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Modal Header</h4>
      </div>
      <div class="modal-body">
            <?php 

        // print_r($countries);

        ?>         
      </div>
      <div class="modal-footer">
        <button type="button"data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
            
            <!-- /.row -->
            
            <div class="hr hr-18 dotted hr-double"></div>
            <div class="row">
              <div class="col-xs-12">
                
                <div> 
         
      </div>
      <!-- /.page-content --> 
    </div>
  </div>
  <!-- /.main-content -->
  
     
  <a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse"> <i class="ace-icon fa fa-angle-double-up icon-only bigger-110"></i> </a> </div>
<!-- /.main-container --> 

<!-- basic scripts --> 

<!--[if !IE]> -->