<div class="row">
          <div class="col-xs-12"> 
            <!-- PAGE CONTENT BEGINS -->
            <div class="alert alert-block alert-success">
              <button type="button" class="close" data-dismiss="alert"> <i class="ace-icon fa fa-times"></i> </button>
              <i class="ace-icon fa fa-check green"></i>Add Education Levels Master</strong>, </div>
            <div class="row">
              <div class="space-6"></div>
              <div class="vspace-12-sm"></div>
            </div>
            <div class="row">
              <div class="col-xs-12">
                <h3  >Add Education Levels Master</h3>
                <div class="filter">
                 <div class="panel-body" style="padding:0 !important;">
                  <div class="col-lg-6">View Records>></div>
                  </div>
                </div>
                <div class="portlet-body">
                  <form id="bookingFilter">
                    <div id="myTabContent" class="tab-content">
                      <div class="tab-pane fade active in" id="home">
                        <div class="col-sm-col-sm-offset-1" style="margin: 10px auto 0px !important;padding: 0 10px;">
                          <div class="row">
                                                <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">Country</label>
                                                  <div class="col-sm-3 ">
                                                     <input id="Classic Dance" class=" form-control inputchange" placeholder="India" type="text">                                    
                                                  </div>
                                                 
                            <label id="point_airport" class="col-sm-2 control-label labelalign ">*Mandatory Fileds
</label>
                                                   <div class="col-sm-3">
                                                     <input id="Karol Bagh" class=" form-control inputchange" placeholder="" type="text"> 
                                                  </div>
                                                 </div>
                                             </div>
                          

                          
                          <div class="row">
                            <div class="form-group clearfix margintopbottom20">
                              <div class="col-sm-4 pull-right"> <a href="#" class="btn btn-red defaultbtnsearch searchBooking"><i class="fa fa-search" id="search_me" style="color:#fff; margin:5px"></i>Search</a> </div>
                            </div>
                          </div>
                        </div>
                      </div>

                    </div>
                  </form>
   
                </div>
                
                 
                  <div class="filter" id="showaddform">
                   <div class="panel-body" style="padding:0 !important; cursor:pointer;">
                  <div class="col-lg-6">Add Update Records>>
                  </div>
  
                  </div>
   
                </div>
                
                <div id="addForm" class="tab-content dontshow">
                      <?php 

                $form=$this->form; 
                $form->prepare();


        $form->setAttribute('action',$this->url('admin',array('controller'=>'master','action'=>'addedulevel')));
        $form->setAttribute('method','post');

        echo $this->form()->openTag($form);
// echo $this->formCollection($form);
                ?>
          <div id="myTabContent" class="tab-content">
            
            
            <div class="tab-pane fade active in" id="driver_tab">
              <div class="container col-sm-col-sm-offset-1" style="margin: 10px auto 0px !important;padding: 0 10px;">
                
                <div class="row">
                                                <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate($form->get('education_level')->getLabel()) ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo $this->formHidden($form->get('id'));
                                                     echo $this->formElement($form->get('education_level'));
                                                     ?>                                    
                                                  </div>
                                                   <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate($form->get('IsActive')->getLabel()) ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo $this->formElement($form->get('IsActive'));
                                                     ?>                                    
                                                  </div>
                         
                                                 </div>
                                             </div>
                                             <div class="row">
                                                <div class="form-group clearfix margintopbottom20">
                          
                                                 </div>
                                             </div>
                                             <div class="row">
                                                <div class="form-group clearfix margintopbottom20">
                                                <div class="col-sm-3">
                                                     <?php 
                                                     echo $this->formRow($form->get('submit'));
                                                     ?>                                    
                                                  </div>
                                             </div>
                                             </div>
              </div>
            </div>
          </div>
        <?php   
echo $this->form()->closeTag();

        ?>
                                                  </div>
                
                    <div class="clearfix"></div>
                  
                <div class="col-lg-6" style="background-color:#FFF;">
                  
                  <div class="col-lg-4"><div class="radio">
                                                <label>
                                                    <input type="radio" checked="" value="option1" id="optionsRadios1" name="optionsRadios"><strong>Active</strong>
                                                </label>
                                                <br>
 
                                            </div>
                  
                  
                  
                  
                  </div>
                  
                  
                   <div class="col-lg-4"><div class="radio">
                                                <label>
                                                    <input type="radio" checked="" value="option1" id="optionsRadios1" name="optionsRadios"><strong>In-Active</strong>
                                                </label>
                                                
                                              
                                            </div>
                  
                  
                  
                  
                  </div>
                  </div>
                  <div class="col-sm-12">

                  <div class="col-lg-2">
                    <div class="delete">
                      <button class="btn btn-red defaultbtnsearch searchBooking" onclick="delselected('<?= $this->serverUrl().$this->url().'/country/delmultiple';?>',delmultipleresp)">Delete Selected</button>                                              
                    </div>
                  </div> 
                  <div class="col-lg-2">
                    <div class="delete">
                      <button class="btn btn-red defaultbtnsearch searchBooking" onclick="statuschangeall('<?= $this->serverUrl().$this->url().'/country/statuschangeall';?>',statuschangeallresp,1)">Activate Selected</button>                                    
                    </div>
                  </div> <div class="col-lg-2">
                    <div class="delete">
                      <button class="btn btn-red defaultbtnsearch searchBooking" onclick="statuschangeall('<?= $this->serverUrl().$this->url().'/country/statuschangeall';?>',statuschangeallresp,0)">De-Activate Selected</button>                                    
                    </div>
                  </div>
                   
</div>
                  
                  
                  
                <div class="col-md-12">
                    <div class="table-responsive">
                      <table id="dynamic-table" class="table table-striped table-bordered table-hover">
                    <thead>
                      <tr>
                         
                        <th>SR.No.</th>
                        <th>Education Level Name</th>
                        <th class="hidden-480">Modified Date</th>
                        <th class="hidden-480">Created Date</th>
                        <th class="hidden-480">Status</th>
                        <th class="hidden-480">Modified By</th>
                        <th><b>Actions</b></th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php 
                      $i =1;
                      foreach ($educationlevels as $educationlevel) {
                      
                      ?>
                      <tr>
                         
                       
                        <td><?= $i?></td>                       
                        <td><?= $educationlevel->education_level?></td>                       
                        <td class="hidden-480"><?= date('l d-m-y',strtotime($educationlevel->created_date))?></td>
                        <td class="hidden-480"><?= date('l d-m-y',strtotime($educationlevel->modified_date))?></td>
                        <td class="hidden-480"><?php echo ($educationlevel->IsActive==1)? 'Active': '<span class="label label-sm label-warning">In-Active</span>'; ?></td>
                        <td class="hidden-480"><?php echo ($educationlevel->modified_by==1)? 'Admin': 'NotByAdmin'; ?></td>
                        <td><div class="hidden-sm hidden-xs action-buttons"> 
                       <!-- <a class="blue" href="<?php echo $this->url('admin',array('controller'=>'master','action'=>'viewedulevel','id'=>$educationlevel->id)); ?>"> 
                        <i class="ace-icon fa fa-search-plus bigger-130"></i> </a>--> 
                        
                         <a class="blue" style="cursor:pointer;" tar="indview<?=$i?>"> <i class="ace-icon fa fa-search-plus bigger-130"></i> </a>
                        
                        <a class="green" href="<?php echo $this->url('admin',array('controller'=>'master','action'=>'editedulevel','id'=>$educationlevel->id)); ?>" > 
                        <i class="ace-icon fa fa-pencil bigger-130"></i> </a> <a class="red" href="<?php echo $this->url('admin',array('controller'=>'master','action'=>'deleteedulevel','id'=>$educationlevel->id)); ?>" onclick="return confirm('are you sure you want to delete');"> 
                        <i class="ace-icon fa fa-trash-o bigger-130"></i> </a> </div>
                          </td>
                      </tr>
                      
                      <tr class="dontshow" id="indview<?=$i?>" aria-expanded="true">
                     
                	<td colspan="7">
                    <div aria-expanded="true" class="panel-body accordion-body packageDetails1 collapse in" id="accordion1">
               
                          <div class="tab-content" id="myTabContent">
        
              <div class="col-sm-col-sm-offset-1" style="margin: 10px auto 0px !important;padding: 0 10px;">
                <div class="row">
                   <div class="form-group clearfix margintopbottom20 col-sm-12">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Education Level Name'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     
                                                     echo $Info->education_level;
                                                     ?>                                    
                                                  </div>
                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Created Date'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo date('l d-m-Y',strtotime($Info->created_date));
                                                     ?>                                    
                                                  </div>
                           
                                                 </div>
                                             </div>
                                             <div class="row">
                                                <div class="form-group clearfix margintopbottom20 col-sm-12">
                        <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Modified By'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo ($Info->modified_by==1)?'Admin':'Not Available Now';
                                                     ?>                                    
                                                  </div>
                                                 
                            <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Status'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo ($Info->IsActive==1)? 'Active':'In-Active';
                                                     ?>                                    
                                                  </div>
                                                 </div>
                                             </div>

                                          <div class="row">
                                                <div class="form-group clearfix margintopbottom20 col-sm-12">
                          
                                                 
                            <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Modified Date'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo date('l d-m-Y',strtotime($Info->modified_date));
                                                     ?>                                    
                                                  </div>
                                                 </div>
                                             </div>  
                                             
              </div>
           
          </div>
      </div>
                    
                                             
                       </td>
                    </tr>
                      
                      <?php 
                      $i++;
                    }
                      ?>
                    </tbody>
                  </table>
                      
                      
                      
                      
                    </div>
                 </div>
              </div>
              
              
              
              
              
              <div class="col-sm-12"> 
                
                <!-- /.widget-box -->
                <!--<div  style="margin-top:20px;"> <a href="#" class="btn btn-red defaultbtnsearch searchBooking"><i class="fa fa-search" id="search_me" style="color:#fff; margin:5px"></i>Refresh</a> </div>-->
              </div>
            </div>
            <!-- /.col --> 
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Modal Header</h4>
      </div>
      <div class="modal-body">
            <?php 

        // print_r($countries);

        ?>         
      </div>
      <div class="modal-footer">
        <button type="button"data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
            
            <!-- /.row -->
            
            <div class="hr hr-18 dotted hr-double"></div>
            <div class="row">
              <div class="col-xs-12">
                
                <div> 
         
      </div>
      <!-- /.page-content --> 
    </div>
  </div>
  <!-- /.main-content -->
  
     
  <a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse"> <i class="ace-icon fa fa-angle-double-up icon-only bigger-110"></i> </a> </div>
<!-- /.main-container --> 

<!-- basic scripts --> 

<!--[if !IE]> -->