<style>
	.col-xs-3 {
   	 width: 20%;
}
.list-view ul li .col-xs-3 img{ border-radius:50%; width:60px; height:60px; margin:auto; overflow:hidden;}
.grid-view ul li{margin:0 4px 20px 4px;  font-size:12px; color:#636363; float:left; width:auto !important;}
.list-view ul li{margin:0 4px 20px 4px;  font-size:12px; color:#636363; float:left; width:15.5% !important;}
.list-view ul li {
    color: #636363;
    float: left;
    font-size: 12px;
    margin: 0 4px 20px;
    width: 15.5% !important;
}

.list-view ul li {
    border: none;
}

.list-view ul li .col-xs-3 .heithviue {
    color: #666666;
    display: block;
    font-size: 12px;
    font-weight: normal !important;
    margin: 0;
    padding: 3px 0;
    text-align: center;
}

.list-view ul li .col-xs-3 .btn {
    border: 0 none;
    border-radius: 3px;
    display: table;
    font-size: 12px;
    font-weight: normal;
    line-height: 1.1;
    margin: 0 auto;
    padding: 5px 10px;
}

.thumbnail > img, .thumbnail a > img {
    height: 79px;
    
}

</style>

<div class="col-sm-3 col-sm-3-new width20per">
<?php 
echo $this->partial('layout/sidebar-matrimonial') 
?>
</div>
<div class="showerrorbox">

</div>
<div class="col-sm-9 width80per">
<div class="row">
<div class="col-xs-9">
<!--<ul class="view-menu">
<li>Sort By :</li>
<li class="active"><a href="#">New Joining</a></li>
<li><a href="#">Executive Communinty</a></li>
<li><a href="#">Senior Citizen</a></li>             
</ul>-->
</div>
<div class="col-xs-3">
<ul class="prof-view pull-right">
<li><a href="#" id="grid"><span class="glyphicon glyphicon-th-list"></span><span class="sr-only">List View</span></a></li>
<li><a href="#" id="list"><span class="glyphicon glyphicon-th"></span><span class="sr-only">Grid View</span></a></li>
</ul>
</div>
</div>
<div class="clearfix"></div>
<div id="profile1">
<div class="commen-list gblist-view list-view">
<div style="width:100%; float:left;" id="brides">
<h2>Brides</h2>
	<ul >
		
		<li  style="display:none;">
			<div class="col-xs-2">
			<div class="profile-pic"><a href="<?php echo $this->basePath()?>/matrimonial/profile-view"><img src="images/groome.jpg" /></a></div>
			<p>Ranbir Rustagi</p>
			<p>26, 5.11”, Bhopal</p>
			<!--<a href="<?php echo $this->basePath()?>/matrimonial/profile-view" class="btn btn-default">more info</a>-->
            
            <a href="#"  class="btn btn-default" data-toggle="modal" data-target="#myModal">more info</a>
			</div>
			</li>
			
		<?php $i=1; if(count($this->BridesData)>0){
				foreach($BridesData as $BrdData){ ?>
					
                    
                    
                    <li class="matrimonialli">
						<div class="col-xs-3" align="center">
						<a class="thumbnail" href="#thumb" style="margin-bottom:0;"><img src="<?php if($BrdData->profile_photo !=''){
						echo $this->basePath().$BrdData->profile_photo;
						}else{
							echo $this->basePath().'/img/default_user.png';
						} ?>" class="img-responsive" width="78"/><!--<span><img src="<?php if($BrdData->profile_photo !=''){
						echo $this->basePath().$BrdData->profile_photo;
						}else{
							echo $this->basePath().'/img/default_user.png';
						} ?>" /></span>--></a>
                        <?php echo $BrdData->name_title_user." ".$BrdData->full_name ?>
						<!--<p> <a href="#"  class="btn btn-default clickme" atr="findme<?=$i?>" data-toggle="modal" data-target="#myModalimg" style="background:none !important; color:#eda344;">View Full Photo</a></p>--><div class="heithviue"><?php echo $BrdData->age.','.$BrdData->height; ?></div>
						<div class="heithviue" style="height:;"><?php echo $BrdData->city; ?></div>
						<div class="heithviue">
                        <a href="<?php echo $this->basePath()?>/matrimonial/profile-view?groom_id=<?php echo $BrdData->uid ?>" class="btn btn-default">more info</a>
                        <!--<a href="<?php echo $this->basePath()?>/matrimonial/profile-view?groom_id=<?php echo $BrdData->user_id ?>">Read More</a>--></div>
						</div>
						<div class="col-xs-9">
						<div class="col-xs-8">
                        <div class="col-xs-4">Name</div>
						<div class="col-xs-8">:  <?php echo $BrdData->name_title_user." ".$BrdData->full_name ?></div>
						<div class="col-xs-4">Age / Height</div>
						<div class="col-xs-8">: <?php echo $BrdData->age.','.$BrdData->height; ?></div>
						<div class="col-xs-4">Religion</div>
						<div class="col-xs-8">: <?php echo $BrdData->religion; ?></div>						
						<!-- <div class="col-xs-4">Community</div>
						<div class="col-xs-8">: <?php echo $BrdData->caste; ?></div> -->
						<div class="col-xs-4">Location</div>
						<div class="col-xs-8">: <?php echo $BrdData->city.'/'.$BrdData->state.','.$BrdData->country; ?></div>
						<div class="col-xs-4">Education</div>
						<div class="col-xs-8">: <?php echo $BrdData->education_level.'-'.$BrdData->education_field; ?></div>
						<div class="col-xs-4">Profession</div>
						<div class="col-xs-8">: <?php echo $BrdData->profession; ?></div>
						<div class="col-xs-12"> <?php echo substr($BrdData->about_yourself_partner_family,0,120); ?><a href="<?php echo $this->basePath()?>/matrimonial/profile-view?groom_id=<?php echo $BrdData->uid ?>">  Read more</a></div>
						</div>
						<div class="col-xs-4 col-xs-4-matri">
						<p class="text-right">(Profile created by Self)</p>
						<h3>Connect with her?</h3>
						<button class="btn btn-info btn-block">Yes</button>
						<button class="btn btn-success pull-left">May be</button>
						<button class="btn btn-danger pull-right">No</button>
						<div class="clearfix"></div>
						<p class="text-center"><a href="<?php echo $this->basePath()?>/matrimonial/profile-view?groom_id=<?php echo $BrdData->uid ?>">(View full Profile)</a></p>
						</div>
						</div>
				</li>
                    
                    
                    
				<?php 
				$i++;
				}
			}else{ ?>
					<span style="text-align:center;font-weight:bold;font-size:12px; padding-left:10px; color:cornflowerblue;">No Data available</span>
			<?php } ?>
	</ul>
<div class="clearfix"></div>
<a href="<?php echo $this->basePath()?>/matrimonial/list-view?search_for=Female" class="btn btn-default pull-right">View More</a>
</div>
<div class="clearfix"></div>
<div style="width:100%; float:left;" id="grooms">
<h2>Grooms</h2>
	<ul>	
			<li  style="display:none;">
			<div class="col-xs-2">
			<div class="profile-pic"><a href="<?php echo $this->basePath()?>/matrimonial/profile-view"><img src="images/groome.jpg" /></a></div>
			<p>Ranbir Rustagi</p>
			<p>26, 5.11”, Bhopal</p>
			<!--<a href="<?php echo $this->basePath()?>/matrimonial/profile-view" class="btn btn-default">more info</a>-->
            
            <a href="#"  class="btn btn-default" data-toggle="modal" data-target="#myModal">more info</a>
			</div>
			</li>
			
			<?php if(count($this->GroomData)>0){
				foreach($GroomData as $GrData){ ?>
					<!--<li>
					<div class="col-xs-2">
					<div class="profile-pic"><a href="<?php echo $this->basePath()?>/matrimonial/profile-view?groom_id=<?php echo $GrData->id ?>"><img src="<?php if($GrData->profile_photo !=''){
						echo $this->basePath().$GrData->profile_photo;
					}else{
						echo $this->basePath().'/img/default_user.png';
					} ?>" /></a></div>
					<p><?php echo $GrData->name_title_user.". ".$GrData->full_name ?></p>
					<p><?php echo $GrData->age.','.$GrData->height.','.$GrData->city; ?></p>
					<a href="<?php echo $this->basePath()?>/matrimonial/profile-view?groom_id=<?php echo $GrData->id ?>" class="btn btn-default">more info</a>
                    
                    
					</div>
					</li>-->
                    
                    <li class="matrimonialli">
						<div class="col-xs-3" align="center">
						<a class="thumbnail" href="#thumb" style="margin-bottom:0;"><img id="findme<?=$i?>" src="<?php if($GrData->profile_photo !=''){
						echo $this->basePath().$GrData->profile_photo;
						}else{
							echo $this->basePath().'/img/default_user.png';
						} ?>" class="img-responsive" width="78" /><!--<span><img id="findme<?=$i?>" src="<?php if($GrData->profile_photo !=''){
						echo $this->basePath().$GrData->profile_photo;
						}else{
							echo $this->basePath().'/img/default_user.png';
						} ?>" class="img-responsive"/></span>--></a>
                        <?php echo $GrData->name_title_user." ".$GrData->full_name ?>
						<!--<p><a href="#"  class="btn btn-default clickme" data-toggle="modal" atr="findme<?=$i?>" data-target="#myModalimg" style="background:none !important; color:#eda344;">View Full Photo</a></p>--><div class="heithviue"><?php echo $GrData->age.','.$GrData->height; ?></div>
						<div class="heithviue" style="height:;"><?php echo $GrData->city; ?></div>
						<div class="heithviue">
                        <a href="<?php echo $this->basePath()?>/matrimonial/profile-view?groom_id=<?php echo $GrData->id ?>" class="btn btn-default">more info</a>
                        <!--<a href="<?php echo $this->basePath()?>/matrimonial/profile-view?groom_id=<?php echo $GrData->user_id ?>">Read More</a>--></div>
						</div>
						<div class="col-xs-9">
						<div class="col-xs-8">
                        <div class="col-xs-4">Name</div>
						<div class="col-xs-8">:  <?php echo $GrData->name_title_user." ".$GrData->full_name ?></div>
						<div class="col-xs-4">Age / Height</div>
						<div class="col-xs-8">: <?php echo $GrData->age.','.$GrData->height; ?></div>
						<div class="col-xs-4">Religion</div>
						<div class="col-xs-8">: <?php echo $GrData->religion; ?></div>						
						<!-- <div class="col-xs-4">Community</div>
						<div class="col-xs-8">: <?php echo $GrData->caste; ?></div> -->
						<div class="col-xs-4">Location</div>
						<div class="col-xs-8">: <?php echo $GrData->city.'/'.$GrData->state.','.$GrData->country; ?></div>
						<div class="col-xs-4">Education</div>
						<div class="col-xs-8">: <?php echo $GrData->education_level.'-'.$GrData->education_field; ?></div>
						<div class="col-xs-4">Profession</div>
						<div class="col-xs-8">: <?php echo $GrData->profession; ?></div>
						<div class="col-xs-12"> <?php echo substr($GrData->about_yourself_partner_family,0,120); ?><a href="<?php echo $this->basePath()?>/matrimonial/profile-view?groom_id=<?php echo $GrData->uid ?>">  Read more</a></div>
						</div>
						<div class="col-xs-4 col-xs-4-matri">
						<p class="text-right">(Profile created by Self)</p>
						<h3>Connect with her?</h3>
						<button class="btn btn-info btn-block">Yes</button>
						<button class="btn btn-success pull-left">May be</button>
						<button class="btn btn-danger pull-right">No</button>
						<div class="clearfix"></div>
						<p class="text-center"><a href="<?php echo $this->basePath()?>/matrimonial/profile-view?groom_id=<?php echo $GrData->uid ?>">(View full Profile)</a></p>
						</div>
						</div>
				</li>
                    
                    
                    
                    
                    
				<?php }
			}else{ ?> 
				<span style="text-align:center;font-weight:bold;font-size:12px; padding-left:10px;color:cornflowerblue;">No Data available</span>
			<?php } ?>
	</ul>
<div class="clearfix"></div>
<a href="<?php echo $this->basePath()?>/matrimonial/list-view?search_for=Male" class="btn btn-default pull-right" >View More</a>


</div>
</div>
</div>

<div class="clearfix"></div>

<div class="featured-list">
<ul id="flexiselDemo2">
<li style="width:100%;">
<a href="<?php echo $this->basePath()?>/pages/gallery" style="float:left; padding:0;" class="col-sm-4">
<div class="col-xs-5"><img src="<?php echo $this->basePath('images/gallery-thumb.jpg') ?>" class="img-responsive" /></div>
<div class="col-xs-7"><span class="bar">&nbsp;</span><h2><?php echo $this->translate('PHOTO GALLERY') ?></h2></div>
</a>

<a href="<?php echo $this->basePath()?>/pages/about" style="float:left; padding:0;" class="col-sm-4">
<div class="col-xs-5"><img src="<?php echo $this->basePath('images/about-us-thumb.jpg') ?>" class="img-responsive" /></div>
<div class="col-xs-7"><span class="bar">&nbsp;</span><h2><?php echo $this->translate('ABOUT RUSTAGI SAMAJ') ?></h2></div>
</a>

<a href="<?php echo $this->basePath()?>/matrimonial" style="float:left; padding:0;" class="col-sm-4">
<div class="col-xs-5"><img src="<?php echo $this->basePath('images/matrimonial.jpg') ?>" class="img-responsive" /></div>
<div class="col-xs-7"><span class="bar">&nbsp;</span><h2><?php echo $this->translate('MATRIMONIAL') ?></h2></div>
</a>
</li>

<li>
<a href="<?php echo $this->basePath()?>/pages/gallery" class="col-sm-12" style="width:100%; padding:0;">
<img src="<?php echo $this->basePath('images/rustagi_ad.jpg') ?>" class="img-responsive" style="width:100%;" />
</a>
</li>
</ul>
</div>

</div>

  <!-- Create New Start popup -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document" style="width:222px !important;">
    <div class="modal-content gnt-pad15 modal-contentnew">
      <form role="form" action="<?php echo $this->basePath()?>/matrimonial/profile-view?groom_id=<?php echo $BrdData->id ?>">
   		<div class="form-group">
        <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h2 class="modal-title" id="myModalLabel">Login</h2>
      </div>
      <div class="modal-body">
       
       <div class="col-sm-12">
       Email OR Mobile
      <input type="text" name="login_email" id="login_email" class="form-control" />
       </div>
       <div class="col-sm-12">
      Password
     <input type="password" name="login_password" id="login_password" class="form-control" />
       </div>
       
       <div class="col-sm-12">
      
     <input type="checkbox" name="rember" /><em>Remember me</em>
       </div>
       
        <div class="col-sm-12">
      
     <button type="submit" name="login" id="login" class="btn btn-default btn-block popuplogingbut">Sign In</button>
       </div>
       
       <div class="col-sm-12">
<a type="submit" class="">Forgot your password?</a>
</div>

<div class="col-sm-12 text-center">OR</div>

<div class="col-sm-12">New account 
<a class="btn btn-default btn-block popuplogingbut" href="<?php echo $this->basePath()?>/user/signup"><?php echo $this->translate('Signup') ?></a>

</div>

    <div class="col-sm-12 text-center"> </div>  
        
      </div>
      <div class="clearfix"></div>
      <div class="modal-footer">
       
      </div>
      </div>
        </form>
    </div>
  </div>
</div>

<div class="modal fade" id="myModalimg" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content gnt-pad15 modal-contentnew">
     
      <div class="modal-body" align="center">
     <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <img  id="popimg" src="" class="img-responsive"/>
                        
                        </div>
    </div>
  </div>
</div>

<script>
$("#list").on('click',function(){
	$(".li_listmember").addClass('li_listmember_wid');
});
$("#grid").on('click',function(){
	$(".li_listmember").removeClass('li_listmember_wid');
});
</script>
<!-- Create New End popup -->
<?php echo $this->inlineScript()->prependFile($this->basePath('/js/matrimony_filters.js')); ?>