
<div class="commen-list gblist-view list-view">
    <?php if ($this->type == 'female' || $this->type == 'both') { ?>
        <div style="width:100%; float:left;" id="brides">
            <h2>Brides</h2>
            <ul>
                <li  style="display:none;">
                    <div class="col-xs-2">
                        <div class="profile-pic"><a href="<?php echo $this->basePath() ?>/matrimonial/profile-view"><img src="images/groome.jpg" /></a></div>
                        <p>Ranbir Rustagi</p>
                        <p>26, 5.11”, Bhopal</p>
                        <!--<a href="<?php echo $this->basePath() ?>/matrimonial/profile-view" class="btn btn-default">more info</a>-->

                        <a href="#"  class="btn btn-default" data-toggle="modal" data-target="#myModal">more info</a>
                    </div>
                </li>

                <?php
                $i = 1;
                if (count($this->BridesData) > 0) {
                    /* echo "<pre>";
                      print_r($this->BrideData);exit; */
                    foreach ($this->BridesData as $BrdData) {
                        ?>
                        <li class="matrimonialli">
                            <div class="col-xs-3" align="center">
                                <a class="thumbnail" href="#thumb" style="margin-bottom:0;"><img src="<?php
                                    if ($BrdData->profile_photo != '') {
                                        echo $this->basePath() . $BrdData->profile_photo;
                                    } else {
                                        echo $this->basePath() . '/img/default_user.png';
                                    }
                                    ?>" class="img-responsive" width="78"/><!--<span><img src="<?php
                                                                                                 if ($BrdData->profile_photo != '') {
                                                                                                     echo $this->basePath() . $BrdData->profile_photo;
                                                                                                 } else {
                                                                                                     echo $this->basePath() . '/img/default_user.png';
                                                                                                 }
                                                                                                 ?>" /></span>--></a>
                                <?php echo $BrdData->name_title_user . " " . $BrdData->full_name ?>
                                <!--<p> <a href="#"  class="btn btn-default clickme" atr="findme<?= $i ?>" data-toggle="modal" data-target="#myModalimg" style="background:none !important; color:#eda344;">View Full Photo</a></p>--><div class="heithviue"><?php echo $BrdData->age . ',' . $BrdData->height; ?></div>
                                <div class="heithviue" style="height:;"><?php echo $BrdData->city; ?></div>
                                <div class="heithviue">
                                    <a href="<?php echo $this->basePath() ?>/matrimonial/profile-view?groom_id=<?php echo $BrdData->uid ?>" class="btn btn-default">more info</a>
                                    <!--<a href="<?php echo $this->basePath() ?>/matrimonial/profile-view?groom_id=<?php echo $BrdData->user_id ?>">Read More</a>--></div>
                            </div>
                            <div class="col-xs-9">
                                <div class="col-xs-8">
                                    <div class="col-xs-4">Name</div>
                                    <div class="col-xs-8">:  <?php echo $BrdData->name_title_user . " " . $BrdData->full_name ?></div>
                                    <div class="col-xs-4">Age / Height</div>
                                    <div class="col-xs-8">: <?php echo $BrdData->age . ',' . $BrdData->height; ?></div>
                                    <div class="col-xs-4">Religion</div>
                                    <div class="col-xs-8">: <?php echo $BrdData->religion; ?></div>						
                                    <!-- <div class="col-xs-4">Community</div>
                                    <div class="col-xs-8">: <?php echo $BrdData->caste; ?></div> -->
                                    <div class="col-xs-4">Location</div>
                                    <div class="col-xs-8">: <?php echo $BrdData->city . '/' . $BrdData->state . ',' . $BrdData->country; ?></div>
                                    <div class="col-xs-4">Education</div>
                                    <div class="col-xs-8">: <?php echo $BrdData->education_level . '-' . $BrdData->education_field; ?></div>
                                    <div class="col-xs-4">Profession</div>
                                    <div class="col-xs-8">: <?php echo $BrdData->profession; ?></div>
                                    <div class="col-xs-12"> <?php echo substr($BrdData->about_yourself_partner_family, 0, 120); ?><a href="<?php echo $this->basePath() ?>/matrimonial/profile-view?groom_id=<?php echo $BrdData->uid ?>">  Read more</a></div>
                                </div>
                                <div class="col-xs-4 col-xs-4-matri">
                                    <p class="text-right">(Profile created by Self)</p>
                                    <h3>Connect with her?</h3>
                                    <button class="btn btn-info btn-block">Yes</button>
                                    <button class="btn btn-success pull-left">May be</button>
                                    <button class="btn btn-danger pull-right">No</button>
                                    <div class="clearfix"></div>
                                    <p class="text-center"><a href="<?php echo $this->basePath() ?>/matrimonial/profile-view?groom_id=<?php echo $BrdData->uid ?>">(View full Profile)</a></p>
                                </div>
                            </div>
                        </li>



                        <?php
                        $i++;
                    }
                } else {
                    ?>
                    <span style="text-align:center;font-weight:bold;font-size:12px; padding-left:10px; color:cornflowerblue;">No Data available</span>
                <?php } ?>
            </ul>
            <div class="clearfix"></div>
            <a href="<?php echo $this->basePath() ?>/matrimonial/list-view?search_for=Female" class="btn btn-default pull-right">View More</a>
        </div>
    <?php } ?>
    <div class="clearfix"></div>
    <?php if ($this->type == 'male' || $this->type == 'both') { ?>
        <div style="width:100%; float:left;" id="grooms">
            <h2>Grooms</h2>
            <ul>	
                <li  style="display:none;">
                    <div class="col-xs-2">
                        <div class="profile-pic"><a href="<?php echo $this->basePath() ?>/matrimonial/profile-view"><img src="images/groome.jpg" /></a></div>
                        <p>Ranbir Rustagi</p>
                        <p>26, 5.11”, Bhopal</p>
                        <!--<a href="<?php echo $this->basePath() ?>/matrimonial/profile-view" class="btn btn-default">more info</a>-->

                        <a href="#"  class="btn btn-default" data-toggle="modal" data-target="#myModal">more info</a>
                    </div>
                </li>

                <?php
                if (count($this->GroomData) > 0) {
                    foreach ($GroomData as $GrData) {
                        ?>
                        <!--<li>
                        <div class="col-xs-2">
                        <div class="profile-pic"><a href="<?php echo $this->basePath() ?>/matrimonial/profile-view?groom_id=<?php echo $GrData->id ?>"><img src="<?php
                        if ($GrData->profile_photo != '') {
                            echo $this->basePath() . $GrData->profile_photo;
                        } else {
                            echo $this->basePath() . '/img/default_user.png';
                        }
                        ?>" /></a></div>
                        <p><?php echo $GrData->name_title_user . ". " . $GrData->full_name ?></p>
                        <p><?php echo $GrData->age . ',' . $GrData->height . ',' . $GrData->city; ?></p>
                        <a href="<?php echo $this->basePath() ?>/matrimonial/profile-view?groom_id=<?php echo $GrData->id ?>" class="btn btn-default">more info</a>


                        </div>
                        </li>-->

                        <li class="matrimonialli">
                            <div class="col-xs-3" align="center">
                                <a class="thumbnail" href="#thumb" style="margin-bottom:0;"><img id="findme<?= $i ?>" src="<?php
                                    if ($GrData->profile_photo != '') {
                                        echo $this->basePath() . $GrData->profile_photo;
                                    } else {
                                        echo $this->basePath() . '/img/default_user.png';
                                    }
                                    ?>" class="img-responsive" width="78" /><!--<span><img id="findme<?= $i ?>" src="<?php
                                                                                                 if ($GrData->profile_photo != '') {
                                                                                                     echo $this->basePath() . $GrData->profile_photo;
                                                                                                 } else {
                                                                                                     echo $this->basePath() . '/img/default_user.png';
                                                                                                 }
                                                                                                 ?>" class="img-responsive"/></span>--></a>
            <?php echo $GrData->name_title_user . " " . $GrData->full_name ?>
                                <!--<p><a href="#"  class="btn btn-default clickme" data-toggle="modal" atr="findme<?= $i ?>" data-target="#myModalimg" style="background:none !important; color:#eda344;">View Full Photo</a></p>--><div class="heithviue"><?php echo $GrData->age . ',' . $GrData->height; ?></div>
                                <div class="heithviue" style="height:;"><?php echo $GrData->city; ?></div>
                                <div class="heithviue">
                                    <a href="<?php echo $this->basePath() ?>/matrimonial/profile-view?groom_id=<?php echo $GrData->id ?>" class="btn btn-default">more info</a>
                                    <!--<a href="<?php echo $this->basePath() ?>/matrimonial/profile-view?groom_id=<?php echo $GrData->user_id ?>">Read More</a>--></div>
                            </div>
                            <div class="col-xs-9">
                                <div class="col-xs-8">
                                    <div class="col-xs-4">Name</div>
                                    <div class="col-xs-8">:  <?php echo $GrData->name_title_user . " " . $GrData->full_name ?></div>
                                    <div class="col-xs-4">Age / Height</div>
                                    <div class="col-xs-8">: <?php echo $GrData->age . ',' . $GrData->height; ?></div>
                                    <div class="col-xs-4">Religion</div>
                                    <div class="col-xs-8">: <?php echo $GrData->religion; ?></div>						
                                    <!-- <div class="col-xs-4">Community</div>
                                    <div class="col-xs-8">: <?php echo $GrData->caste; ?></div> -->
                                    <div class="col-xs-4">Location</div>
                                    <div class="col-xs-8">: <?php echo $GrData->city . '/' . $GrData->state . ',' . $GrData->country; ?></div>
                                    <div class="col-xs-4">Education</div>
                                    <div class="col-xs-8">: <?php echo $GrData->education_level . '-' . $GrData->education_field; ?></div>
                                    <div class="col-xs-4">Profession</div>
                                    <div class="col-xs-8">: <?php echo $GrData->profession; ?></div>
                                    <div class="col-xs-12"> <?php echo substr($GrData->about_yourself_partner_family, 0, 120); ?><a href="<?php echo $this->basePath() ?>/matrimonial/profile-view?groom_id=<?php echo $GrData->uid ?>">  Read more</a></div>
                                </div>
                                <div class="col-xs-4 col-xs-4-matri">
                                    <p class="text-right">(Profile created by Self)</p>
                                    <h3>Connect with her?</h3>
                                    <button class="btn btn-info btn-block">Yes</button>
                                    <button class="btn btn-success pull-left">May be</button>
                                    <button class="btn btn-danger pull-right">No</button>
                                    <div class="clearfix"></div>
                                    <p class="text-center"><a href="<?php echo $this->basePath() ?>/matrimonial/profile-view?groom_id=<?php echo $GrData->uid ?>">(View full Profile)</a></p>
                                </div>
                            </div>
                        </li>





                    <?php
                    }
                } else {
                    ?> 
                    <span style="text-align:center;font-weight:bold;font-size:12px; padding-left:10px;color:cornflowerblue;">No Data available</span>
    <?php } ?>
            </ul>
            <div class="clearfix"></div>
            <a href="<?php echo $this->basePath() ?>/matrimonial/list-view?search_for=Male" class="btn btn-default pull-right" >View More</a>


        </div>
<?php } ?>
</div>
