<div class="col-sm-3 width20per">
<?php echo $this->partial('layout/sidebar-news') ?>
</div>

<div class="col-sm-9 width80per">

<h2 class="heading">Latest Post</h2>
<div class="newsfull">
<img src="<?php echo $this->basePath('images/onside.jpg') ?>" class=" img-responsive pull-left" />
<h3>Post Title Here</h3>
<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>

<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>

<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting</p>

<p>dummy text ever since the 1500s, when an unknown printer took a galley .</p>

<div class="status">
<ul>
<li>Posted By : Ankit</li>
<li>Posted Date : 28-10-2015</li>
<li id="flip">Add Comment</li>
<li><a href="#">Share</a></li>
</ul>
</div>

<div id="panel">
<div class="form-group">
<textarea id="commentBodyField" class="form-control" onkeypress="BLOG_CMT_onCommentBodyChange()" cols="50" rows="4" name="commentBody" placeholder="Enter your comment..."></textarea>
</div>
<div class="form-group row">
<label class="col-sm-2 form-control-label lblline">Comment As</label>

<div class="col-sm-3">
<select class="form-control">
	<option>Google Account</option>
    <option>Select Profile</option>
</select>
</div>
</div>

<div class="form-group row">

<div class="col-sm-6">


<input id="postCommentSubmit" type="button" class="btn btn-info" value="Publish"  name="postCommentSubmit">
<input id="postCommentPreview" type="button" class="btn btn-info" value="Preview" name="postCommentPreview">

</div>
</div>
</div>
<div class="clearfix"></div>
<div class="related">

<div class="col-md-12 news col-xs-12">
<div class="col-md-2 col-sm-2 col-xs-3">
<div class="related-img"><img src="<?php echo $this->basePath('images/related-img.jpg') ?>" /></div>
</div>
<div class="col-md-10 col-sm-10 col-xs-9 content">
<h4>Vijay </h4>
<p>orem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five ce</p>

</div>
</div>

<div class="col-md-12 news col-xs-12">
<div class="col-md-2 col-sm-2 col-xs-3">
<div class="related-img"><img src="<?php echo $this->basePath('images/related-img.jpg') ?>" /></div>
</div>
<div class="col-md-10 col-sm-10 col-xs-9 content">
<h4>Vijay </h4>
<p>orem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five ce</p>

</div>
</div>

<div class="col-md-12 news col-xs-12">
<div class="col-md-2 col-sm-2 col-xs-3">
<div class="related-img"><img src="<?php echo $this->basePath('images/related-img.jpg') ?>" /></div>
</div>
<div class="col-md-10 col-sm-10 col-xs-9 content">
<h4>Vijay </h4>
<p>orem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five ce</p>

</div>
</div>

</div>


<div class="clearfix"></div>
</div>
</div>
  