<div class="col-sm-4" style="width:100%;">
		 <h3><?php echo $this->translate('Update Education & Career Info') ?></h3>	 
		  
		  
		  <div class="row">
	     <div class="form-group">	
	        <div class="col-md-2">
                <label style="margin-top: 20px;"><?php echo $this->translate('Education Level') ?></label>
			</div>
			</div>
			<div class="form-group">
			 <div class="col-md-">
                <?php  echo $this->formRow($form->get('education_level'));?>
             </div>			 
		</div>
	 </div>
		 
		  
		  <div class="row">
	     <div class="form-group">	
	        <div class="col-md-2">
                <label style="margin-top: 20px;"><?php echo $this->translate('Education Field') ?></label>
			</div>
			</div>
			<div class="form-group">
			 <div class="col-md-">
                <?php  echo $this->formRow($form->get('education_field'));?>
             </div>			 
		</div>
	 </div>
		   
		  
		  <div class="row">
	     <div class="form-group">	
	        <div class="col-md-2">
                <label style="margin-top: 20px;"><?php echo $this->translate('Specialization') ?></label>
			</div>
			</div>
			<div class="form-group">
			 <div class="col-md-">
                <?php  echo $this->formRow($form->get('specialization_major'));?>
             </div>			 
		</div>
	 </div>
		  
		  
		  <div class="row">
	     <div class="form-group">	
	        <div class="col-md-2">
                <label style="margin-top: 20px;"><?php echo $this->translate('Employment Status') ?></label>
			</div>
			</div>
			<div class="form-group">
			 <div class="col-md-">
                <?php  echo $this->formRow($form->get('employment_status'));?>
             </div>			 
		</div>
	 </div>
		  		    
		  
		  <div class="row">
	     <div class="form-group">	
	        <div class="col-md-2">
                <label style="margin-top: 20px;"><?php echo $this->translate('Profession') ?></label>
			</div>
			</div>
			<div class="form-group">
			 <div class="col-md-">
                <?php  echo $this->formRow($form->get('profession'));?>
             </div>			 
		</div>
	 </div> 
          
           <div class="form-group">			
			<?php  echo $this->formRow($form->get('submit'));?>
		  </div>
		  	  
	  </div>