 <div class="col-sm-4" style="width:100%;">
	 <div class="row">
			 <div class="form-group">	
				<div class="col-md-2">
					<label style="margin-top: 20px;"><?php echo $this->translate('Marital Status') ?></label>
				</div>
				</div>
				<div class="form-group">
				 <div class="col-md-">
					<?php  echo $this->formRow($form->get('marital_status'));?>
				 </div>			 
			</div>
		 </div>          
			  
			  <div class="row">
			 <div class="form-group">	
				<div class="col-md-2">
					<label style="margin-top: 20px;"><?php echo $this->translate('Caste') ?></label>
				</div>
				</div>
				<div class="form-group">
				 <div class="col-md-">
					<?php  echo $this->formRow($form->get('caste'));?>
				 </div>			 
			</div>
		 </div>	
			  
			  
			  <div class="row">
			 <div class="form-group">	
				<div class="col-md-2">
				<label><?php echo $this->translate('Caste Other') ?></label>
				</div>
				 <div class="col-md-">
				<?php  echo $this->formRow($form->get('caste_other'));?>
			  </div>
			</div>
		 </div>
				
			  
			  <div class="row">
			 <div class="form-group">	
				<div class="col-md-2">
					<label style="margin-top: 20px;"><?php echo $this->translate('Religion') ?></label>
				</div>
				</div>
				<div class="form-group">
				 <div class="col-md-">
					<?php  echo $this->formRow($form->get('religion'));?>
				 </div>			 
			</div>
		 </div>
				
				
				
				<div class="row">
			 <div class="form-group">	
				<div class="col-md-2">
				<label><?php echo $this->translate('Religion Other') ?></label>
				</div>
				 <div class="col-md-">
				<?php  echo $this->formRow($form->get('religion_other'));?>
			  </div>
			</div>
		 </div>
			  
			  <div class="row">
			 <div class="form-group">	
				<div class="col-md-2">
					<label style="margin-top: 20px;"><?php echo $this->translate('Blood Group') ?></label>
				</div>
				</div>
				<div class="form-group">
				 <div class="col-md-">
					<?php  echo $this->formRow($form->get('blood_group'));?>
				 </div>			 
			</div>
		 </div>	
 </div>
 
 