<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Modal Header</h4>
      </div>
      <div class="modal-body">
      
      
          <tr class="dontshow" id="indview<?=$i?>" aria-expanded="true">
                     
                  <td colspan="7">
                    <div aria-expanded="true" class="panel-body accordion-body packageDetails1 collapse in" id="accordion1">
               
                          <div class="tab-content" id="myTabContent">
        
              <div class="col-sm-col-sm-offset-1" style="margin: 10px auto 0px !important;padding: 0 10px;">
                <div class="row">
                   <div class="form-group clearfix margintopbottom20 col-sm-12">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Event Title'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
//                                                     \Zend\Debug\Debug::dump($info);exit;
                                                     echo $info->eventName;
                                                     ?>                                    
                                                  </div>
                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Upload Event Image'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <p class="pull-left newsimg">

          <img src="<?php //echo $this->basepath().$info->image; ?>" width="127"  height="126" alt=""></p>                                 
                                                  </div>
                           
                                                 </div>
                                             </div>
                                             
                                             <div class="row">
                                                <div class="form-group clearfix margintopbottom20 col-sm-12">
                        <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Event Description'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php                                                      
                                                     echo $info->eventDesc;
                                                     ?>                                    
                                                  </div>
                                                 
                            <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Sponser Photo'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <img src="<?php //echo $this->basepath().$info->sponserPhoto; ?>" alt="Alex's Avatar" class="editable img-responsive editable-click " id="avatar"></img>                           
                                                  </div>
                                                 </div>
                                             </div>

                                          <div class="row">
                                                <div class="form-group clearfix margintopbottom20 col-sm-12">
                          
                                                 
                            <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Sponser Name'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo $info->sponserName;
                                                     ?>                                    
                                                  </div>
                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Sponser Contact'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo $info->sponserContact;
                                                     ?>                                    
                                                  </div>
                                                 </div>
                                             </div>  


                                             <div class="row">
                                                <div class="form-group clearfix margintopbottom20 col-sm-12">
                          
                                                 
                            <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Organiser Photo'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <img src="<?php //echo $this->basepath().$info->organiserPhoto; ?>"  alt="Alex's Avatar" class="editable img-responsive editable-click " id="avatar"></img>                                   
                                                  </div>
                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Organiser Name'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo $info->eventOrganiser;
                                                     ?>                                    
                                                  </div>
                                                 </div>
                                             </div> 

                                             <div class="row">
                                                <div class="form-group clearfix margintopbottom20 col-sm-12">
                          
                                                 
                            <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Organiser Contact'); ?>
                           </label>
                                                  <div class="col-sm-3">   
                                                    <?php                                     
                                                     echo $info->organiserContact;
                                                     ?>                         
                                                  </div>
                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('venue'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo $info->venue;
                                                     ?>                                    
                                                  </div>
                                                 </div>
                                             </div> 

                                             <div class="row">
                                                <div class="form-group clearfix margintopbottom20 col-sm-12">
                          
                                                 
                            <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Event Date'); ?>
                           </label>
                                                  <div class="col-sm-3">   
                                                    <?php                                     
                                                     echo $info->eventDate;
                                                     ?>                         
                                                  </div>
                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('End Date'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo $info->endDate;
                                                     ?>                                    
                                                  </div>
                                                 </div>
                                             </div>

                                             <div class="row">
                                                <div class="form-group clearfix margintopbottom20 col-sm-12">
                          
                                                 
                            <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Country Name'); ?>
                           </label>
                                                  <div class="col-sm-3">   
                                                    <?php                                     
                                                     echo $info->countryName;
                                                     ?>                         
                                                  </div>
                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('State Name'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo $info->stateName;
                                                     ?>                                    
                                                  </div>
                                                 </div>
                                             </div>

                                             <div class="row">
                                                <div class="form-group clearfix margintopbottom20 col-sm-12">
                          
                                                 
                            <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('City Name'); ?>
                           </label>
                                                  <div class="col-sm-3">   
                                                    <?php                                     
                                                     echo $info->cityName;
                                                     ?>                         
                                                  </div>
                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Start Time'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo $info->startTime;
                                                     ?>                                    
                                                  </div>
                                                 </div>
                                             </div>

                                             <div class="row">
                                                <div class="form-group clearfix margintopbottom20 col-sm-12">
                          
                                                 
                            <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('End Time'); ?>
                           </label>
                                                  <div class="col-sm-3">   
                                                    <?php                                     
                                                     echo $info->endTime;
                                                     ?>                         
                                                  </div>
                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?php //echo  $this->translate('Start Time'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     //echo $info->username;
                                                     ?>                                    
                                                  </div>
                                                 </div>
                                             </div>

                                             <div class="row">
                                                <div class="form-group clearfix margintopbottom20 col-sm-12">
                          
                                                 
                            <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Created Date'); ?>
                           </label>
                                                  <div class="col-sm-3">   
                                                    <?php                                     
                                                     echo $info->createdDate;
                                                     ?>                         
                                                  </div>
                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?php echo  $this->translate('venue'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo $info->venue;
                                                     ?>                                    
                                                  </div>
                                                 </div>
                                             </div>
                                             
              </div>
           
          </div>
      </div>
                    
                                             
                       </td>
                    </tr>   
      </div>
      <div class="modal-footer">
        <button type="button"data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
         