 <div >
            <p>
              <a href="<?= $this->url('admin',array('controller'=>'events','action'=>'eventsindex'));?>"><button class="btn btn-warning btn-xlg">Go Back</button></a>
            </p>
          </div>
          

      <?php 

                $form=$this->form; 
                $form->prepare();


        $form->setAttribute('action',$this->url('admin',array('controller'=>'events','action'=>'eventsadd')));
        $form->setAttribute('onsubmit','return SubmitEventsForm();');
        $form->setAttribute('method','post');
        $form->setAttribute('enctype','multipart/form-data');


        echo $this->form()->openTag($form);
// echo $this->formCollection($form);
                ?>
                <div class="alert_info">
        <h3>Organizer Details</h3>
      </div>
          <div class="tab-pane fade active in" id="driver_tab">
                                         <div class=" col-sm-col-sm-offset-1" >
                    <div class="row">
                                                <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate($form->get('event_name')->getLabel()) ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo $this->formHidden($form->get('id'));
                                                     echo $this->formElement($form->get('event_name'));
                                                     ?>                                    
                                                  </div>
                                                 
                            <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate($form->get('sponser_name')->getLabel()) ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo $this->formElement($form->get('sponser_name'));
                                                     ?>                                    
                                                  </div>
                                                 </div>
                                             </div>
                       
                       <div class="row">
                                                <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate($form->get('organiser_name')->getLabel()) ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo $this->formElement($form->get('organiser_name'));
                                                     ?>                                    
                                                  </div>
                                                 
                            <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate($form->get('sponser_photo')->getLabel()) ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo $this->formElement($form->get('sponser_photo'));
                                                     ?>                                    
                                                  </div>
                                                 </div>
                                             </div>
                        <div class="row">
                                                <div class="form-group clearfix margintopbottom20">
                          <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate($form->get('organiser_photo')->getLabel()) ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo $this->formElement($form->get('organiser_photo'));
                                                     ?>                                    
                                                  </div>

                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate($form->get('organiser_contact')->getLabel()) ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo $this->formElement($form->get('organiser_contact'));
                                                     ?>                                    
                                                  </div>
                           
                                                 
                            
                                                   
                                                 </div>
                                                                                              
                                             </div>

                                              <div class="row">
                                                <div class="form-group clearfix margintopbottom20">
                           
                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate($form->get('sponser_contact')->getLabel()) ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo $this->formElement($form->get('sponser_contact'));
                                                     ?>                                    
                                                  </div>

                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate($form->get('IsActive')->getLabel()) ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo $this->formElement($form->get('IsActive'));
                                                     ?>                                    
                                                  </div>
                           
                                                 
                            
                                                   
                                                 </div>
                                                                                              
                                             </div>
                         
                         
                       
                       
                       
                       
                    </div>
                                    </div>

<div class="alert_info">
        <h3>Event Graphics</h3>
      </div>
          <div class="tab-pane fade active in" id="driver_tab">
                                         <div class=" col-sm-col-sm-offset-1" >
                     
                                             <div class="row">
              <div class="col-xs-12">
                 <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate($form->get('event_desc')->getLabel()) ?>
                           </label>
                <div class="wysiwyg-editor" id="editor1"></div>
                  
              </div><!-- /.col -->
            </div><!-- /.row --> 
                                             <div class="row">
                                                <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate($form->get('image')->getLabel()) ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                      echo $this->formElement($form->get('event_desc'));
                                                     echo $this->formElement($form->get('image'));
                                                     ?>                                    
                                                  </div>
                                                 
                               
                                                                                        
                                                   
                                                 </div>
                                             </div>
                       
                       
                    </div>
                                    </div>
                                    <div class="alert_info">
        <h3>Location Details</h3>
      </div>
          <div class="tab-pane fade active in" id="driver_tab">
                                         <div class=" col-sm-col-sm-offset-1" >
                    <div class="row">
                                                <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate($form->get('country_id')->getLabel()) ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo $this->formElement($form->get('country_id'));
                                                     ?>                                    
                                                  </div>
                                                 
                            <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate($form->get('city_id')->getLabel()) ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo $this->formElement($form->get('city_id'));
                                                     ?>                                    
                                                  </div>
                                                 </div>
                                             </div>
                       
                       <div class="row">
                                                <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate($form->get('state_id')->getLabel()) ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo $this->formElement($form->get('state_id'));
                                                     ?>                                    
                                                  </div>
                                                 
                             
                                                 </div>
                                             </div>
                         
                         
                       
                       
                       
                       
                    </div>
                                    </div>
                                    <div class="alert_info">
        <h3>Event Timing Details</h3>
      </div>
          <div class="tab-pane fade active in" id="driver_tab">
                                         <div class=" col-sm-col-sm-offset-1" >
                    <div class="row">
                                                <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate($form->get('start_date')->getLabel()) ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <div class="input-group">
																	 <?php 
                                                     echo $this->formElement($form->get('start_date'));
                                                     ?><span class="input-group-addon">
																		<i class="fa fa-calendar bigger-110"></i>
																	</span>
																	
																	
																</div> 
                                                     
                                                                                        
                                                  </div>
                                                 
                            <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate($form->get('end_date')->getLabel()) ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo $this->formElement($form->get('end_date'));
                                                     ?>                                    
                                                  </div>
                                                 </div>
                                             </div>
                       
                       <div class="row">
                                                <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate($form->get('start_time')->getLabel()) ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo $this->formElement($form->get('start_time'));
                                                     ?>                                    
                                                  </div>
                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate($form->get('end_time')->getLabel()) ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo $this->formElement($form->get('end_time'));
                                                     ?>                                    
                                                  </div>
                                                 
                             
                                                 </div>
                                             </div>
                         
                         
                       <div class="row">
                                                <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate($form->get('venue')->getLabel()) ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo $this->formElement($form->get('venue'));
                                                     ?>                                    
                                                  </div>
                                                   
                             
                                                 </div>
                                             </div>
                       
                       
                       
                    </div>
                                    </div>
                                    <div class="alert_info">
        <h3>Event Costing</h3>
      </div>
          <div class="tab-pane fade active in" id="driver_tab">
                                         <div class=" col-sm-col-sm-offset-1" >
                    <div class="row">
                                                <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate($form->get('event_cost')->getLabel()) ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo $this->formElement($form->get('event_cost'));
                                                     ?>                                    
                                                  </div>
                                                 
                            <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate($form->get('event_members')->getLabel()) ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo $this->formElement($form->get('event_members'));
                                                     ?>                                    
                                                  </div>
                                                 </div>
                                             </div>
                    </div>
                                    </div>

                                    <?php   
                                    echo $this->formElement($form->get('submit'));
echo $this->form()->closeTag();

        ?>