 
  
<div class="modal-dialog">
    <div class="modal-content">
      Developement mode ahead
           <?php 
/*
                $form=$this->form; 
                $form->prepare();


        $form->setAttribute('action',$this->url('admin',array('controller'=>'events','action'=>'eventsedit')));
        $form->setAttribute('id','EventsEditForm');
        $form->setAttribute('onsubmit','return SubmitEventsForm($(this).attr("id"));');
        $form->setAttribute('method','post');
        $form->setAttribute('enctype','multipart/form-data');


        echo $this->form()->openTag($form);
// echo $this->formCollection($form);
                ?>
                <div class="alert_info">
        <h3>Organizer Details</h3>
      </div>
          <div class="tab-pane fade active in" id="driver_tab">
                                         <div class=" col-sm-col-sm-offset-1" >
                    <div class="row">
                                                <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate($form->get('event_name')->getLabel()) ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo $this->formHidden($form->get('id'));
                                                     echo $this->formElement($form->get('event_name'));
                                                     ?>
                                                     <span class="showerror"></span>                                    
                                                  </div>
                                                 
                            <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate($form->get('sponser_name')->getLabel()) ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo $this->formElement($form->get('sponser_name'));
                                                     ?> 
                                                     <span class="showerror"></span>                                   
                                                  </div>
                                                 </div>
                                             </div>
                       
                       <div class="row">
                                                <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate($form->get('event_organiser')->getLabel()) ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo $this->formElement($form->get('event_organiser'));
                                                     ?>   
                                                     <span class="showerror"></span>                                 
                                                  </div>
                                                 
                            <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate($form->get('sponser_photo')->getLabel()) ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo $this->formElement($form->get('sponser_photo'));
                                                     ?>
                                                     <span class="showerror"></span>                                    
                                                  </div>
                                                 </div>
                                             </div>
                        <div class="row">
                                                <div class="form-group clearfix margintopbottom20">
                          <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate($form->get('organiser_photo')->getLabel()) ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo $this->formElement($form->get('organiser_photo'));
                                                     ?>sadadas
                                                     <!-- <input type="hidden" name="organiser_photo" value="<?=$form->get('organiser_photo'?>"> -->
                                                     <span class="showerror"></span>                                    
                                                  </div>

                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate($form->get('organiser_contact')->getLabel()) ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo $this->formElement($form->get('organiser_contact'));
                                                     ?>
                                                     <span class="showerror"></span>                                    
                                                  </div>
                           
                                                 
                            
                                                   
                                                 </div>
                                                                                              
                                             </div>

                                              <div class="row">
                                                <div class="form-group clearfix margintopbottom20">
                           
                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate($form->get('sponser_contact')->getLabel()) ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo $this->formElement($form->get('sponser_contact'));
                                                     ?> 
                                                     <span class="showerror"></span>                                   
                                                  </div>

                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate($form->get('IsActive')->getLabel()) ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo $this->formElement($form->get('IsActive'));
                                                     ?> 
                                                     <span class="showerror"></span>                                   
                                                  </div>
                           
                                                 
                            
                                                   
                                                 </div>
                                                                                              
                                             </div>
                         
                         
                       
                       
                       
                       
                    </div>
                                    </div>

<div class="alert_info">
        <h3>Event Graphics</h3>
      </div>
          <div class="tab-pane fade active in" id="driver_tab">
                                         <div class=" col-sm-col-sm-offset-1" >
                     
                                             <div class="row">
              <div class="col-xs-12">
                 <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate($form->get('event_desc')->getLabel()) ?>
                           </label>
                <div class="wysiwyg-editor" id="editor1"></div>
                  
              </div><!-- /.col -->
            </div><!-- /.row --> 
                                             <div class="row">
                                                <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate($form->get('image')->getLabel()) ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                      echo $this->formElement($form->get('event_desc'));
                                                     echo $this->formElement($form->get('image'));
                                                     ?>
                                                     <span class="showerror"></span>                                    
                                                  </div>
                                                 
                                                 </div>
                                             </div>
                       
                       
                    </div>
                                    </div>
                                    <div class="alert_info">
        <h3>Location Details</h3>
      </div>
          <div class="tab-pane fade active in" id="driver_tab">
                                         <div class=" col-sm-col-sm-offset-1" >
                    <div class="row">
                                                <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate($form->get('country_id')->getLabel()) ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo $this->formElement($form->get('country_id'));
                                                     ?> 
                                                     <span class="showerror"></span>                                   
                                                  </div>
                                                 
                            <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate($form->get('city_id')->getLabel()) ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo $this->formElement($form->get('city_id'));
                                                     ?>
                                                     <span class="showerror"></span>                                    
                                                  </div>
                                                 </div>
                                             </div>
                       
                       <div class="row">
                                                <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate($form->get('state_id')->getLabel()) ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo $this->formElement($form->get('state_id'));
                                                     ?>
                                                     <span class="showerror"></span>                                    
                                                  </div>
                                                 
                             
                                                 </div>
                                             </div>
                         
                         
                       
                       
                       
                       
                    </div>
                                    </div>
                                    <div class="alert_info">
        <h3>Event Timing Details</h3>
      </div>
          <div class="tab-pane fade active in" id="driver_tab">
                                         <div class=" col-sm-col-sm-offset-1" >
                    <div class="row">
                                                <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate($form->get('event_date')->getLabel()) ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <div class="input-group">
                                   <?php 
                                                     echo $this->formElement($form->get('event_date'));
                                                     ?><span class="showerror"></span>
                                  
                                  
                                </div> 
                                                     
                                                                                        
                                                  </div>
                                                 
                            <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate($form->get('end_date')->getLabel()) ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo $this->formElement($form->get('end_date'));
                                                     ?> 
                                                     <span class="showerror"></span>                                   
                                                  </div>
                                                 </div>
                                             </div>
                       
                       <div class="row">
                                                <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate($form->get('start_time')->getLabel()) ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo $this->formElement($form->get('start_time'));
                                                     ?> 
                                                     <span class="showerror"></span>                                   
                                                  </div>
                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate($form->get('end_time')->getLabel()) ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo $this->formElement($form->get('end_time'));
                                                     ?>
                                                     <span class="showerror"></span>                                    
                                                  </div>
                                                 
                             
                                                 </div>
                                             </div>
                         
                         
                       <div class="row">
                                                <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate($form->get('venue')->getLabel()) ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo $this->formElement($form->get('venue'));
                                                     ?>
                                                     <span class="showerror"></span>                                    
                                                  </div>
                                                   
                             
                                                 </div>
                                             </div>
                       
                       
                       
                    </div>
                                    </div>
                                    <div class="alert_info">
        <h3>Event Costing</h3>
      </div>
          <div class="tab-pane fade active in" id="driver_tab">
                                         <div class=" col-sm-col-sm-offset-1" >
                    <div class="row">
                                                <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate($form->get('event_cost')->getLabel()) ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo $this->formElement($form->get('event_cost'));
                                                     ?> 
                                                     <span class="showerror"></span>                                   
                                                  </div>
                                                 
                            <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate($form->get('event_members')->getLabel()) ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo $this->formElement($form->get('event_members'));
                                                     ?> 
                                                     <span class="showerror"></span>                                   
                                                  </div>
                                                 </div>
                                             </div>
                    </div>
                                    </div>

                                    <?php   
                                    echo $this->formElement($form->get('submit'));
echo $this->form()->closeTag();
*/
        ?>       
</div>
</div>