
                   <?php 

                $form=$this->form; 
                $form->prepare();


        //$form->setAttribute('action',$this->url('admin',array('controller'=>'State','action'=>'edit')));
        $form->setAttribute('action', $this->url('admin/state', array('action' => 'edit', 'id' => $id)));
        $form->setAttribute('method','post');
        $form->setAttribute('name', 'editform');
        $form->setAttribute('autocomplete','off');
        //$form->setAttribute('id','StateForm');
        $form->setAttribute('id','StateFormEdit');
       // $action = $this->serverUrl().$this->url('admin',array('controller'=>'state','action'=>'edit','id'=>$id));
        $action = $this->url('admin/state', array('action' => 'edit', 'id' => $id));
        //$form->setAttribute('onSubmit',"return SubmitFormAction($(this).attr('id'),'".$action."',addformResp)");
        $form->setAttribute('onSubmit', "return SubmitFormAction($(this).attr('id'),'" . $action . "',addformResp)");

        echo $this->form()->openTag($form);
// echo $this->formCollection($form);
                ?>
            
            
            
            <div class="tab-pane fade active in" id="driver_tab">
              <div class="col-sm-col-sm-offset-1" style="margin: 10px auto 0px !important;padding: 0 10px;">
                
               								 <div class="row">
                                                <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate($form->get('country_id')->getLabel()) ?>
                           </label>
                                                  <div class="col-sm-2">
                                                     <?php 
                                                     echo $this->formHidden($form->get('id'));
                                                     echo $this->formElement($form->get('country_id'));
                                                     ?> 
                                                     <span class="showerror"></span>                                      
                                                  </div>
                                                 
                           <label id="flight_nos" class="col-sm-1 control-label labelalign ">
                            <?= $this->translate($form->get('state_name')->getLabel()) ?>
                           </label>
                                                  <div class="col-sm-2 passCname" Cname="">
                                                     <?php 
                                                     //echo $this->formHidden($form->get('master_state_id'));

                                                     echo $this->formElement($form->get('state_name'));
                                                     ?>
                                                     <span class="showerror"></span>                                        
                                                  </div>
                                                  
                                                    <label id="flight_nos" class="col-sm-1 control-label labelalign ">
                            <?= $this->translate($form->get('IsActive')->getLabel()) ?>
                           </label>
                           
                                                    <div class="col-sm-2">
                                                     <?php 
                                                     echo $this->formElement($form->get('IsActive'));
                                                     ?> 
                                                     <span class="showerror"></span>                                      
                                                  </div>
                                                  
                                                  <div class="col-sm-1">
                                                     <?php 
                                                     echo $this->formRow($form->get('submit'));
                                                     ?>                                    
                                                  </div>
                                                  
                                                 </div>
                                             </div>
                                             
                                             
              </div>
            </div>
          
        <?php   
echo $this->form()->closeTag();

        ?>                                   
                                                  