<style>
	.modal-dialog {
    width: 67%;
}

.activestatus{
		color:green;
		background:green;
		border-radius:30px; width:15px; height:15px;
		cursor:pointer
		
	}
	
	.de-activestatus{
		color:green;
		background:red;
		border-radius:30px; width:15px; height:15px;
		cursor:pointer;
		
		
	}



</style>


<div class="row">
          <div class="col-xs-12"> 
            <!-- PAGE CONTENT BEGINS -->
            <!--<div class="alert alert-block alert-success">
              <button type="button" class="close" data-dismiss="alert"> <i class="ace-icon fa fa-times"></i> </button>
              <i class="ace-icon fa fa-check green"></i>Add State Master</strong>, </div>
            <div class="row">
              <div class="space-6"></div>
              <div class="vspace-12-sm"></div>
            </div>-->
            <div class="row">
              <div class="col-xs-12">
                <h3  >Add States Master</h3>
                <div class="filter">
                 <div class="panel-body" style="padding:0 !important">
                  <div class="col-lg-6">View Records>></div>
                  </div>
                </div>
                <div class="portlet-body">
                  <?php 

                  $form=$this->form; 
                $form->prepare();


        //$form->setAttribute('action',$this->url('admin',
                  //array("controller"=>"state","action"=>"performsearch")));
        $form->setAttribute('action',$this->url('admin/state', array('action' => 'performsearch')));
        
        $form->setAttribute('method','post');
        $form->setAttribute('autocomplete','off');
        $form->setAttribute('id','bookingFilter');
        
//        $form->setAttribute('onSubmit','return performsearch(this.id,"'.$this->url("admin",
//                  array("controller"=>"state","action"=>"performsearch")).'",performsearchresults)');
        
        $action = $this->url('admin/state', array('action' => 'performsearch'));
        $form->setAttribute('onSubmit',"return performsearch($(this).attr('id'),'".$action."',performsearchresults)");

        echo $this->form()->openTag($form);

                  ?>
                   
                    <div id="myTabContent" class="tab-content">
                      <div class="tab-pane fade active in" id="home">
                        <div class="col-sm-col-sm-offset-1" style="margin: 10px auto 0px !important;padding: 0 10px;">
                          <div class="row">
                                                <div class="form-group clearfix margintopbottom20">
                          						 <label id="point_airport" class="col-sm-2 control-label labelalign ">Country Name
                          						 </label>
                                                   <div class="col-sm-3">
                                                    <?php 

                                                     echo $this->formElement($form->get('country_id'));

                                                    ?>
                                                    
                                                    </div>

                         						  <label id="flight_nos" class="col-sm-2 control-label labelalign ">State Name</label>
                                                  <div class="col-sm-2 ">
                                                     <input id="search_countryName" class=" form-control inputchange" placeholder="State Name" type="text" 
                                                     onkeyup="countrysearchactions($(this).val(),'<?php echo $this->url("admin/state",array('action'=>'countrysearch'))?>',countrysearchresp,$('#bookingFilter :input[name=country_id]').val())" name="state_name">
                                                     <div class="col-sm-3" id="countrysearchresults" style="position: absolute;overflow-y:scroll;background:#FFF;width:93%;height:auto;z-index: 9999;display:none;">
                                                     </div>                                    
                                                  </div>
                                                 
                            				<div class="col-sm-1">
                                                     <input class="btn btn-red defaultbtnsearch searchBooking"  type="submit" name="submit" value="Search">
                                                    </div>
                                                    
                                                    <div class="col-sm-2">
                                                     <a id="showaddform" class="btn btn-red defaultbtnsearch searchBooking" href="#"> Add</a>
                                                    </div>
                                                 </div>
                                             </div>
                          
                                             </div>

                          
                           
                        </div>
                      </div>
                   <?php   
echo $this->form()->closeTag();

        ?>                                   
          
                    </div>
                
                 
                  <div class="filter">
                   <div class="panel-body" style="padding:0 !important; cursor:pointer;">
                  <div class="col-lg-6" >Add Update Records>>
                    </div>
                     <!--<div class="col-lg-6" id="showaddform" align="right" style="font-size:18px;">+
                    </div>-->
                  </div>
   
                </div>
                
                
              
               
                
          <div id="addForm" class="tab-content dontshow">
                   <?php 

                $form=$this->form; 
                $form->prepare();


        $form->setAttribute('action',$this->url('admin/state', array('action' => 'add')));        
        $form->setAttribute('method','post');
        $form->setAttribute('autocomplete','off');
        $form->setAttribute('id','StateForm');        
        $action = $this->url('admin/state', array('action' => 'add'));
        $form->setAttribute('onSubmit',"return SubmitFormAction($(this).attr('id'),'".$action."',addformResp)");

        echo $this->form()->openTag($form);
// echo $this->formCollection($form);
                ?>
        
            
            
            <div class="tab-pane fade active in" id="driver_tab">
              <div class="col-sm-col-sm-offset-1" style="margin: 10px auto 0px !important;padding: 0 10px;">
                
                <div class="row">
                                                <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate($form->get('country_id')->getLabel()) ?>
                           </label>
                                                  <div class="col-sm-2">
                                                     <?php 
                                                     echo $this->formHidden($form->get('id'));
                                                     echo $this->formElement($form->get('country_id'));
                                                     ?> 
                                                     <span class="showerror"></span>                                      
                                                  </div>
                                                 
                           <label id="flight_nos" class="col-sm-1 control-label labelalign ">
                            <?= $this->translate($form->get('state_name')->getLabel()) ?>
                           </label>
                                                  <div class="col-sm-2 dontshow" id="passCname" Cname="">
                                                     <?php 
                                                     echo $this->formHidden($form->get('master_state_id'));

                                                     echo $this->formElement($form->get('state_name'));
                                                     ?>
                                                     <span class="showerror"></span> <div class="col-sm-3 searchboxresults" id="searchresults" style="position: absolute;
  overflow-y:scroll;
  background:#FFF;
  width:93%;
  height:auto;
  z-index: 9999;display:none;">
                                                     </div>                                       
                                                  </div>
                                                  
                                                   <label id="flight_nos" class="col-sm-1 control-label labelalign ">
                            <?= $this->translate($form->get('IsActive')->getLabel()) ?>
                           </label>
                                                  <div class="col-sm-2">
                                                     <?php 
                                                     echo $this->formElement($form->get('IsActive'));
                                                     ?> 
                                                     <span class="showerror"></span>                                      
                                                  </div>
                                                  
                                                  <div class="col-sm-1 ">
                                                     <?php 
                                                     echo $this->formRow($form->get('submit'));
                                                     ?>                                    
                                                  </div>
                                                  
                                                  
                                                 </div>
                                             </div>
                                             
                                             
              </div>
            </div>
          
        <?php   
echo $this->form()->closeTag();

        ?>                                   
                                                  </div>
                                           
                                              
              <div id="editForm" class="tab-content dontshow">
          </div>
                   
                  <div class="clearfix"></div>
                <div class="col-lg-12" style="background-color:#FFF;" id="radiosearch" fld="tbl_country">
                  
                  <div class="col-lg-1"><div class="radio">
                                                <label>
                                                    <input type="radio" value="1" id="optionsRadios1" 
                                                           name="optionsRadios" onchange=
                                                               "RadioSearch($(this).val(),
                                                               'tbl_state','<?php echo 
$this->url('admin/state', array('action'=>'ajaxradiosearch'))?>',radioSearchResult10)" ><strong>Active</strong>
                                                </label>
                                                <br>
 
                                            </div>
                  
                  
                  
                  
                  </div>
                  
                  
                   <div class="col-lg-1">
                    <div class="radio">
                                                <label>
                                                    <input type="radio" value="0" id="optionsRadios1" 
                                                           name="optionsRadios" onchange="RadioSearch
                                                               ($(this).val(),'tbl_state','<?php echo $this->url
                                            ('admin/state', array('action'=>'ajaxradiosearch'))?>',
                                                                           radioSearchResult10)"><strong>
                                                        In-Active</strong>
                                                </label>
                                                
                                              
                    </div>
                  </div>
                  
                    
                   
                    <div class="col-lg-2 pull-right">
                        <div class="delete">
                      <button class="btn btn-red defaultbtnsearch searchBooking" onclick="statuschangeall
                          ('<?php echo $this->url('admin/state', array('action'=>
                                    'statuschangeall'))?>',
                          statuschangeallresp,0)">De-Activate Selected</button> 
                         </div>
                    </div>
                    
                    <div class="col-lg-2 pull-right">
                    <div class="delete">
                      <button class="btn btn-red defaultbtnsearch searchBooking" onclick="statuschangeall
                          ('<?php echo $this->url('admin/state', array
                                    ('action'=>'statuschangeall'))?>',
                          statuschangeallresp,1)">Activate Selected</button>                                    
                    </div>
                  </div>
                  
                 <div class="col-lg-2 pull-right">
                    <div class="delete">
                      <button class="btn btn-red defaultbtnsearch searchBooking" onclick="delselected
                          ('<?php echo $this->url('admin/state', array('action'=>
                                    'delmultiple'))?>',delmultipleresp)">
                          Delete Selected</button>                                              
                    </div>
                  </div>

                  </div>
                  
                  <div class="col-sm-12">

                 
                   
</div>         <div class="col-md-12" id="state_data_list">
                    
                    <?php echo $this->partial('admin/state/stateList.phtml'); ?>
               </div>
              </div>
              
              
              
              
              
              <div class="col-sm-12"> 
              </div>
            </div>
            <!-- /.col --> 

            <a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse"> <i class="ace-icon fa fa-angle-double-up icon-only bigger-110"></i> </a> </div>
            
            </div></div>
        
<div id="viewStateModel"></div>
<?php echo $this->inlineScript()->prependFile($this->basePath('/assets/js/state.js')); ?>
            
 
  <!-- /.main-content -->
  
     
  
<!-- /.main-container --> 

<!-- basic scripts --> 

<!--[if !IE]> -->