
                    <div class="table-responsive">
                      <table id="dynamic-table" class="table table-striped table-bordered table-hover">
                    <thead>
                      <tr>
                         
                           <th><input type="checkbox" value="" id="checkAll" onclick="checkall(this.id)" > </th>
                         <th> Sr. No. </th>
                        <th>State Name</th>
                        <th>Country Name</th>
                        <th class="hidden-480">Modified Date</th>
                        <th class="hidden-480">Created Date</th>
                        <th class="hidden-480">Status</th>
                        <th class="hidden-480">Modified By</th>
                        <th><b>Actions</b></th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php 
                      $i=1;
                      foreach ($states as $state) {
                      
                      ?>
                      <tr>
                            <td><input type="checkbox" value="<?=$state->id?>" class="checkme" name="checkme[]"> </td>  
                        <td> <?=$i?></td>
                        <td><?= $state->state_name?></td>                       
                        <td class="hidden-480"><?= $state->country_name?></td>
                        <td class="hidden-480"><?= $state->modified_date?></td>
                        <td class="hidden-480"><?= $state->created_date?></td>
                        
                        <td class="hidden-480" align="center">

    <?php
    $status = ($state->IsActive == 1) ? 'Active' : 'In-Active';
    $statuscolor = ($state->IsActive == 1) ? 'activestatus' : 'de-activestatus';
    ?>
                                            <div name="ChangeStatus" id="changestatus<?= $i; ?>" onclick=
                                                "changestatusquick(<?= $state->id ?>,<?= ($state->
                                                        IsActive == 0) ? 0 : 1; ?>, '<?php echo $this->
                                                                url('admin/state', array('action'=>
                                                                    'changestatus')); ?>', 
                                                                        changstatusresult);" class="<?= 
                                                        $statuscolor ?>">
                                            </div>

                                        </td>
                        <td class="hidden-480"><?php echo ($state->modified_by==1)? 'Admin': 'NotByAdmin'; ?></td>
                        <td aria-expanded="false" class="accordion1">
                        <div class="hidden-sm hidden-xs action-buttons">                        
                         <a class="blue" style="cursor:pointer;" data-toggle="modal" data-target="#myModal" tar="indview<?=$i?>
                            "> <i onclick="findRowDataByStateId('<?php echo $this->url
                                                           ('admin/state', array('action'=>'viewById','id'=>$state->id)); ?>', 
                                                                       viewRowDataById);" class="ace-icon fa fa-search-plus bigger-130">
                                                    </i> </a>
                        
                         
                        
                        <a class="green" href="javascript:void(0);" onclick="editbox(<?= $state->id ?>, '<?php echo 
                                        $this->url('admin/state', array('action' => 'edit', 'id' => $state->id));
                                        ?>', editformresp);" > <i class="ace-icon fa fa-pencil bigger-130"></i> </a>

                         
                        
                        <a class="red" 
                                           href="<?php echo $this->url('admin/state', array('action' => 'delete', 'id' => 
                                               $state->id)); ?>" onclick="return confirm('are you sure you want to delete');"> 
                                            <i class="ace-icon fa fa-trash-o bigger-130"></i> </a>
                        </div>
                          </td>
                      </tr>
                      
                       
                      
                      <?php 
                      $i++;
                    }
                      ?>
                    </tbody>
                  </table>
                      
                      
                      
                      
                    </div>
<?php 

if($this->action!='index'){
    ?>
<script src="<?php echo $this->basePath(); ?>/assets/js/jquery.2.1.1.min.js"></script>
<script src="<?php echo $this->basePath(); ?>/assets/js/jquery.dataTables.min.js"></script> 
<script src="<?php echo $this->basePath(); ?>/assets/js/jquery.dataTables.bootstrap.min.js"></script> 
<script src="<?php echo $this->basePath(); ?>/assets/js/dataTables.tableTools.min.js"></script> 
<script src="<?php echo $this->basePath(); ?>/assets/js/dataTables.colVis.min.js"></script>
<script src="<?php echo $this->basePath(); ?>/assets/js/table.js"></script> 
<?php
}
?>
                 