<div class="col-sm-3 col-sm-3-new width20per">
<?php echo $this->partial('layout/sidebar-about') ?>
</div>

<div class="col-sm-9 width80per">
    <h2 class="heading">About Us</h2>
<p>Rustagisamaj.com is a community website. In the Present world there is need of strong community. The original purpose of this site is to publish the profiles of all our Rustagi members with their family detail incl Child, Contact details, Education, Profession and expertise along with Photos. Matrimonial information for Bride and Groom Search, News and Events of the Rustagi Samaj including publishing photos of the event like Annual Function, Annkut , Holi Milan and other events as a free resource to anyone who may be interested. All our community people will participate and share ideas and experience and leave comments for Improvements and Grooming of Society. Later on we will add other features like information of Rustagi Samaj Branches all over India , Sub Committee Details , Family Tree, Events online   to support the growing number of visitors that are genuinely interested in contributing to the Samaj.</p>
  </div>