<div id="panel" style="display:block !important;">
	<form method="post" action="<?=$this->serverurl().$this->url()."pages/AddComment/".$posts['id'];?>" onsubmit="return validatecomment('<?=$posts['user_id']?>')">
<div class="form-group">
<textarea id="commentBodyField" required class="form-control" onkeypress="BLOG_CMT_onCommentBodyChange()" cols="50" rows="4" name="commentBody" placeholder="Enter your comment..."></textarea>
<input type="hidden" name="post_id" value="<?=$posts['id']?>">
<input type="hidden" name="user_id" value="<?=$posts['user_id']?>">
<input type="hidden" name="user_name" value="<?=$posts['user_name']?>">
</div>
<?php 
	if($posts['user_id']!=0){
		?>
<div class="form-group row">
	
<label class="col-sm-2 form-control-label lblline">Comment As</label>

<div class="col-sm-3">
	<?php
	 echo $posts['user_name']; 
	?>
</div>
</div>

<div class="form-group row">

<div class="col-sm-6">


<input id="postCommentSubmit" type="submit" class="btn btn-info" value="Publish"  name="postCommentSubmit">
<!-- <input id="postCommentPreview" type="button" class="btn btn-info" value="Preview" name="postCommentPreview"> -->
</form>
</div>
</div>
<?php
}
	else {
		?>
		</form>
		<div class="popover-markup"> 

 <a href="javascript:void(0);" class="trigger" data-placement="bottom"><?php echo $this->translate('Login to Comment') ?></a>
<div class="content hide"  >
	
<form id="loginForm" name="loginForm" action="<?php echo $this->basePath()?>/user/login" method="POST">

<div class="form-group">
<label for="email"><?php echo $this->translate('Email OR Mobile') ?></label>
<input type="text" name="login_email" id="login_email" class="form-control" />
</div>

<div class="form-group">
<label for="password"><?php echo $this->translate('Password') ?></label>
<input type="password" name="login_password" id="login_password" class="form-control" />
</div> 

<div class="form-group">
<input type="checkbox" name="rember" /><label><em><?php echo $this->translate('Remember me') ?></em></label>
</div>


<div class="form-group">
<button type="submit" name="login" id="login" class="btn btn-info btn-block"><?php echo $this->translate('Sign In') ?></button>
</div>

</form>



<div class="form-group">
<a type="submit" class="btn btn-default"><?php echo $this->translate('Forgot your password?') ?></a>
</div>

<div class="form-group text-center"><?php echo $this->translate('OR') ?></div>

<div class="form-group"><?php echo $this->translate('New account?') ?>
<a class="btn btn-info btn-block" href="<?php echo $this->basePath()?>/user/signup"><?php echo $this->translate('Signup') ?></a>

</div>


</div>
</div>
		<?php

	}
	?>

</div>


<div class="clearfix"></div>
<div class="related">

<?php 
if(count($PostComments)>0){
	foreach ($PostComments as $Comments) {
?>
<div class="col-md-12 news col-xs-12">
<div class="col-md-2 col-sm-2 col-xs-3">

<div class="related-img">
<img src="<?= empty($Comments['profile_photo'])? $this->basePath()."/img/default_user.png":$this->basePath().$Comments['profile_photo']; ?>" class="img-responsive" />
</div>
</div>
<div class="col-md-10 col-sm-10 col-xs-9 content">
<h4><?=$Comments->sender_name?> </h4>
<p> <?=$Comments->comment_desc?>  </p>
<p><a href="#">Like </a> <a href="#">Reply </a> <img src="<?php echo $this->basePath('images/liked-bg.png') ?>" style="float:leftl; padding-right:2px;"> 6</p>

</div>
</div>
<?php 
	}
}
else echo "Be the first one to comment";
?>

</div>