<div class="col-sm-3 col-sm-3-new width20per">
<?php echo $this->partial('layout/sidebar-about') ?>
</div>

<div class="col-sm-9 width80per">
    <h2 class="heading">Our History</h2>
<p>Our society today is about the history of each young man and young woman newly information. The knowledge is essential to our society. Discover the history of many years, I am making my Rustogi society. If not entirely, but it is successful I'm fairly. It should not be any doubt we cook honest Hricndra King's son Rohit 'Rohitas' have the distinction of being the son.</p>

<p>Evidence indicates festival 35-4-5 Mahabharata 'Nakul Singh' chapter meets Rohitk country which is described. Nukl to victory in the country "Pandavas" Yuhddh was quite gross. Our ancestors could not bear the weight of the troops as their families moved in three directions.</p>

<p>Kashi first detachment to the south - the first contingent of the descent on the south side from Kashi to be settled on the coast of the Sone river. After a while the state has established its strength and influence. The name of its capital, in the name of their ancestor Rohitash Rohtashw kept defenses. At that time, the ancestors rohitashv 'God' as' considered. His name was worshiped by the temple constructed. As a result, our society and the race named in his name Rohatgi, Rustogi and placed Rustugi.</p>

<p>The second contingent of Punjab - The second contingent of Punjab, Haryana shifted to the present. The name of his ancestor founded Rohtak state, which is mentioned in the Mahabharata etc. One festival. Rohtak own defenses to his rule grew our society. Even those Bsaye city name their ancestor 'Hricndra' 'name' 'Hrgiana' and the name of Rohtash called Rohtak.</p>

<p>The third detachment to Kannauj - third contingent which was shifted to the Kannauj, the fifth century 'AD' in the beginning of a big state 'Ruhtri' set. We fell after Muslim Akramanon.</p>

<p>Muslim History of Time - Rohtas Fort '' kindergarten 'Rohtak' Punjab 'Haryana Rohtri' Kannauj 'ages in the Hindu kings of the race, but for Kalachakra is very strong. Always someone there to stay. Sixteenth century, '' AD 'in the Sher Shah won his strength and courage Rohtash defenses. Rohtash septal Kshtri save their state and religion fought well.</p>
  </div>