 <div >
            <p>
              <a href="<?= $this->url('admin',array('controller'=>'state','action'=>'index'));?>"><button class="btn btn-warning btn-xlg">Go Back</button></a>
            </p>
          </div>
 
    
      <div class="portlet-body">
         <?php 

                $form=$this->form; 
                $form->prepare();


        $form->setAttribute('action',$this->url('admin',array('controller'=>'Pages','action'=>'add')));
        $form->setAttribute('method','post');
        $form->setAttribute('autocomplete','off');
        $form->setAttribute('id','PagesForm');
        $action = $this->serverUrl().$this->url().'/pages/add';
        // $form->setAttribute('onSubmit');

        echo $this->form()->openTag($form);
// echo $this->formCollection($form);
                ?>
            
            <div class="tab-pane fade active in" id="driver_tab">
              <div class="container col-sm-col-sm-offset-1" style="margin: 10px auto 0px !important;padding: 0 10px;">
                
                <div class="row" style="position:relative;z-index:1;">
                                                <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate($form->get('page_title')->getLabel()) ?>
                           </label>
                                                  <div class="col-sm-3" id="addparent" >
                                                     <?php 
                                                     echo $this->formHidden($form->get('id'));
                                                     echo $this->formElement($form->get('page_title'));
                                                     ?> 
                                                     <span class="showerror"></span>   
                                                                                    
                                                  </div>
                                                  

                                                 
                            
                                                 </div>
                                             </div>

                                             <div class="row">
                                                <div class="form-group clearfix margintopbottom20">
                          
                                                 
                             <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate($form->get('page_content')->getLabel())?>
                           </label>
                            <div class="row">
              <div class="col-xs-12">
                
                <div class="wysiwyg-editor" id="editor1"></div>

                <span class="showerror"></span>   
                 
              </div><!-- /.col -->
            </div><!-- /.row -->                
                                                 </div>
                                             </div>

                                             <div class="row">
                                                <div class="form-group clearfix margintopbottom20">
                          
                               <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate($form->get('IsActive')->getLabel()) ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo $this->formElement($form->get('IsActive'));
                                                     ?> 
                                                     <span class="showerror"></span>                                   
                                                                                        
                                                  </div>
                                                  <div class="col-sm-3" id="addparent" >
                                                     <?php 
                                                     
                                                     echo $this->formElement($form->get('page_content'));
                                                     ?> 
                                                     
                                                                                    
                                                  </div>
                                                 </div>
                                             </div>

                                             <div class="row">
                                                <div class="form-group clearfix margintopbottom20">
                                                <div class="col-sm-3 pull-right">
                                                     <?php 
                                                     echo $this->formRow($form->get('submit'));
                                                     ?>                                    
                                                  </div>
                                                   <div class="col-sm-1 pull-right">
                                                       <a class="btn btn-red defaultbtnsearch searchBooking" href="javascript:void(0);" onclick="location.reload();">Cancel</a>                              
                                                  </div>
                                             </div>
                                             </div>
              </div>
            </div>
            <?php   
echo $this->form()->closeTag();

        ?>
      </div>
    </div>
    </div>
     
  <a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse"> <i class="ace-icon fa fa-angle-double-up icon-only bigger-110"></i> </a> </div>
