<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle(' ' . $this->translate('Welcome to Rustagi Samaj'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <?php include('head.phtml'); ?>

    </head>
    <body>
        <!--Header Start-->
        <!--<div class="ad-banner">
        <div class="banner-left"><img src="images/rastogi-sabha-trust.jpg" /></div>
        <div class="banner-right"><img src="<?php echo $this->basePath('images/rastogi-sabha-trust.jpg') ?>" width="140" /></div>
        </div>-->


        <header>
            <div class="container">
                <?php include('header.phtml'); ?>
                <div class="clearfix"></div>

                <nav class="navbar navbar-default">
                    <?php include('menu.phtml'); ?>
                </nav>
                <div class="clearfix"></div>


                <div class="slider-home">
                    <?php include('slider.phtml'); ?>
                </div>

                <div class="clearfix"></div>
            </div>

        </header>
        <!--Header End-->



        <!--Container Start-->
        <div class="container orange-panelbg">
            <?php echo $this->content; ?>
        </div>
        <!--Container End-->
        <!--Footer Start-->
        <footer>
            <div class="container">
                <?php include('footer-widget.phtml'); ?>
            </div>

            <div class="clearfix">&nbsp;</div>

            <div class="copyright">
                <div class="container">
                    <?php include('footer.phtml'); ?>
                </div>
            </div>
        </footer>
        <!--Footer End-->

        <?php
        echo $this->inlineScript()
                //->prependFile($this->basePath() . '/js/mmember_filters.js')
                //->prependFile($this->basePath() . '/js/matrimony_filters.js')
                ->prependFile($this->basePath() . '/js/custom.js')
                //->prependFile($this->basePath() . '/js/element.txt')
                ->prependFile($this->basePath() . '/js/easypaginate.js')
                ->prependFile($this->basePath() . '/js/jquery_006.js')
                ->prependFile($this->basePath() . '/js/cropper.js')
                ->prependFile($this->basePath() . '/js/crop-avatar.js')
                ->prependFile($this->basePath() . '/highslide/highslide-with-gallery.js')

                //->prependFile($this->basePath() . '/js/priceranger.js')
                ->prependFile($this->basePath() . '/js/pikaday.js')  //datepicker
                ->prependFile($this->basePath() . '/js/jquery.validate.min.js')
                ->prependFile($this->basePath() . '/js/jquery.blueimp-gallery.min.js')
                //->prependFile($this->basePath() . '/js/bootstrap-image-gallery.js')
                
                ->prependFile($this->basePath() . '/js/jquery.zaccordion.js')
                ->prependFile($this->basePath() . '/js/responsiveslides.min.js')
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery.flexisel.js')
                ->prependFile($this->basePath() . '/js/jquery-ui.js')
                ->prependFile($this->basePath() . '/js/jquery-1.js')
                ->prependFile($this->basePath() . '/js/jquery-1.11.2.min.js')
                //->prependFile($this->basePath() . '/js/jquery-1.12.0.min.js')
        ;
        ?>
        <script type="text/javascript">

            $(document).ready(function () {

                $('ul#items').easyPaginate({
                    step: 16
                });

            });

            $('.popover-markup>.trigger').popover({
                html: true,
                title: function () {
                    return $(this).parent().find('.head').html();
                },
                content: function () {
                    return $(this).parent().find('.content').html();
                }
            });

            $('.collapse').on('shown.bs.collapse', function () {
                $(this).parent().find(".glyphicon-plus").removeClass("glyphicon-plus").addClass("glyphicon-minus");
            }).on('hidden.bs.collapse', function () {
                $(this).parent().find(".glyphicon-minus").removeClass("glyphicon-minus").addClass("glyphicon-plus");
            });

            $(document).ready(function () {
                $('#list').click(function (event) {
                    event.preventDefault();
                    $('#profile .commen-list').addClass('list-view');
                    $('#profile1 .commen-list').addClass('list-view');
                });
                $('#grid').click(function (event) {
                    event.preventDefault();
                    $('#profile .commen-list').removeClass('list-view');
                    $('#profile1 .commen-list').removeClass('list-view');
                    $('#profile .commen-list').addClass('grid-view');
                    $('#profile1 .commen-list').addClass('grid-view');
                });
            });



            //            $(function () {
            //                $("#slider-range").slider({
            //                    range: true,
            //                    min: 0,
            //                    max: 100,
            //                    values: [22, 50],
            //                    slide: function (event, ui) {
            //                        $("#amount").val("" + ui.values[ 0 ] + " - " + ui.values[ 1 ]);
            //                    }
            //                });
            //                $("#amount").val("" + $("#slider-range").slider("values", 0) +
            //                        " - " + $("#slider-range").slider("values", 1));
            //            });
            //
            //
            //            $(function () {
            //                $("#slider-range1").slider({
            //                    range: true,
            //                    min: 0,
            //                    max: 1000000,
            //                    values: [0, 200000],
            //                    slide: function (event, ui) {
            //                        $("#amount1").val("Rs" + ui.values[ 0 ] + " - Rs" + ui.values[ 1 ]);
            //                    }
            //                });
            //                $("#amount1").val("Rs" + $("#slider-range1").slider("values", 0) +
            //                        " - Rs" + $("#slider-range1").slider("values", 1));
            //            });


            function googleTranslateElementInit() {
                new google.translate.TranslateElement({
                    pageLanguage: 'en',
                    includedLanguages: 'en,hi',
                    autoDisplay: false,
                    layout: google.translate.TranslateElement.InlineLayout.SIMPLE
                }, 'google_translate_element');
            }




            $(document).ready(function () {
                $("#bs-example-navbar-collapse-1 ul li:first").addClass('active');
                setNavigation();
                setSidebarNavigation();



                $("#Female").click(function () {
                    $("#profile1").show();
                    $("#profile").hide();
                    var count_checked = $("[name='matrimony_gender[]']:checked").length; // count the checked rows
                    if (count_checked == 0)
                    {

                        alert("Please select at leasst one record.");
                        return false;
                    }
                    if (count_checked == 1) {
                        //alert("Record Selected:"+count_checked);
                        $('#brides').hide();
                        $('#grooms').show();

                    } else {
                        // alert("Record Selected:"+count_checked);
                        $('#brides').show();
                        $('#grooms').show();
                    }
                });

                $("#Male").click(function () {
                    $("#profile1").show();
                    $("#profile").hide();
                    //debugger;
                    var count_checked = $("[name='matrimony_gender[]']:checked").length; // count the checked rows
                    if (count_checked == 0)
                    {
                        alert("Please select at least one record.");

                        return false;
                    }
                    if (count_checked == 1) {
                        // alert("Record Selected:"+count_checked);
                        $('#brides').show();
                        $('#grooms').hide();
                    } else {
                        // alert("Record Selected:"+count_checked);
                        $('#brides').show();
                        $('#grooms').show();
                    }
                });


            });

            /*function ShowHideDiv(groomcheck) {
             var grooms = document.getElementById("grooms");
             grooms.style.display = groomcheck.checked ? "block" : "none";
             }
             
             function ShowHideDiv1(bridescheck) {
             var brides = document.getElementById("brides");
             brides.style.display = bridescheck.checked ? "block" : "none";
             }*/


            function setNavigation() {
                var path = window.location.pathname;
                path = path.replace(/\/$/, "");
                path = decodeURIComponent(path);

                $("#bs-example-navbar-collapse-1 ul li a").each(function () {
                    var href = $(this).attr('href');
                    if (path.substring(0, href.length) === href) {
                        $("#bs-example-navbar-collapse-1 ul li:first").removeClass('active');
                        $(this).closest('li').addClass('active');
                    }
                });
            }
            function setSidebarNavigation() {
                var path = window.location.pathname;
                path = path.replace(/\/$/, "");
                path = decodeURIComponent(path);

                $("#bs-example-navbar-collapse-2 ul li a").each(function () {
                    var href = $(this).attr('href');
                    if (path.substring(0, href.length) === href) {
                        $("#bs-example-navbar-collapse-2 ul li:first").removeClass('active');
                        $(this).closest('li').addClass('active');
                    }
                });

            }
        </script>
    </body>
</html>
