<nav class="navbar navbar-default">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2" aria-expanded="false">
        <span class="sr-only">Sub Page</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">

<!--<ul class="nav navbar-nav">-->
<!--<li><a href="<?php echo $this->basePath()?>/pages/history"><?php echo $this->translate('History') ?></a></li>
<li><a href="<?php echo $this->basePath()?>/pages/team"><?php echo $this->translate('Team Member') ?></a></li>
<li><a href="<?php echo $this->basePath()?>/pages/vision"><?php echo $this->translate('Our Vision') ?></a></li>
<li><a href="<?php echo $this->basePath()?>/pages/communities"><?php echo $this->translate('Other Rustagi Institutions') ?></a></li>-->	
<!--<li><a href="<?php //echo $this->basePath()?>/pages/branches"><?php //echo $this->translate('All India Branches') ?></a></li>-->
<!--</ul>-->

</div>
</nav>

<?php echo $this->partial('layout/sidebar-slider') ?>