<div class="panel-group" id="Newsaccordion">
 
<div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title"><span class="filter-heading">Filter</span></h4>
    </div>
  </div><form method="post" action="" onsubmit="return newsdatevalidate();">
  <div class="panel panel-default">
    <div class="panel-heading">
     <div class="filter">
	 <div class="col-xs-12" style="padding:0;">
     <label>From</label>
     
    <input type="text" name="dob" class="form-control inputDate" id="dob" />
    
	 </div>
	 
	 <div class="col-xs-12" style="padding:0;" >
     <label>To</label>
      <input type="text" name="dob1" class="form-control inputDate" id="dob1" />
	 </div>
     <div class="col-xs-12" style="padding:0; margin-top:5px;">
     
      <input type="submit" class="btn btn-default" value="Search" />
    
	 </div>
     </div>
    </div>
  </div>
  </form>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
        <span class="pull-right glyphicon glyphicon-plus"></span>Categories</a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse in">
      <div class="panel-body" id="newsForm">
      <ul>
        <?php 
        foreach($filters_data["news_category_id"] as $grdata)
        {
      
          echo '<li><input type="checkbox" name="news_category[]" value="'.$grdata->id.'"><label>'.$grdata->category_name.'</label></li>';
        }
        ?>

</ul>
      </div>
    </div>
  </div>
  
  
  
</div>

<?php echo $this->partial('layout/sidebar-slider') ?>

<script>
     var obj = new Date();
     var curr_year = obj.getFullYear();
	 var curr_month = obj.getMonth();
	 var curr_date = obj.getDate();    
    var picker = new Pikaday(
    {
        field: document.getElementById('dob'),
        firstDay: 1,
        minDate: new Date(1801, 0, 1),
        maxDate: new Date(curr_year, curr_month, curr_date),
        yearRange: [1801,curr_year],
		format:'DD-MM-YYYY',
		formatStrict: false
    });

      </script>
      
      <script>
     var obj = new Date();
     var curr_year = obj.getFullYear();
	 var curr_month = obj.getMonth();
	 var curr_date = obj.getDate();    
    var picker = new Pikaday(
    {
        field: document.getElementById('dob1'),
        firstDay: 1,
        minDate: new Date(1801, 0, 1),
        maxDate: new Date(curr_year, curr_month, curr_date),
        yearRange: [1801,curr_year],
		format:'DD-MM-YYYY',
		formatStrict: false
    });

      </script>