<nav class="navbar navbar-default">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2" aria-expanded="false">
        <span class="sr-only">Sub Page</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
<ul class="nav navbar-nav">
<li><a href="<?php echo $this->basePath()?>/pages/about">About Community</a></li>
<li><a href="<?php echo $this->basePath()?>/matrimonial/index">Bride Groom Search</a></li>
<li><a href="<?php echo $this->basePath()?>/matrimonial/list-view?search_for=Female">Browse All Brides</a></li>
<li><a href="<?php echo $this->basePath()?>/matrimonial/list-view?search_for=Male">Browse All Grooms</a></li>
<li><a href="<?php echo $this->basePath()?>/pages/postcat/6">Health &amp; Food</a></li>
<li><a href="<?php echo $this->basePath()?>/pages/postcat/7">Devotional / Mythology</a></li>
<li><a href="<?php echo $this->basePath()?>/pages/entertain">Jokes / SMS / Poems</a></li>
<li><a href="<?php echo $this->basePath()?>/events">All Events</a></li>
<li><a href="<?php echo $this->basePath()?>/community">All India Branches</a></li>
</ul>
</div>
</nav>

<?php echo $this->partial('layout/sidebar-slider') ?>