<div class="col-xs-2 col-xs-2-new">
<div id="myCarousel" class="carousel slide" data-ride="carousel"> 
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
<div class="carousel-inner">
<div class="item active"><img src="<?php echo $this->basePath('images/harish_1.jpg') ?>" class="img-responsive" alt="First slide"></div>
<div class="item"><img src="<?php echo $this->basePath('images/slide1.jpg') ?>" class="img-responsive" alt="Second slide"></div>
<div class="item"><img src="<?php echo $this->basePath('images/harish_3.jpg') ?>" class="img-responsive" alt="Third slide"></div>
</div>
  <a class="left carousel-control" href="#myCarousel" data-slide="prev"></a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next"></a>
</div>
</div>
<div class="col-xs-9 col-xs-9-new">
<ul id="zaccordion">
<li><a href="http://www.asian-tours.com/" target="_blank" class="btn btn-info">
<img src="<?php echo $this->basePath('images/regency_package.jpg') ?>" class="img-responsive" alt="" /></a>
<div class="caption">
<a href="http://www.asian-tours.com/" target="_blank" class="btn btn-info" style="  margin: 5px 0 0 0;">More...</a>
<p>Booking Call 011-47474700 OR obt@regencytours.in, www.asian-tours.com.</p>
</div>
</li>
<li><a href="http://hello42cab.com/" target="_blank" class="btn btn-info"><img src="<?php echo $this->basePath('images/hello42_banner.jpg') ?>" class="img-responsive" alt="" /></a>
<div class="caption">
<a href="http://hello42cab.com/" target="_blank" class="btn btn-info" style="  margin: 5px 0 0 0;">More...</a>
<p>Booking Call 011-42424242 OR www.hello42cab.com.<br />
<br />
</p>
</div>
</li>
<li><a href="http://www.asian-tours.com/" target="_blank" class="btn btn-info" >
<img src="<?php echo $this->basePath('images/regency_banner.jpg') ?>" class="img-responsive" alt="" /></a>
<div class="caption">
<a href="http://www.asian-tours.com/" target="_blank" class="btn btn-info" style="  margin: 5px 0 0 0;">More...</a>
<p>Booking Call 011-47474700 OR obt@regencytours.in, www.asian-tours.com.</p>
</div>
</li>
</ul>
</div>