	
                    <div class="table-responsive">
                      <table id="dynamic-table" class="table table-striped table-bordered table-hover">
                    <thead>
                      <tr>
                         <th><input type="checkbox" value="" id="checkAll" onclick="checkall(this.id)" > </th>
                         <th> Sr. No. </th>
                         
                        <th class="hidden-480">City Name</th>
                        <th class="hidden-480">State Name</th>
                        <th class="hidden-480">Modified Date</th>
                        <th class="hidden-480">Created Date</th>
                        
                        <th class="hidden-480">Modified By</th>
                        <th class="hidden-480">Status</th>
                        <th><b>Actions</b></th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php 
					   $i=1;
                      foreach ($cities as $city) {
//                          echo   "<pre>";
//                          echo  "hi amir";
//                          print_r($cities);die;
                      
                      ?>
                      <tr>
                      
                        
                      
                        <td><input type="checkbox" value="<?=$city->id?>" class="checkme" name="checkme[]"> </td> 
                        <td> <?=$i?></td>
                       
                        <td class="hidden-480"><?= $city->cityName?></td>                       
                        <td class="hidden-480"><?= $city->stateName?></td>
                        <td class="hidden-480"><?= $city->modifiedDate?></td>
                        <td class="hidden-480"><?= $city->createdDate?></td>                        
                        
                        <td class="hidden-480"><?php echo ($city->modifiedBy==1)? 'Admin': 'NotByAdmin'; ?></td>
                        
                        <td class="hidden-480" align="center">
												
						<?php $status = ($city->isActive==1)? 'Active': 'In-Active';
                        $statuscolor = ($city->isActive==1)? 'activestatus': 'de-activestatus';
                         ?>
                          <div name="ChangeStatus" id="changestatus<?=$i;?>" onclick="changestatusquick(<?=$city->id?>,<?= ($city->isActive==0)?0:1; ?>,'<?php echo $this->
                                                                url('admin/city', array('action'=>
                                                                    'changestatus')); ?>',changstatusresult);" class="<?=$statuscolor?>">
                        </div>
						
						<!--<?php echo ($city->IsActive==1)? 'Active': '<span class="label label-sm label-warning">In-Active</span>'; ?>--></td>
                        <td class="hidden-480">
                        <div class="hidden-sm hidden-xs action-buttons"> 
                       <!-- <a class="blue" href="<?php echo $this->url('admin',array('controller'=>'city','action'=>'view','id'=>$city->id)); ?>"> 
                        <i class="ace-icon fa fa-search-plus bigger-130"></i> </a> -->
                        
                        <a class="blue" style="cursor:pointer;" data-toggle="modal" data-target="#myModal" tar="indview<?=$i?>
                            "> <i onclick="findRowDataByCityId('<?php echo $this->url
                                                           ('admin/city', array('action'=>'viewById','id'=>$city->id)); ?>', 
                                                                       viewRowDataById);" class="ace-icon fa fa-search-plus bigger-130">
                                                    </i> </a>
                        
                        <a class="green" href="javascript:void(0);" onclick="editbox(<?= $city->id ?>, '<?php echo 
                                        $this->url('admin/city', array('action' => 'edit', 'id' => $city->id));
                                        ?>', editformresp);" > <i class="ace-icon fa fa-pencil bigger-130"></i> </a> <a class="red" href="<?php echo $this->url('admin/city',array('action'=>'delete','id'=>$city->id)); ?>" onclick="return confirm('are you sure you want to delete');"> <i class="ace-icon fa fa-trash-o bigger-130"></i> </a> </div>
                          </td>
                      </tr>
                      
                      
                      
                      
                      <?php 
                      $i++;
                    }
                      ?>
                    </tbody>
                  </table>
                      
                      
                      
                      
                    </div>


<?php 

if($this->action!='index'){
    ?>
<script src="<?php echo $this->basePath(); ?>/assets/js/jquery.2.1.1.min.js"></script>
<script src="<?php echo $this->basePath(); ?>/assets/js/jquery.dataTables.min.js"></script> 
<script src="<?php echo $this->basePath(); ?>/assets/js/jquery.dataTables.bootstrap.min.js"></script> 
<script src="<?php echo $this->basePath(); ?>/assets/js/dataTables.tableTools.min.js"></script> 
<script src="<?php echo $this->basePath(); ?>/assets/js/dataTables.colVis.min.js"></script>
<script src="<?php echo $this->basePath(); ?>/assets/js/table.js"></script> 
<?php
}
?>
                