
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Modal Header</h4>
      </div>
      <div class="modal-body">
            <tr class="dontshow" id="indview<?=$i?>" aria-expanded="true">
                     
                	<td colspan="7">
                    <div aria-expanded="true" class="panel-body accordion-body packageDetails1 collapse in" id="accordion1">
               
                          <div class="tab-content" id="myTabContent">
        
              <div style="margin: 10px auto 0px !important;padding: 0 10px;" class="col-sm-col-sm-offset-1">
                <div class="row">
                   <div class="form-group clearfix margintopbottom20 ">
                           <label class="col-sm-2 control-label labelalign " id="flight_nos">
                            <?= $this->translate('City Name'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     
                                                     echo $info->cityName;
                                                     ?>                                    
                                                  </div>
                           <label class="col-sm-2 control-label labelalign " id="flight_nos">
                            <?= $this->translate('State Name'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo $info->stateName;
                                                     ?>                                    
                                                  </div>
                                                 </div>
                                             </div>
                                             <div class="row">
                                                <div class="form-group clearfix margintopbottom20 col-sm-12">
                        <label class="col-sm-2 control-label labelalign " id="flight_nos">
                            <?= $this->translate('Modified By'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo ($info->modifiedBy==1)?'Admin':'Not Available Now';
                                                     ?>                                    
                                                  </div>
                                                 
                            <label class="col-sm-2 control-label labelalign " id="flight_nos">
                            <?= $this->translate('Status'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo ($info->isActive==1)? 'Active':'In-Active';
                                                     ?>                                    
                                                  </div>
                                                 </div>
                                             </div>

                                          <div class="row">
                                                <div class="form-group clearfix margintopbottom20 col-sm-12">
                          <label class="col-sm-2 control-label labelalign " id="flight_nos">
                            <?= $this->translate('Created Date'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo date('l d-m-Y',strtotime($info->createdDate));
                                                     ?>                                    
                                                  </div>
                                                 
                            <label class="col-sm-2 control-label labelalign " id="flight_nos">
                            <?= $this->translate('Modified Date'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo date('l d-m-Y',strtotime($info->modifiedDate));
                                                     ?>                                    
                                                  </div>
                                                 </div>
                                             </div>  
                                             
              </div>
           
          </div>
      </div>
                    
                                             
                       </td>
                    </tr>     
      </div>
      <div class="modal-footer">
        <button type="button"data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
            
           