<div class="col-sm-3 col-sm-3-new width20per">
<?php echo $this->partial('layout/sidebar-news') ?>
</div>


<div class="col-sm-9 width80per">

<h2 class="heading">All Listings for Just Born Beby</h2>

<div class="col-md-6 news col-xs-12">
<div class="col-md-3 col-sm-2 col-xs-2 img">
<img src="<?php echo $this->basePath('images/beby.jpg') ?>" class="img-responsive" />
</div>
<div class="col-md-9 col-sm-10 col-xs-10 content">
<h4>Aditya Rastogi</h4>
<p>I was blessed by a baby boy...<br><a href="<?php echo $this->basePath()?>/justborn/view">Read Full Story >></a></p>
<p></p>

Sender: krishrastogi3@gmail.com<br>
Posted Date: 2013-12-24 16:54:06
</div>
</div>

<div class="col-md-6 news col-xs-12">
<div class="col-md-3 col-sm-2 col-xs-2 img">
<img src="<?php echo $this->basePath('images/beby.jpg') ?>" class="img-responsive" />
</div>
<div class="col-md-9 col-sm-10 col-xs-10 content">
<h4>Aditya Rastogi</h4>
<p>I was blessed by a baby boy...<br><a href="<?php echo $this->basePath()?>/justborn/view">Read Full Story >></a></p>
<p></p>

Sender: krishrastogi3@gmail.com<br>
Posted Date: 2013-12-24 16:54:06
</div>
</div>

<div class="col-md-6 news col-xs-12">
<div class="col-md-3 col-sm-2 col-xs-2 img">
<img src="<?php echo $this->basePath('images/beby.jpg') ?>" class="img-responsive" />
</div>
<div class="col-md-9 col-sm-10 col-xs-10 content">
<h4>Aditya Rastogi</h4>
<p>I was blessed by a baby boy...<br><a href="<?php echo $this->basePath()?>/justborn/view">Read Full Story >></a></p>
<p></p>

Sender: krishrastogi3@gmail.com<br>
Posted Date: 2013-12-24 16:54:06
</div>
</div>

<div class="col-md-6 news col-xs-12">
<div class="col-md-3 col-sm-2 col-xs-2 img">
<img src="<?php echo $this->basePath('images/beby.jpg') ?>" class="img-responsive" />
</div>
<div class="col-md-9 col-sm-10 col-xs-10 content">
<h4>Aditya Rastogi</h4>
<p>I was blessed by a baby boy...<br><a href="<?php echo $this->basePath()?>/justborn/view">Read Full Story >></a></p>
<p></p>

Sender: krishrastogi3@gmail.com<br>
Posted Date: 2013-12-24 16:54:06
</div>
</div>
<!--
<div class="col-md-6 news col-xs-12">
<div class="col-md-3 col-sm-2 col-xs-2 img">
<img src="<?php echo $this->basePath('images/onside.jpg') ?>" class="img-responsive" />
</div>
<div class="col-md-9 col-sm-10 col-xs-10 content">
<h4>What is Lorem Ipsum</h4>
<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy</p>
<p><a href="<?php echo $this->basePath()?>/posts/view">Read Full Story >></a></p>
</div>
</div>

<div class="col-md-6 news col-xs-12">
<div class="col-md-3 col-sm-2 col-xs-2 img">
<img src="<?php echo $this->basePath('images/onside.jpg') ?>" class="img-responsive" />
</div>
<div class="col-md-9 col-sm-10 col-xs-10 content">
<h4>What is Lorem Ipsum</h4>
<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy</p>
<p><a href="<?php echo $this->basePath()?>/posts/view">Read Full Story >></a></p>
</div>
</div>

<div class="col-md-6 news col-xs-12">
<div class="col-md-3 col-sm-2 col-xs-2 img">
<img src="<?php echo $this->basePath('images/onside.jpg') ?>" class="img-responsive" />
</div>
<div class="col-md-9 col-sm-10 col-xs-10 content">
<h4>What is Lorem Ipsum</h4>
<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy</p>
<p><a href="<?php echo $this->basePath()?>/posts/view">Read Full Story >></a></p>
</div>
</div>

<div class="col-md-6 news col-xs-12">
<div class="col-md-3 col-sm-2 col-xs-2 img">
<img src="<?php echo $this->basePath('images/onside.jpg') ?>" class="img-responsive" />
</div>
<div class="col-md-9 col-sm-10 col-xs-10 content">
<h4>What is Lorem Ipsum</h4>
<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy</p>
<p><a href="<?php echo $this->basePath()?>/posts/view">Read Full Story >></a></p>
</div>
</div>

<div class="col-md-6 news col-xs-12">
<div class="col-md-3 col-sm-2 col-xs-2 img">
<img src="<?php echo $this->basePath('images/onside.jpg') ?>" class="img-responsive" />
</div>
<div class="col-md-9 col-sm-10 col-xs-10 content">
<h4>What is Lorem Ipsum</h4>
<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy</p>
<p><a href="<?php echo $this->basePath()?>/posts/view">Read Full Story >></a></p>
</div>
</div>

<div class="col-md-6 news col-xs-12">
<div class="col-md-3 col-sm-2 col-xs-2 img">
<img src="<?php echo $this->basePath('images/onside.jpg') ?>" class="img-responsive" />
</div>
<div class="col-md-9 col-sm-10 col-xs-10 content">
<h4>What is Lorem Ipsum</h4>
<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy</p>
<p><a href="<?php echo $this->basePath()?>/posts/view">Read Full Story >></a></p>
</div>
</div>

<div class="col-md-6 news col-xs-12">
<div class="col-md-3 col-sm-2 col-xs-2 img">
<img src="<?php echo $this->basePath('images/onside.jpg') ?>" class="img-responsive" />
</div>
<div class="col-md-9 col-sm-10 col-xs-10 content">
<h4>What is Lorem Ipsum</h4>
<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy</p>
<p><a href="<?php echo $this->basePath()?>/posts/view">Read Full Story >></a></p>
</div>
</div>

<div class="col-md-6 news col-xs-12">
<div class="col-md-3 col-sm-2 col-xs-2 img">
<img src="<?php echo $this->basePath('images/onside.jpg') ?>" class="img-responsive" />
</div>
<div class="col-md-9 col-sm-10 col-xs-10 content">
<h4>What is Lorem Ipsum</h4>
<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy</p>
<p><a href="<?php echo $this->basePath()?>/posts/view">Read Full Story >></a></p>
</div>
</div>

<div class="col-md-6 news col-xs-12">
<div class="col-md-3 col-sm-2 col-xs-2 img">
<img src="<?php echo $this->basePath('images/onside.jpg') ?>" class="img-responsive" />
</div>
<div class="col-md-9 col-sm-10 col-xs-10 content">
<h4>What is Lorem Ipsum</h4>
<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy</p>
<p><a href="<?php echo $this->basePath()?>/posts/view">Read Full Story >></a></p>
</div>
</div>

<div class="col-md-6 news col-xs-12">
<div class="col-md-3 col-sm-2 col-xs-2 img">
<img src="<?php echo $this->basePath('images/onside.jpg') ?>" class="img-responsive" />
</div>
<div class="col-md-9 col-sm-10 col-xs-10 content">
<h4>What is Lorem Ipsum</h4>
<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy</p>
<p><a href="<?php echo $this->basePath()?>/posts/view">Read Full Story >></a></p>
</div>
</div>-->

<div class="clearfix"></div>

<nav>
  <ul class="pagination">
  <li class="disabled"><a href="#">Pages:</a></li>
    <li><a href="#">1</a></li>
    <li><a href="#">2</a></li>
    <li><a href="#">3</a></li>
    <li><a href="#">4</a></li>
    <li><a href="#">5</a></li>
    <li><a href="#">6</a></li>
    <li><a href="#">7</a></li>
    <li class="disabled"><a href="#">.....</a></li>
    
  </ul>
</nav>
<div class="clearfix"></div>
</div>
