


<?php 

// foreach ($newscategorys as $newscategory) {

// echo  $newscategory->religion_name."<br>";

// }

// echo "<pre>";
// print_r($newscategorys);
// die;

?>
<div class="row">
          <div class="col-xs-12"> 
            <!-- PAGE CONTENT BEGINS -->
            <div class="alert alert-block alert-success">
              <button type="button" class="close" data-dismiss="alert"> <i class="ace-icon fa fa-times"></i> </button>
              <i class="ace-icon fa fa-check green"></i>Add Country Master</strong>, </div>
            <div class="row">
              <div class="space-6"></div>
              <div class="vspace-12-sm"></div>
            </div>
            <div class="row">
              <div class="col-xs-12">
                <h3  >Add Country Master</h3>
                <div class="filter">
                  <div class="col-lg-6">View Records>></div>
                </div>
                <div class="portlet-body">
                  <form id="bookingFilter">
                    <div id="myTabContent" class="tab-content">
                      <div class="tab-pane fade active in" id="home">
                        <div class="col-sm-col-sm-offset-1" style="margin: 10px auto 0px !important;padding: 0 10px;">
                          <div class="row">
                                                <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">Country</label>
                                                  <div class="col-sm-3 ">
                                                     <input id="Classic Dance" class=" form-control inputchange" placeholder="India" type="text">                                    
                                                  </div>
                                                 
                            <label id="point_airport" class="col-sm-2 control-label labelalign ">*Mandatory Fileds
</label>
                                                   <div class="col-sm-3">
                                                     <input id="Karol Bagh" class=" form-control inputchange" placeholder="" type="text"> 
                                                  </div>
                                                 </div>
                                             </div>
                          

                          
                          <div class="row">
                            <div class="form-group clearfix margintopbottom20">
                              <div class="col-sm-4 pull-right"> <a href="#" class="btn btn-red defaultbtnsearch searchBooking"><i class="fa fa-search" id="search_me" style="color:#fff; margin:5px"></i>Search</a> </div>
                            </div>
                          </div>
                        </div>
                      </div>

                    </div>
                  </form>
   
                </div>
                
                 
                  <div class="filter">
                  <div class="col-lg-6">Add Update Records>>
  
                  </div>
   
                </div>
                
                    <div class="clearfix"></div>
                  
                <div class="col-lg-6" style="background-color:#FFF;">
                  
                  <div class="col-lg-4"><div class="radio">
                                                <label>
                                                    <input type="radio" checked="" value="option1" id="optionsRadios1" name="optionsRadios"><strong>Active</strong>
                                                </label>
                                                <br>
 
                                            </div>
                  
                  
                  
                  
                  </div>
                  
                  
                   <div class="col-lg-4"><div class="radio">
                                                <label>
                                                    <input type="radio" checked="" value="option1" id="optionsRadios1" name="optionsRadios"><strong>In-Active</strong>
                                                </label>
                                                
                                              
                                            </div>
                  
                  
                  
                  
                  </div>
                  </div>
                <div class="col-md-12">
                    <div class="table-responsive">
                      <table id="dynamic-table" class="table table-striped table-bordered table-hover">
                    <thead>
                      <tr>
                         
                        
                        <th>Sr.No.</th>
                        <th>Category Name</th>
                        <th class="hidden-480">Modified Date</th>
                        <th class="hidden-480">Created Date</th>
                        <th class="hidden-480">Status</th>
                        <th class="hidden-480">Modified By</th>
                        <th><b>Actions</b></th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php 
                      $i=1;
                      foreach ($newscategories as $newscategory) {
                      
                      ?>
                      <tr>
                         
                       
                        <td><?= $i?></td>                       
                        <td><?= $newscategory->category_name?></td>                       
                        <td class="hidden-480"><?= date('l d-m-y',strtotime($newscategory->created_date))?></td>
                        <td class="hidden-480"><?= date('l d-m-y',strtotime($newscategory->modified_date))?></td>
                        <td class="hidden-480"><?php echo ($newscategory->IsActive==1)? 'Active': '<span class="label label-sm label-warning">In-Active</span>'; ?></td>
                        <td class="hidden-480"><?php echo ($newscategory->modified_by==1)? 'Admin': 'NotByAdmin'; ?></td>
                        <td><div class="hidden-sm hidden-xs action-buttons"> <a class="blue" href="<?php echo $this->url('admin',array('controller'=>'news','action'=>'viewnewscategory','id'=>$newscategory->id)); ?>"> <i class="ace-icon fa fa-search-plus bigger-130"></i> </a> <a class="green" href="<?php echo $this->url('admin',array('controller'=>'news','action'=>'editnewscategory','id'=>$newscategory->id)); ?>" > <i class="ace-icon fa fa-pencil bigger-130"></i> </a> <a class="red" href="<?php echo $this->url('admin',array('controller'=>'news','action'=>'deletenewscategory','id'=>$newscategory->id)); ?>" onclick="return confirm('are you sure you want to delete');"> <i class="ace-icon fa fa-trash-o bigger-130"></i> </a> </div>
                          </td>
                      </tr>
                      <?php 
                      $i++;
                    }
                      ?>
                    </tbody>
                  </table>
                      
                      
                      
                      
                    </div>
                 </div>
              </div>
              
              
              
              
              
              <div class="col-sm-12"> 
                
                <!-- /.widget-box -->
                <!--<div  style="margin-top:20px;"> <a href="#" class="btn btn-red defaultbtnsearch searchBooking"><i class="fa fa-search" id="search_me" style="color:#fff; margin:5px"></i>Refresh</a> </div>-->
              </div>
            </div>
            <!-- /.col --> 
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Modal Header</h4>
      </div>
      <div class="modal-body">
            <?php 

        // print_r($countries);

        ?>         
      </div>
      <div class="modal-footer">
        <button type="button"data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
            
            <!-- /.row -->
            
            <div class="hr hr-18 dotted hr-double"></div>
            <div class="row">
              <div class="col-xs-12">
                
                <div> 
         
      </div>
      <!-- /.page-content --> 
    </div>
  </div>
  <!-- /.main-content -->
  
     
  <a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse"> <i class="ace-icon fa fa-angle-double-up icon-only bigger-110"></i> </a> </div>
<!-- /.main-container --> 

<!-- basic scripts --> 

<!--[if !IE]> -->