                    <div class="table-responsive">
                      <table id="dynamic-table" class="table table-striped table-bordered table-hover">
                    <thead>
                      <tr>
                         
                        
                        <th>Sr.No.</th>
                        <th>Category Name</th>
                        <th class="hidden-480">Created Date</th>
                        <th class="hidden-480">Modified Date</th>                        
                        <th class="hidden-480">Status</th>
                        <th class="hidden-480">Modified By</th>
                        <th><b>Actions</b></th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php 
                      $i=1;
                      foreach ($results as $newscategory) {
                      
                      ?>
                      <tr>
                         
                       
                        <td><?= $i?></td>                       
                        <td><?= $newscategory->categoryName?></td>                       
                        <td class="hidden-480"><?= $newscategory->createdDate;?></td>
                        <td class="hidden-480"><?= $newscategory->modifiedDate;?></td>
                        <td class="hidden-480"><?php echo ($newscategory->isActive==1)? 'Active': '<span class="label label-sm label-warning">In-Active</span>'; ?></td>
                        <td class="hidden-480"><?php echo ($newscategory->modifiedBy==1)? 'Admin': 'NotByAdmin'; ?></td>
                        <td><div class="hidden-sm hidden-xs action-buttons"> <a class="blue" href="<?php echo $this->url('admin/news',array('action'=>'viewnewscategory','id'=>$newscategory->id)); ?>"> <i class="ace-icon fa fa-search-plus bigger-130"></i> </a> <a class="green" href="<?php echo $this->url('admin/news',array('action'=>'editnewscategory','id'=>$newscategory->id)); ?>" > <i class="ace-icon fa fa-pencil bigger-130"></i> </a> <a class="red" href="<?php echo $this->url('admin/news',array('action'=>'deletenewscategory','id'=>$newscategory->id)); ?>" onclick="return confirm('are you sure you want to delete');"> <i class="ace-icon fa fa-trash-o bigger-130"></i> </a> </div>
                          </td>
                      </tr>
                      <?php 
                      $i++;
                    }
                      ?>
                    </tbody>
                  </table>
                      
                      
                      
                      
                    </div>
                
    