 <?php 

// print_r($Info->username);die;
 ?>
 <div >
            <p>
              <a href="<?= $this->url('admin',array('controller'=>'news','action'=>'indexnews'));?>"><button class="btn btn-warning btn-xlg">Go Back</button></a>
            </p>
          </div>
<div class="alert alert-block alert-success">
    <button type="button" class="close" data-dismiss="alert"> <i class="ace-icon fa fa-times"></i> </button>
    <i class="ace-icon fa fa-check green"></i><?= $Info->titile?></strong>, </div>
  <h2>What is Lorem Ipsum</h2>
  <div class="row">
    <div class="col-xs-12">
      <p class="pull-left newsimg"  ><?php $imagePath = (empty($Info->image_path))?'/images/new-big.jpg' : $Info->image_path;?><img src="<?= $this->basepath().$imagePath;?>" width="257"  height="257" alt=""></p>
      <p style="padding-left:20px"><?= $Info->description; ?>
      </p>
      
    </div>
  </div>
  
  <div class="clearfix"></div>
  
  
  <div class="timeline-body alert-success2">
                     Posted By : <?= $Info->username ;?> |
                   Posted Date : <?= date("l d-m-y",strtotime($Info->created_date)); ?> | 

                   Category Name : <?= ($Info->category_name); ?> 

                      
                    </div>