<div class="container">
    <div class="row" align="center">
        <div class="col-sm-6" align="center" style="float:none !important;">

            <form role="form" action="" method="post">
                <div class="form-group">
                    <div class="modal-header">

                        <h2 class="modal-title" id="myModalLabel">Login</h2>
                    </div>
                    <div class="modal-body">

                        <div class="col-sm-12">
                            Email OR Mobile
                            <input type="text" name="login_email" id="login_email" class="form-control" />
                        </div>
                        <div class="col-sm-12">
                            Password
                            <input type="password" name="login_password" id="login_password" class="form-control" />
                        </div>

                        <div class="col-sm-12">

                            <input type="checkbox" name="rember" /><em>Remember me</em>
                        </div>

                        <div class="col-sm-12">

                            <button type="submit" name="login" id="login" class="btn btn-default btn-block popuplogingbut">Sign In</button>
                        </div>

                        <div class="col-sm-12">
                            <a type="submit" class="">Forgot your password?</a>
                        </div>

                        <div class="col-sm-12 text-center">OR</div>

                        <div class="col-sm-12">New account 
                            <a class="btn btn-default btn-block popuplogingbut" href="<?php echo $this->basePath() ?>/user/signup"><?php echo $this->translate('Signup') ?></a>

                        </div>

                        <div class="col-sm-12 text-center"> </div>  

                    </div>
                    <div class="clearfix"></div>
                    <div class="modal-footer">

                    </div>
                </div>
            </form>
        </div> 
    </div>

</div>

