<?php 
if(isset($message) && !empty($message)){
  $disp = "display:block;";
}
else $disp = "display:none;";
?>

 <div class="alert alert-block alert-success" style="<?=$disp?>">
              <button type="button" class="close" data-dismiss="alert"> <i class="ace-icon fa fa-times"></i> </button>
              <i class="ace-icon fa fa-check green"></i> Mail sent successfully . We will get back to you within 24 hrs. Thank you </div>

<div class="col-sm-3 col-sm-3-new width20per">
<div class="panel-group" id="contacts_accordion">
<div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title"><span class="filter-heading">Find Us Here</span></h4>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
     <div class="filter">
      <form method="post" action="" onsubmit="return fetchcontacts();">
     <ul class="newulclass">
  <li>
      <select class="form-control" name="contact_filter[]" id="country" ftype="country">
        <option value="0">---Select---country---</option>
        <?php 
          foreach($filters_data["country"] as $GrData)
            {
                echo "<option value=".$GrData->id.">".$GrData->country_name."</option>";
            }
        ?>
      </select>
  </li>
</ul>
      <ul class="newulclass">
<li><select class="form-control" ftype="state" id="state" name="contact_filter[]">
    <option value="0">---Select---state---</option>
        <?php 
          foreach($filters_data["state"] as $GrData)
            {
                echo "<option value=".$GrData->id.">".$GrData->state_name."</option>";
            }
        ?>
</select></li>
</ul>
      <ul class="newulclass">
        <li>      
  <select class="form-control" ftype="city" id="city" name="contact_filter[]" >
       <option value="0">---Select---city---</option>   
    <?php 
          foreach($filters_data["city"] as $GrData)
            {
                echo "<option value=".$GrData->id.">".$GrData->city_name."</option>";
            }
        ?>
        
  </select>
</li>
</ul>
     <button class="btn btn-default" data-toggle="modal" data-target="#myModal">Submit</button>
     </form>
     <div class="clearfix"></div>
     </div>
    </div>
  </div>
  <?php echo $this->partial('layout/sidebar-slider') ?>  
  <!-- Create New Start popup -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-dialogcnt" role="document">
    <div class="modal-content gnt-pad15">
      <form role="form">
   		<div class="form-group">
        <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h2 class="modal-title" id="myModalLabel">Country/State/City</h2>
      </div>
      <div class="modal-body">
      <div class="col-md-3 col-sm-6 col-xs-6">
       <h3>Rustagi Sabha Rohini-Pitampura Kshetra (Regd.)</h3>
       <p>C-384, Saraswati Vihar, Delhi-110034</p>
       <p>Tel: 011-23670278</p>
       <p>Email: info@rustagisabharohini.com</p>
       </div>
      </div>
      <div class="clearfix"></div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal" aria-label="Close">Close</button>
      </div>
      </div>
        </form>
    </div>
  </div>
</div>
<!-- Create New End popup -->
  
</div>



</div>

<div class="col-sm-9 width80per">

<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3499.644905308578!2d77.1230953501846!3d28.70026698767747!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390d03e75448376f%3A0x5fda4d9cccb774f2!2sRustagi+Sabha+Rohini%2C+C-384%2C+Outer+Ring+Rd%2C+Block+C%2C+Saraswati+Vihar%2C+Pitampura%2C+New+Delhi%2C+Delhi+110085!5e0!3m2!1sen!2sin!4v1445694152567" width="100%" height="250" frameborder="0" style="border:0" allowfullscreen></iframe>

<fieldset class="scheduler-border">
    <legend class="scheduler-border">Contact Us Form</legend>
	
<?php
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);
?>
<?php  
	echo $this->formHidden($form->get('id'));	
?>
	
    <div class="form-group">
    <div class="col-xs-4"><label><?php echo $this->translate('Name') ?> :</label></div>
    <div class="col-xs-8"><?php  echo $this->formRow($form->get('name'));?></div>
    </div>
    <div class="form-group">
    <div class="col-xs-4"><label><?php echo $this->translate('Email') ?> :</label></div>
    <div class="col-xs-8"><?php  echo $this->formRow($form->get('email'));?></div>
    </div>
    <div class="form-group">
    <div class="col-xs-4"><label><?php echo $this->translate('Mobile No') ?> :</label></div>
    <div class="col-xs-8"><?php  echo $this->formRow($form->get('phone_no'));?></div>
    </div>
    <div class="form-group">
    <div class="col-xs-4"><label><?php echo $this->translate('Message') ?> :</label></div>
    <div class="col-xs-8"><?php  echo $this->formRow($form->get('message'));?></div>
    </div>
    <div class="form-group">
    <div class="col-xs-4"></div>
    <div class="col-xs-8"><?php  echo $this->formRow($form->get('submit'));?></div>
    </div>
	
<?php echo $this->form()->closeTag(); ?>

</fieldset>

<div class="clearfix"></div>

</div>
