<?php 
// // print_r($Events_photos);
// foreach ($Events_photos as $photos) {

//   echo $photos->image."<br>";

// }

?>
<div class="col-sm-3 col-sm-3-new width20per">
<?php echo $this->partial('layout/sidebar') ?>
</div>


<div class="col-sm-9 width80per" id="links">
 <?php 
foreach ($Events_photos as $photos) {

 ?>
<h2 class="heading"><?=$photos->event_name; ?></h2>

  <div class="gallery">
  <div class="col-xs-4">
  <div class="col-xs-12"><a href="<?= empty($photos->image)? $this->basePath()."/images/new-big.jpg":$this->basePath().$photos->image; ?>" title="" data-gallery=""><img src="<?= empty($photos->image)? $this->basePath()."/images/new-big.jpg":$this->basePath().$photos->image; ?>" class="img-responsive" style="height:150px; width:100%;"/>
  <div class="img-title"><span style="float:left;"><?=$photos->event_name; ?></span><span style="float:right;">Delhi</span></div>
   
  </a>
    </div>
   <div class="img-title"><span style="float:left;"><?=date("d-m-Y",strtotime($photos->event_date))?></span><span style="float:right;"><?=date("h:i",strtotime($photos->start_time))?>pm</span></div>
  </div>
  
  
  
   
  <div class="clearfix"></div>
  </div>
  <?php 
  }
  ?>
 </div>

 <!-- The Bootstrap Image Gallery lightbox, should be a child element of the document body -->
<div id="blueimp-gallery" class="blueimp-gallery">
    <!-- The container for the modal slides -->
    <div class="slides"></div>
    <!-- Controls for the borderless lightbox -->
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
    <!-- The modal dialog, which will be used to wrap the lightbox content -->
    <div class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" aria-hidden="true">&times;</button>
                    <h4 class="modal-title"></h4>
                </div>
                <div class="modal-body next"></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left prev">
                        <i class="glyphicon glyphicon-chevron-left"></i>
                        Previous
                    </button>
                    <button type="button" class="btn btn-primary next">
                        Next
                        <i class="glyphicon glyphicon-chevron-right"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>