			  <div class="col-md-4 banner-bottom-grid" style="background:#eda344;">
					<?php echo $this->partial('layout/sidebar') ?>
					
				</div>
				<div class="col-md-42 banner-bottom-grid">
					
					<div class="faqs-top-grids">
				<div class="book-grids">
					<div class="col-md-61 book-left">
						<div class="book-left-info">
							<h3>Create Your Account</h3>
						</div>
						<div class="book-left-form">
							<form>
                            <p>User Type</p>
                            	<select name="UserType" onblur="if (this.value == '') {this.value ='';}">
                                <option>--Select--</option>
                                <option>Normel</option>
                                <option>Matrimonial</option>
                                <option>Executive</option>
                                
                                </select>
								
								<p>First Name</p>
								<input type="text" value="" onfocus="this.value='';" onblur="if (this.value == '') {this.value ='';}">
								<p>Last Name</p>
								<input type="text" value="" onfocus="this.value='';" onblur="if (this.value == '') {this.value ='';}">
								<p>Phone Number</p>
								<input type="text" value="" onfocus="this.value='';" onblur="if (this.value == '') {this.value ='';}">
								<p>Email Address</p>
								<input type="text" value="" onfocus="this.value='';" onblur="if (this.value == '') {this.value ='';}">
								<p>Password</p>
								<input type="password" name="password" id="password">
								<p>Confirm Password</p>
								<input type="password" name="password" id="password">
								<label for="checkbox"><input type="checkbox" id="checkbox"> 
I agree to the Privacy Policy and T&C. </label>
								<input type="submit" id="login" value="Register">
							</form>
						</div>
					</div>
                    
                    <div class="col-md-6 book-left book-right">
					  <div class="book-left-info">
							<h3>Recommended</h3>
						</div>
						<ul>
						  <li>Access booking history with upcoming trips</li>
							<li>Print tickets and invoices</li>
							<li>Make checkouts simpler</li>
							<li>Enter your contact details only once</li>
							<li>Get alerts for low fares</li>
					  </ul>
					</div>
					
					<div class="clearfix"> </div>
				</div>
			</div>
				</div>