<div class="col-sm-3 col-sm-3-new width20per">
<?php echo $this->partial('layout/sidebar') ?>
</div>

<div class="col-sm-9 width80per">

<h2 class="heading">SMS : Khubsurat</h2>
<div class="newsfull">

  <p>Kya Khubsurat Apka Andaj Hai,<br>
Hakikat Hai Ya Khwab Hai,<br>
Khush Nashibo Ke Paas Aap Rahte Ho,<br>
Humare Paas Bas Apki Mithi Si Yaad Hai.  </p><br>
 
<div class="clearfix"></div>

<div class="status" style="font-size:11px;">
<ul style="font-size:12px;">
<li style="font-size:12px;">Posted By : RC RustagiI </li>
<li style="font-size:12px;">Posted On : 28-12-2015</li>
<li style="font-size:12px;">Views: 2757</li>
<li style="font-size:12px;"> 143 Likes </li>
<li style="font-size:12px;"><a href="#"> Like it </a></li>

</ul>
</div>
<div id="panel" style="display:block !important;">
<div class="form-group">
<textarea id="commentBodyField" class="form-control" onkeypress="BLOG_CMT_onCommentBodyChange()" cols="50" rows="4" name="commentBody" placeholder="Enter your comment..."></textarea>
</div>
<div class="form-group row">
<label class="col-sm-2 form-control-label lblline">Comment As</label>

<div class="col-sm-3">
<select class="form-control">
	<option>Google Account</option>
    <option>Select Profile</option>
</select>
</div>
</div>

<div class="form-group row">

<div class="col-sm-6">


<input id="postCommentSubmit" type="button" class="btn btn-info" value="Publish"  name="postCommentSubmit">
<input id="postCommentPreview" type="button" class="btn btn-info" value="Preview" name="postCommentPreview">

</div>
</div>
</div>


<div class="clearfix"></div>
<div class="related">

<div class="col-md-12 news col-xs-12">
<div class="col-md-2 col-sm-2 col-xs-3">
<div class="related-img"><img src="<?php echo $this->basePath('images/related-img.jpg') ?>" /></div>
</div>
<div class="col-md-10 col-sm-10 col-xs-9 content">
<h4>Vijay </h4>
<p>What a great man,,makes us proud </p>

<p><a href="#">Like </a> <a href="#">Reply </a> <img src="<?php echo $this->basePath('images/liked-bg.png') ?>" style="float:leftl; padding-right:2px;"> 6</p>

</div>
</div>


<div class="col-md-12 news col-xs-12">
<div class="col-md-2 col-sm-2 col-xs-3">
<div class="related-img"><img src="<?php echo $this->basePath('images/related-img.jpg') ?>" /></div>
</div>
<div class="col-md-10 col-sm-10 col-xs-9 content">
<h4>Vijay </h4>
<p>What a great man,,makes us proud </p>

<p><a href="#">Like </a> <a href="#">Reply </a> <img src="<?php echo $this->basePath('images/liked-bg.png') ?>" style="float:leftl; padding-right:2px;"> 6</p>

</div>
</div>

</div>


<div class="clearfix"></div>
</div>
</div>
  