<div class="col-sm-3 col-sm-3-new width20per">
<?php echo $this->partial('layout/sidebar-about') ?>
</div>

<div class="col-sm-9 width80per">
<h2 class="heading">Team Member</h2>

<div class="tree">
	<ul>
		<li><a href="#">
       <div class="img-tag pull-left"><img src="<?php echo $this->basePath('images/tree-img.jpg') ?>"></div>
       <div class="pull-right">
       <p class="lead">T. G Rustagi</p>
        <p>President</p>
        <p>tgrustagi45@gmail.com</p>
        </div>
        </a>
			<ul>
            <li><a href="#">
            <div class="img-tag"><img src="<?php echo $this->basePath('images/tree-img.jpg') ?>"></div>
            <div class="col-xs-7">
            <p class="lead">Jacke Rustagi</p>
            <p>Vice President</p>
            <p>javkie452@gmail.com</p>
            </div>
            </a></li>
            
            <li><a href="#">
            <div class="img-tag"><img src="<?php echo $this->basePath('images/tree-img.jpg') ?>"></div>
            <div class="col-xs-7">
            <p class="lead">Jacke Rustagi</p>
            <p>Vice President</p>
            <p>javkie452@gmail.com</p>
            </div>
            </a></li>
            
            <li><a href="#">
            <div class="img-tag"><img src="<?php echo $this->basePath('images/tree-img.jpg') ?>"></div>
            <div class="col-xs-7">
            <p class="lead">Jacke Rustagi</p>
            <p>Vice President</p>
            <p>javkie452@gmail.com</p>
            </div>
            </a></li>
            
            <li><a href="#">
            <div class="img-tag"><img src="<?php echo $this->basePath('images/tree-img.jpg') ?>"></div>
            <div class="col-xs-7">
            <p class="lead">Jacke Rustagi</p>
            <p>Vice President</p>
            <p>javkie452@gmail.com</p>
            </div>
            </a></li>
            
            <li><a href="#">
            <div class="img-tag"><img src="<?php echo $this->basePath('images/tree-img.jpg') ?>"></div>
            <div class="col-xs-7">
            <p class="lead">Jacke Rustagi</p>
            <p>Vice President</p>
            <p>javkie452@gmail.com</p>
            </div>
            </a></li>
            </ul>
            </li>
	</ul>
</div>

<div class="tree">
	<ul>
		<li><a href="#">
       <div class="img-tag pull-left"><img src="<?php echo $this->basePath('images/tree-img.jpg') ?>"></div>
       <div class="pull-right">
       <p class="lead">T. G Rustagi</p>
        <p>President</p>
        <p>tgrustagi45@gmail.com</p>
        </div>
        </a>
			<ul>
            <li><a href="#">
            <div class="img-tag"><img src="<?php echo $this->basePath('images/tree-img.jpg') ?>"></div>
            <div class="col-xs-7">
            <p class="lead">Jacke Rustagi</p>
            <p>Vice President</p>
            <p>javkie452@gmail.com</p>
            </div>
            </a></li>
            
            <li><a href="#">
            <div class="img-tag"><img src="<?php echo $this->basePath('images/tree-img.jpg') ?>"></div>
            <div class="col-xs-7">
            <p class="lead">Jacke Rustagi</p>
            <p>Vice President</p>
            <p>javkie452@gmail.com</p>
            </div>
            </a></li>
            
            <li><a href="#">
            <div class="img-tag"><img src="<?php echo $this->basePath('images/tree-img.jpg') ?>"></div>
            <div class="col-xs-7">
            <p class="lead">Jacke Rustagi</p>
            <p>Vice President</p>
            <p>javkie452@gmail.com</p>
            </div>
            </a></li>
            
            <li><a href="#">
            <div class="img-tag"><img src="<?php echo $this->basePath('images/tree-img.jpg') ?>"></div>
            <div class="col-xs-7">
            <p class="lead">Jacke Rustagi</p>
            <p>Vice President</p>
            <p>javkie452@gmail.com</p>
            </div>
            </a></li>
            
            <li><a href="#">
            <div class="img-tag"><img src="<?php echo $this->basePath('images/tree-img.jpg') ?>"></div>
            <div class="col-xs-7">
            <p class="lead">Jacke Rustagi</p>
            <p>Vice President</p>
            <p>javkie452@gmail.com</p>
            </div>
            </a></li>
            </ul>
            </li>
	</ul>
</div>

<div class="tree">
	<ul>
		<li><a href="#">
       <div class="img-tag pull-left"><img src="<?php echo $this->basePath('images/tree-img.jpg') ?>"></div>
       <div class="pull-right">
       <p class="lead">T. G Rustagi</p>
        <p>President</p>
        <p>tgrustagi45@gmail.com</p>
        </div>
        </a>
			<ul>
            <li><a href="#">
            <div class="img-tag"><img src="<?php echo $this->basePath('images/tree-img.jpg') ?>"></div>
            <div class="col-xs-7">
            <p class="lead">Jacke Rustagi</p>
            <p>Vice President</p>
            <p>javkie452@gmail.com</p>
            </div>
            </a></li>
            
            <li><a href="#">
            <div class="img-tag"><img src="<?php echo $this->basePath('images/tree-img.jpg') ?>"></div>
            <div class="col-xs-7">
            <p class="lead">Jacke Rustagi</p>
            <p>Vice President</p>
            <p>javkie452@gmail.com</p>
            </div>
            </a></li>
            
            <li><a href="#">
            <div class="img-tag"><img src="<?php echo $this->basePath('images/tree-img.jpg') ?>"></div>
            <div class="col-xs-7">
            <p class="lead">Jacke Rustagi</p>
            <p>Vice President</p>
            <p>javkie452@gmail.com</p>
            </div>
            </a></li>
            
            <li><a href="#">
            <div class="img-tag"><img src="<?php echo $this->basePath('images/tree-img.jpg') ?>"></div>
            <div class="col-xs-7">
            <p class="lead">Jacke Rustagi</p>
            <p>Vice President</p>
            <p>javkie452@gmail.com</p>
            </div>
            </a></li>
            
            <li><a href="#">
            <div class="img-tag"><img src="<?php echo $this->basePath('images/tree-img.jpg') ?>"></div>
            <div class="col-xs-7">
            <p class="lead">Jacke Rustagi</p>
            <p>Vice President</p>
            <p>javkie452@gmail.com</p>
            </div>
            </a></li>
            </ul>
            </li>
	</ul>
</div>


<div class="clearfix"></div>

</div>

<!--<div class="col-sm-9 width80per">
<h2 class="heading">Rohini Branch</h2>
<img src="<?php //echo $this->basePath('img/community1.jpg') ?>">
<img src="<?php //echo $this->basePath('img/community2.jpg') ?>">
</div>-->
