<div class="col-sm-3 col-sm-3-new width20per">
<?php echo $this->partial('layout/sidebar-about') ?>
</div>

<div class="col-sm-9 width80per">
    <h2 class="heading">Our Vision</h2>
<p>As mentioned we have big plans to expand the features of this site in 2016. However, the site is not self-sustaining at the moment so we will also have to look at ways to increase revenue at the same time. Post your ads on a minimal price on our website which will promote your business and as well as our step towards development.</p>

<p>Our goal for this site is that it becomes one of the best sources of accurate, current information about the Rustagi people groups of Rohini branch and Later on All India Basis The only way to achieve this is to engage more of our users to become regular contributors and to rapidly expand the breadth and depth of information we publish here.</p>

<p>Please consider registering as a member (free) and contributing articles, photos, or just comments. Articles do not need to be lengthy – they could be as simple as a review of another website that contains useful/interesting information relevant to our users. We also want to see more personal stories so if you have one you’d like to share or read one online that we can link to that that would be most welcome.</p>

  </div>